// Language-name patterns. key = iso-ish code used in courses.target_lang / known_lang
// eng: English exonym regex (for scanning known_text)
// tgt: regex covering endonym + exonyms in many orthographies (for scanning target_text)
// Patterns are applied case-insensitively to NFC text with diacritics stripped as a second pass.
module.exports = {
 yor:{eng:/yoruba/i, tgt:/(yorub|yorùb|jorub|iorub|ioruv|ジョルバ|ヨルバ|约鲁巴|約魯巴|요루바|יאָרובאַ|יורובה|يوروب|ยอรูบา|योरूब|ಯೊರುಬ|యోరుబ)/i},
 eng:{eng:/english/i, tgt:/(english|inglés|ingles|inglese|inglés|anglais|englisch|engels|inglês|angol|anglick|anglič|angliť|englanti|engelsk|αγγλικ|английск|англійськ|англиск|енглеск|ingliz|angielsk|englez|ingilizce|英語|英语|英文|영어|영문|अंग्रे|ইংরে|ஆங்கில|ఇంగ్లీ|ಇಂಗ್ಲಿ|अंग्रेज|انجليزي|إنجليزي|انگلیسی|انگریزی|אנגלי|ภาษาอังกฤษ|อังกฤษ|saesneg|sasnaeg|béarla|beurla|sowsnek|saoznek|inglish|ingliss|anglés|anglès|angliar|eangla|ingelsa|englesch|ingurese)/i},
 cym:{eng:/welsh/i, tgt:/(cymraeg|gymraeg|nghymraeg|chymraeg|walisisch|gallois|galés|gales|gallese|wels|валлийск|ウェールズ語|威尔士|웨일스|kembraeg|breatnais|breatnaise|cuimris|welsh)/i},
 fur:{eng:/friulian/i, tgt:/(furlan|friulan|friulian|フリウリ|弗留利)/i},
 roh:{eng:/romansh|romansch/i, tgt:/(rumantsch|romontsch|rumauntsch|romanch|romancio|romanche|rätoroman|retoroman|ロマンシュ)/i},
 vec:{eng:/venetian/i, tgt:/(v[eè]neto|venet|venez|venesian|ヴェネト)/i},
 lmo:{eng:/lombard/i, tgt:/(lombard|lumbard|ロンバル)/i},
 nap:{eng:/neapolitan/i, tgt:/(napulitan|napoletan|neapolitan|napolitan)/i},
 scn:{eng:/sicilian/i, tgt:/(sicilian|sicilianu|siciliano|sizilian)/i},
 rgn:{eng:/romagnol/i, tgt:/(rumagn[oò]l|romagnol)/i},
 sme:{eng:/(northern\s+)?s[aá]mi|lapp/i, tgt:/(s[aá]megiel|s[aá]mi|samisk|saami|同?サーミ)/i},
 cor:{eng:/cornish/i, tgt:/(kernewek|gernewek|kernow(ek)?|cornish|cornico|cornique|kornisch)/i},
 bre:{eng:/breton/i, tgt:/(brezhoneg|vrezhoneg|breton|bretone|bretonisch|bretón)/i},
 gle:{eng:/irish|gaeilge/i, tgt:/(gaeilge|ngaeilge|ghaeilge|irish|irlandes|irlandais|irisch|iers|ирландск)/i},
 gla:{eng:/(scottish\s+)?gaelic|scots gaelic/i, tgt:/(g[aà]idhlig|gaelic|gaélico|gaélique|g[aä]lisch)/i},
 spa:{eng:/spanish|castilian/i, tgt:/(espa[nñ]ol|castellan|spanisch|spaans|spagnol|espanhol|espagnol|hiszpa|španěl|španjol|шпански|испанск|іспанськ|spanska|spansk|espanjä?a|espanja|スペイン|西班牙|스페인|sbaeneg|spáinnis|spainnis|spaeneg)/i},
 fra:{eng:/french/i, tgt:/(fran[cç]ais|franz[oö]sisch|frans|franc[eé]s|frances|francese|francuz|francusk|franciá|ranska|fransk|француз|フランス|法語|法语|프랑스|ffrangeg|fraincis|fh?rangais|galleg)/i},
 deu:{eng:/german/i, tgt:/(deutsch|duits|alem[aá]n|allemand|tedesc|niemieck|německ|немецк|німецьк|nemačk|tysk|saksa|ドイツ|德語|德语|독일|almanca|almaenimee?g|almaeneg|gearmáinis|gearmailtis|alamaneg)/i},
 ita:{eng:/italian/i, tgt:/(italian|italien|italiaans|italiensk|italia|włosk|итальянск|італійськ|italijansk|イタリア|意大利|義大利|이탈리아|eidaleg|iodáilis|eadailtis|italianeg|talianu|itailhan)/i},
 por:{eng:/portuguese/i, tgt:/(portugu[eê]s|portugies|portugees|portugalsk|португальск|ポルトガル|葡萄牙|포르투갈|portugaleg|portaingéilis)/i},
 zho:{eng:/(mandarin|chinese)/i, tgt:/(中文|漢語|汉语|中国語|中國話|普通话|普通話|chinesisch|chinees|chino|chinois|cinese|chiń|čínšt|китайск|kiina|kines|中国語|중국어|tsieinëeg|tsieineeg|sínis|síneach)/i},
 jpn:{eng:/japanese/i, tgt:/(日本語|japan[ei]s|japon[eê]s|japonais|giappones|japoń|японск|japani|japansk|일본어|siapan|seapáinis)/i},
 kor:{eng:/korean/i, tgt:/(한국어|조선말|korean|korean?isch|corean|cor[eé]en|corean|kore[ai]|коре[йи]ск|韓國語|韓国語|韩语)/i},
 rus:{eng:/russian/i, tgt:/(русск|russi[as]ch|russisch|russe|ruso|russo|rosyjsk|rusk|venäj|ロシア|俄語|俄语|러시아|rwseg|rúisis)/i},
 nld:{eng:/dutch|netherlandic/i, tgt:/(nederlands|niederl[aä]nd|hollands|neerland|olandes|holand[eé]s|hollan|オランダ|荷蘭|荷兰|네덜란드|iseldireg|ollainnis)/i},
 pol:{eng:/polish/i, tgt:/(polski|polnisch|polonais|polaco|polacco|pools|польск|puola|polsk|ポーランド|波蘭|波兰)/i},
 swe:{eng:/swedish/i, tgt:/(svensk|schwedisch|su[eè]dois|sueco|svedese|zweeds|шведск|ruotsi|スウェーデン)/i},
 nor:{eng:/norwegian/i, tgt:/(norsk|norwegisch|norv[eé]g|noruego|noorse?|норвежск|norja|ノルウェー)/i},
 dan:{eng:/danish/i, tgt:/(dansk|d[aä]nisch|danois|dan[eé]s|deens|датск|tanska)/i},
 fin:{eng:/finnish/i, tgt:/(suomi|suome|finnisch|finnois|finland[eé]s|fins|финск|finsk)/i},
 isl:{eng:/icelandic/i, tgt:/(íslensk|islensk|isl[aä]ndisch|island[eê]s|islandais|ijslands|исландск|islanti)/i},
 ces:{eng:/czech/i, tgt:/(češt|cesk|tschechisch|tch[eè]que|checo|ceco|tsjechisch|чешск|tšekki)/i},
 hun:{eng:/hungarian/i, tgt:/(magyar|ungarisch|hongrois|h[uú]ngaro|ungherese|hongaars|венгерск|unkari)/i},
 ell:{eng:/greek/i, tgt:/(ελληνικ|griechisch|grec|griego|greco|grieks|греческ|kreikka|グリシャ|ギリシャ)/i},
 tur:{eng:/turkish/i, tgt:/(t[uü]rk[cç]e|t[uü]rkisch|turc|turco|turks|турецк|トルコ)/i},
 ara:{eng:/arabic/i, tgt:/(عرب|arabisch|arabe|[aá]rabe|arabo|arabisk|арабск|arabia|アラビア|阿拉伯)/i},
 heb:{eng:/hebrew/i, tgt:/(עברית|hebr[aä]isch|h[eé]breu|hebreo|ebraico|hebreeuws|иврит|heprea|ヘブライ)/i},
 yid:{eng:/yiddish/i, tgt:/(ייִדיש|jiddisch|yiddish|yidish|идиш)/i},
 hin:{eng:/hindi/i, tgt:/(हिन्दी|हिंदी|hindi|ヒンディー|印地)/i},
 ben:{eng:/bengali|bangla/i, tgt:/(বাংলা|bengal|bangla|ベンガル)/i},
 tam:{eng:/tamil/i, tgt:/(தமிழ்|tamil|タミル)/i},
 tel:{eng:/telugu/i, tgt:/(తెలుగు|telugu)/i},
 kan:{eng:/kannada/i, tgt:/(ಕನ್ನಡ|kannada)/i},
 mar:{eng:/marathi/i, tgt:/(मराठी|marathi)/i},
 guj:{eng:/gujarati/i, tgt:/(ગુજરાતી|gujarati)/i},
 pan:{eng:/punjabi|panjabi/i, tgt:/(ਪੰਜਾਬੀ|پنجابی|punjabi|panjabi)/i},
 urd:{eng:/urdu/i, tgt:/(اردو|urdu)/i},
 nep:{eng:/nepali/i, tgt:/(नेपाली|nepali)/i},
 sin:{eng:/sinhala|sinhalese/i, tgt:/(සිංහල|sinhala|singhal)/i},
 tha:{eng:/thai/i, tgt:/(ไทย|thail[aä]ndisch|thai|タイ語)/i},
 ind:{eng:/indonesian/i, tgt:/(bahasa indonesia|indonesisch|indon[eé]si|indonesian)/i},
 swa:{eng:/swahili|kiswahili/i, tgt:/(swahili|suaheli)/i},
 afr:{eng:/afrikaans/i, tgt:/(afrikaans)/i},
 mlt:{eng:/maltese/i, tgt:/(malti|maltesisch|maltais|malt[eé]s|maltese)/i},
 eus:{eng:/basque/i, tgt:/(euskara|euskera|baskisch|basque|vasco|vascuence)/i},
 cat:{eng:/catalan/i, tgt:/(catal[aà]|katalanisch|catal[aá]n|catalano|catalaans)/i},
 glg:{eng:/galician/i, tgt:/(galego|galicisch|galicien|gallego|galiziano)/i},
 ron:{eng:/romanian|rumanian/i, tgt:/(rom[aâ]n[aă]|rum[aä]nisch|roumain|rumano|rumeno)/i},
 bul:{eng:/bulgarian/i, tgt:/(български|bulgarisch|bulgare|b[uú]lgaro|bulgaars)/i},
 hrv:{eng:/croatian/i, tgt:/(hrvatski|kroatisch|croate|croata|kroatisch)/i},
 srp:{eng:/serbian/i, tgt:/(српски|srpski|serbisch|serbe|serbio|servo)/i},
 mkd:{eng:/macedonian/i, tgt:/(македонски|makedonisch|mac[eé]doni|macedonio)/i},
 ukr:{eng:/ukrainian/i, tgt:/(українськ|ukrainisch|ukrainien|ucraniano|oekraïens)/i},
 lav:{eng:/latvian/i, tgt:/(latviešu|lettisch|letton|let[oó]n)/i},
 lit:{eng:/lithuanian/i, tgt:/(lietuvi|litauisch|lituanien|lituano)/i},
 est:{eng:/estonian/i, tgt:/(eesti|estnisch|estonien|estonio|viro)/i},
 fas:{eng:/persian|farsi/i, tgt:/(فارسی|persisch|persan|persa|farsi)/i},
 hye:{eng:/armenian/i, tgt:/(հայերեն|armenisch|arm[eé]nien|armenio)/i},
 yue:{eng:/cantonese/i, tgt:/(粵語|粤语|廣東話|广东话|kantonesisch|cantonais|canton[eé]s)/i},
 hak:{eng:/hakka/i, tgt:/(客家|hakka)/i},
 nan:{eng:/hokkien|min nan|taiwanese/i, tgt:/(閩南|闽南|台語|臺語|hokkien)/i},
 pdc:{eng:/pennsylvania (dutch|german)/i, tgt:/(deitsch|pennsilfaanisch)/i},
};
