#!/usr/bin/env node

/**
 * Phase 1: Pedagogical Translation for Spanish
 *
 * Translates 668 canonical seeds from English to Spanish
 * Applies 6 pedagogical heuristics + Spanish-specific rules
 */

const fs = require('fs-extra');
const path = require('path');
const crypto = require('crypto');

// Spanish-specific translation rules
const SPANISH_RULES = {
  // Keep reflexive verbs together
  reflexive_verbs: ['me gusta', 'se puede', 'nos vamos', 'te parece', 'me llamo', 'se llama'],

  // Don't split compound prepositions
  compound_prepositions: ['a través de', 'al lado de', 'en vez de', 'delante de', 'detrás de', 'cerca de', 'lejos de', 'encima de', 'debajo de', 'después de', 'antes de'],

  // Keep idiomatic expressions intact
  idioms: ['tener que', 'hay que', 'estar de acuerdo', 'darse cuenta', 'echar de menos', 'hacer falta', 'tener ganas', 'llegar a ser'],

  // Keep verb phrases together
  verb_phrases: ['ir a', 'acabar de', 'volver a', 'tener que', 'haber que', 'deber', 'poder', 'querer'],

  // Avoid splitting estas construcciones
  keep_together: ['¿Cómo estás?', '¿Qué tal?', 'por favor', 'muchas gracias', 'de nada', 'lo siento', 'está bien', 'no importa']
};

// High-quality translations for 668 seeds
// Following pedagogical heuristics: naturalness, frequency, clarity, brevity, consistency, utility
const TRANSLATIONS = {
  1: "Quiero hablar español contigo ahora.",
  2: "Estoy intentando aprender.",
  3: "cómo hablar lo más posible.",
  4: "cómo decir algo en español",
  5: "Voy a practicar hablando con otra persona.",
  6: "Estoy intentando recordar una palabra.",
  7: "Quiero intentar con todas mis fuerzas hoy.",
  8: "Voy a intentar explicar lo que quiero decir.",
  9: "Hablo un poco de español ahora.",
  10: "No estoy seguro de que pueda recordar la frase completa.",
  11: "Me gustaría poder hablar después de que termines.",
  12: "No me gustaría adivinar lo que va a pasar mañana.",
  13: "Hablas español muy bien.",
  14: "¿Hablas español todo el día?",
  15: "Y quiero que hables español conmigo mañana.",
  16: "Él quiere volver con todos los demás más tarde.",
  17: "Ella quiere averiguar cuál es la respuesta.",
  18: "Queremos reunirnos a las seis de la tarde.",
  19: "Pero no quiero dejar de hablar.",
  20: "Quieres aprender su nombre rápidamente.",
  21: "¿Por qué estás aprendiendo su nombre?",
  22: "Porque quiero conocer gente que hable español.",
  23: "Voy a empezar a hablar más pronto.",
  24: "No voy a poder recordar fácilmente.",
  25: "¿Vas a ayudarme antes de que tenga que irme?",
  26: "Me gusta sentir como si estuviera casi listo para ir.",
  27: "No me gusta tardar demasiado en responder.",
  28: "Es útil empezar a hablar tan pronto como puedas.",
  29: "Tengo ganas de hablar mejor tan pronto como pueda.",
  30: "Quería preguntarte algo ayer.",
  31: "Querías hablar conmigo esta noche.",
  32: "¿Querías enseñarme algo?",
  33: "¿Cuánto tiempo llevas aprendiendo español?",
  34: "Él no quiere estar callado cuando hay otra gente aquí.",
  35: "Ella no quiere leer nada esta tarde.",
  36: "No queremos interrumpir la historia.",
  37: "Empecé a pensar en ello con cuidado el mes pasado.",
  38: "He estado aprendiendo durante una semana aproximadamente.",
  39: "Pero estoy un poco cansado esta mañana.",
  40: "¿Cómo te sientes en este momento?",
  41: "Me siento bien, pero estoy empezando a sentirme cansado.",
  42: "Estaba empezando a sentirme mejor que anoche.",
  43: "No estaba pensando en cómo responder.",
  44: "O si necesito mejorar.",
  45: "No necesito saberlo todo.",
  46: "Pero no me preocupo por cometer errores.",
  47: "Porque creo que es bueno cometer errores.",
  48: "No me importa cometer errores.",
  49: "Es así, si sabes lo que quiero decir.",
  50: "No estoy intentando terminar lo más rápido posible.",
  51: "Disfruto haciendo cosas interesantes con mis amigos.",
  52: "Él quería escribir una carta a su amigo la semana pasada.",
  53: "Ella quería poner su carta en su bolso.",
  54: "Queríamos darte un poco más de tiempo.",
  55: "No disfruto despertándome cuando no he dormido bien.",
  56: "Así puedo recordar cómo decir algunas palabras.",
  57: "No puedo recordar cómo decir lo que quería decir.",
  58: "Es interesante cuando entiendes suficientes palabras.",
  59: "Sé cómo hacer lo que necesito hacer la semana que viene.",
  60: "No sé cómo decir suficientes palabras diferentes todavía.",
  61: "¿Podrías decir eso otra vez un poco más despacio?",
  62: "No estoy seguro de que pueda ayudarte al mismo tiempo.",
  63: "¿Estás seguro de que no te importa ayudarme?",
  64: "Aprender español no es fácil pero es divertido.",
  65: "Es importante tomar tiempo para ponerte a prueba.",
  66: "No es difícil encontrar la respuesta.",
  67: "¿Por qué quieres parar?",
  68: "¿Qué estás buscando?",
  69: "Él no quería cuidar al perro joven toda la tarde.",
  70: "Ella no quería decirme dónde estaba.",
  71: "No queríamos dejar que nadie oyera la verdad.",
  72: "Creo que lo estás haciendo muy bien.",
  73: "Muchas gracias, pero tengo más que aprender.",
  74: "Muchas gracias por ayudarme a entender.",
  75: "¿Tienes más que aprender?",
  76: "Estoy muy feliz con cuánto he aprendido ya.",
  77: "Me sorprende lo rápido que estoy empezando a entender.",
  78: "No entiendo lo que dijiste.",
  79: "¿Cuándo empezaste a aprender?",
  80: "No estoy seguro de cuándo estaré listo.",
  81: "¿Cuándo quieres empezar?",
  82: "No voy a esperarte. ¿Por qué no?",
  83: "Estoy de acuerdo con lo que dijiste sobre tu amigo.",
  84: "No estoy de acuerdo con lo que él dijo sobre mi amigo.",
  85: "No conozco a esa gente.",
  86: "No fue posible, desafortunadamente.",
  87: "Son gente que no conozco.",
  88: "No estoy listo para hablar con gente que no conozco todavía.",
  89: "Creo que he hecho mucho en poco tiempo.",
  90: "Si puedes hablar más despacio eso sería genial.",
  91: "Es difícil pensar lo suficientemente rápido para responder a tiempo.",
  92: "Me gustaría seguir haciendo esto por un tiempo.",
  93: "Es hora de irse ahora.",
  94: "Esta es la única manera en que funcionará.",
  95: "¿Estás listo para ir a casa en el próximo autobús?",
  96: "No, todavía no estoy listo, necesito un poco más de tiempo.",
  97: "Sí, estoy listo para ir tan pronto como quieras.",
  98: "Debería considerar tocar algo más.",
  99: "Deberías preguntarte por qué no está funcionando.",
  100: "No deberías preocuparte por hacer algo similar.",
  101: "Disfruto descubriendo más sobre este idioma.",
  102: "Estamos intentando decir que no es así.",
  103: "No estamos intentando escuchar muchas más palabras.",
  104: "Necesitamos cambiar lo que estamos haciendo.",
  105: "Por eso él no sabía la respuesta.",
  106: "No necesitamos sentirnos felices, solo necesitamos trabajar duro.",
  107: "Esperábamos ver lo que estabas haciendo.",
  108: "No esperábamos despertarnos en medio de la noche.",
  109: "Debemos trabajar duro para aprender muchas palabras nuevas.",
  110: "Somos amigos, y después de que terminemos me gustaría relajarme.",
  111: "Cuando aprendemos algo nuevo cambia nuestro cerebro.",
  112: "Eso fue muy interesante, y no lo esperaba.",
  113: "¿Por qué no puedo recordar lo que dijiste?",
  114: "Siento como si lo estuviera haciendo peor hoy que ayer.",
  115: "No siento como si estuviera listo para tener una conversación.",
  116: "Esta no es la mejor elección que podría hacer.",
  117: "Definitivamente lo estoy haciendo mejor que la última vez que hablamos.",
  118: "Me siento mejor que cuando estábamos en el bar.",
  119: "¿Puedo preguntarte algo antes de que te vayas?",
  120: "Es interesante que te guste ir en autobús.",
  121: "Es poco común que no te guste usar tu coche.",
  122: "Está empezando a sentirse más fácil y estoy emocionado por cómo va.",
  123: "Creo que es una buena idea.",
  124: "Pensé que era una buena idea.",
  125: "Creo que tu idea fue muy buena.",
  126: "Este trabajo está cambiando la forma de mi cerebro.",
  127: "Esa no es la razón por la que quería verte.",
  128: "Eres como alguien que solía conocer.",
  129: "Estoy tan feliz de que lo estés haciendo tan bien.",
  130: "Eso fue una sorpresa, porque él es mi amigo.",
  131: "Hay demasiadas ideas dando vueltas en mi cabeza.",
  132: "Eso es menos emocionante que lo que ella estaba diciendo.",
  133: "Llegas a conocer muy bien a alguien cuando trabajas juntos.",
  134: "No es un problema cuando trabajas en algo difícil con ellos.",
  135: "No sé por qué piensas que es tan bueno.",
  136: "Por supuesto que puedes preguntarle porque es mi amiga.",
  137: "Es más importante hablar a menudo que ser perfecto.",
  138: "Aquí era donde mi amigo quería reunirnos.",
  139: "Siento tener que irme tan temprano.",
  140: "Siento no poder ver lo que estás intentando mostrarme.",
  141: "No hay problema. Todo está bien.",
  142: "Eres muy amable y te estoy agradecido por ayudar.",
  143: "Es lo mismo de lo que estábamos hablando antes.",
  144: "Me desperté más temprano de lo que quería esta mañana.",
  145: "¿Por qué ya no eres feliz?",
  146: "Nada parece estar funcionando desde que intentamos arreglarlo.",
  147: "Ella fue muy amable cuando me vio nervioso.",
  148: "Él no fue muy paciente cuando no pude responder.",
  149: "Esto no es muy difícil, así que espero que termines pronto.",
  150: "¿Puedes decirme cuál es tu nombre?",
  151: "Eso no fue lo que esperaba que pasara.",
  152: "Lo habría hecho diferente si hubiera sabido lo que querías.",
  153: "No lo habría dicho exactamente de la misma manera.",
  154: "¿Dónde quieres reunirte el sábado por la noche?",
  155: "No me importa esperar unos minutos mañana por la mañana.",
  156: "¿Quieres ir a un restaurante esta noche?",
  157: "No podré estar allí el mes que viene.",
  158: "Hablemos de otra cosa.",
  159: "Eso no es lo que estoy intentando decir.",
  160: "¿Cómo se dice esta palabra en español?",
  161: "¿Puedes darme ese libro el domingo por la mañana?",
  162: "¿Qué piensas sobre eso?",
  163: "Creo que es interesante.",
  164: "Un libro interesante",
  165: "Pero no estoy seguro de que sea verdad.",
  166: "Mi nombre no es muy poco común.",
  167: "¿Qué necesitas hacer mañana por la tarde?",
  168: "Y luego podré venir y ayudar más tarde.",
  169: "¿Qué quieres que haga?",
  170: "Me gustaría que me dijeras lo que necesitas.",
  171: "¿Quieres que te ayude a buscarlo?",
  172: "Sí, eso sería muy útil.",
  173: "No gracias, puedo arreglármelas solo.",
  174: "¿Puedes entender lo que estoy diciendo?",
  175: "¿Qué quieres hacer el domingo por la mañana?",
  176: "Le preguntaré si podrá ayudar el año que viene.",
  177: "Le preguntaré dónde quiere ir.",
  178: "No tuve tiempo, aunque quería verte.",
  179: "¿Qué vas a hacer el domingo por la tarde?",
  180: "Me gustaría leer mi libro por un rato.",
  181: "Pero tengo que llevar a mi madre al médico.",
  182: "¿Has visto mis llaves en alguna parte?",
  183: "No, me temo que no las he visto.",
  184: "Sí, las vi en la oficina hace un rato.",
  185: "Creo que las dejaste en el trabajo.",
  186: "¿Quieres hablar de algo diferente la semana que viene?",
  187: "Estoy feliz hasta ahora.",
  188: "Así que no necesito cambiar.",
  189: "Sí, es una buena idea.",
  190: "¿Te importa si te hago algunas preguntas?",
  191: "No, no me importa en absoluto.",
  192: "Estoy ocupado mañana por la noche.",
  193: "Lo siento pero estoy demasiado ocupado hoy.",
  194: "¿Qué estás buscando?",
  195: "Estoy intentando encontrar el dinero que dejé en la mesa.",
  196: "¿Has oído la última idea?",
  197: "Mi hijo trabaja como profesor.",
  198: "Mi hija trabaja para el ayuntamiento.",
  199: "Mi amigo solía trabajar en una oficina.",
  200: "Dicen que quieren asegurarse de que terminemos todo a tiempo.",
  201: "Queríamos saber qué iba a pasar.",
  202: "Nadie estaba seguro de cómo responder la pregunta.",
  203: "¿Qué harías si te pidiera que me ayudaras?",
  204: "Quería que ella te ayudara a ocuparte de los arreglos.",
  205: "He olvidado la palabra que estaba intentando decir.",
  206: "Disfruto la oportunidad de practicar hablando contigo.",
  207: "Has hecho lo que necesitabas hacer.",
  208: "No quería preguntarte cómo decirlo.",
  209: "Quieren pasar más tiempo reuniéndose como grupo.",
  210: "Piensan que necesitamos discutir el problema.",
  211: "Nos dijeron que no querían explicar.",
  212: "Querían pedir ayuda.",
  213: "No sabemos qué están intentando lograr.",
  214: "¿Lo pasaste bien el fin de semana?",
  215: "Salí el sábado por la noche.",
  216: "Vi a unos amigos.",
  217: "Tomé un vaso o dos de agua.",
  218: "No hice mucho el domingo.",
  219: "Fue agradable relajarse por un rato.",
  220: "¿Viste un poco de televisión?",
  221: "Vi el fútbol y luego vi una película.",
  222: "Él está intentando decirme lo que quiere",
  223: "Él va a preguntarte mañana.",
  224: "Él acaba de empezar a aprender.",
  225: "Él te daría una respuesta si pudiera.",
  226: "El hombre está intentando ayudarme.",
  227: "Ese hombre va a decirme algo nuevo.",
  228: "Ese hombre acaba de empezar a practicar hablando.",
  229: "Esa mujer te ayudaría si pudiera.",
  230: "Conozco a un hombre joven que quiere trabajar contigo.",
  231: "Conozco a un hombre mayor que quería pedir ayuda.",
  232: "Conozco a una mujer mayor que puede recordar la respuesta.",
  233: "Conozco a una mujer joven que conoce a tu hermana.",
  234: "Conocí a alguien anoche que trabaja con tu hermano.",
  235: "Conocí a alguien que dijo que quería decirte algo.",
  236: "Conozco a alguien que dijo que iba a intentar ayudar.",
  237: "Él quería que te dijera antes del fin de semana.",
  238: "Él quería que me dijeras ayer.",
  239: "A mi madre le gusta leer.",
  240: "A mi padre no le gusta dejar de hablar.",
  241: "No quiero dárselo.",
  242: "Quiero darle más tiempo.",
  243: "Voy a pedir lo mismo para comer.",
  244: "Ya he aprendido mucho",
  245: "Estoy feliz con cuánto he hecho en poco tiempo",
  246: "Quería que ella te ayudara pero estaba demasiado ocupada.",
  247: "Pensé que ese libro era bastante bueno.",
  248: "Pensé que la película era una completa basura y quiero que me devuelvan el dinero.",
  249: "Quiero que me ayudes antes de que te vayas.",
  250: "¿Puedes decirme algo más antes de que responda?",
  251: "No quiero descubrirlo hasta después de que terminemos.",
  252: "¿Cuándo estarás listo para empezar?",
  253: "Debería estar listo en unos minutos.",
  254: "He estado listo desde esta mañana.",
  255: "¿Cuándo crees que estarás listo para irte?",
  256: "Creo que estaré listo en menos de una hora.",
  257: "Me gusta esa cosa azul.",
  258: "¿Qué es esa cosa azul de ahí?",
  259: "Una idea.",
  260: "No tengo ni la menor idea.",
  261: "Creo que podría ser algo importante.",
  262: "¿Quién era ese hombre con el que estabas hablando ayer?",
  263: "No sé a quién te refieres.",
  264: "Un hombre mayor.",
  265: "Un amigo.",
  266: "Era un viejo amigo de mi padre.",
  267: "¿Has tenido noticias de tu amigo?",
  268: "Sí, me envió dos correos la semana pasada.",
  269: "¿Por qué no quieres esperar a tu padre?",
  270: "Porque me preocupa que vaya a llegar tarde.",
  271: "¿Te gustaría venir con nosotros el mes que viene?",
  272: "Sí, eso suena como una gran idea.",
  273: "No, desafortunadamente tengo demasiado trabajo.",
  274: "¿Tienes que irte en unos días?",
  275: "Más tiempo.",
  276: "No, puedo quedarme aquí un poco más de tiempo.",
  277: "Sí, tengo una reunión importante a principios de la semana que viene.",
  278: "¿Tuviste que terminar todo anoche?",
  279: "Sí, porque no quedaba mucho tiempo.",
  280: "No, solo tuve que hacer el trabajo más importante.",
  281: "¿Te importa si termino mi café antes de que empieces?",
  282: "No, eso no es un problema.",
  283: "¿Cuál de tus amigos habla español?",
  284: "¿Conoces al amigo de mi hermana?",
  285: "Ella habla español.",
  286: "Gente a la que le gusta hablar español.",
  287: "¿Cuánta gente conoces a la que le guste ver televisión?",
  288: "La mayoría de la gente que conozco le gusta ver televisión.",
  289: "Me pregunto si ella va a estar allí esta tarde.",
  290: "Me pregunto si él sabe la respuesta.",
  291: "Espero poder hablar mejor pronto.",
  292: "Espero que puedas venir a la fiesta.",
  293: "Tengo que averiguar dónde va a reunirse conmigo.",
  294: "No tengo suficiente tiempo para llamarte esta noche.",
  295: "No dije que quisiera terminar en un día.",
  296: "Dije que necesitaba un poco más de tiempo.",
  297: "No conozco mucha gente que hable español.",
  298: "No me queda nada que decir.",
  299: "Él quiere pagar la mitad.",
  300: "Ella no quiere parecer antipática.",
  301: "Él dijo que quiere mostrarte algo.",
  302: "Ella dijo que no quiere vivir en una ciudad.",
  303: "Creo que él quiere sentarse.",
  304: "Creo que ella no quiere trabajar desde casa.",
  305: "Mujer.",
  306: "Conozco a esa mujer joven que está hablando con tu amigo.",
  307: "Conozco a ese hombre joven que está sentado allí.",
  308: "Sí, es amiga de mi madre.",
  309: "No, nunca la he visto antes.",
  310: "Ella podría escribir una historia sobre ese hombre.",
  311: "Él no podía creer los tres hechos más importantes.",
  312: "Ella dijo que podría usar la otra habitación mañana por la noche.",
  313: "Él dijo que no podía ver los cinco juegos.",
  314: "Creo que ella podría ponerlo en la mesa.",
  315: "Creo que él no podía permitirse el coche que quería.",
  316: "¿Crees que ella podría traer a su hermano el lunes?",
  317: "Sí, creo que podría si quisiera.",
  318: "No, no creo que pudiera esta vez.",
  319: "Ella necesita mudarse a un país diferente.",
  320: "Él no necesita comprar otro televisor este año.",
  321: "Un libro.",
  322: "Ella dijo que necesita leer el mismo libro.",
  323: "Él dijo que no necesita caminar a la escuela.",
  324: "Ese estudiante tiene ambas manos levantadas.",
  325: "Creo que él necesita considerar diez problemas posibles.",
  326: "No creo que ella necesite vender la empresa.",
  327: "¿Crees que ella necesita ofrecer otra manera?",
  328: "Sí, creo que debería.",
  329: "Es importante.",
  330: "No, no creo que sea muy importante.",
  331: "Ella no puede proporcionar todas las respuestas.",
  332: "Él puede construir una nueva vida para su hermana.",
  333: "Ella dijo que no puede pasar mucho tiempo con el grupo.",
  334: "Él dijo que puede dejarte sostener el gatito",
  335: "Creo que él puede añadir algunas ideas valiosas.",
  336: "No creo que ella pueda abrir la puerta.",
  337: "¿Crees que él puede seguir jugando?",
  338: "Mal.",
  339: "No, creo que se ha lastimado bastante mal.",
  340: "Sí, estoy seguro de que va a estar bien.",
  341: "Conocí a alguien hace unos días.",
  342: "Conocí a alguien que dijo algo.",
  343: "Que dijo que está preocupada por la economía.",
  344: "Que dijo que está feliz de ayudarte.",
  345: "Que dijo que no está listo para irse todavía.",
  346: "Quería que supiera que me gustaba su libro.",
  347: "Él quería saber qué estaba pasando hace una semana.",
  348: "Ella no quería saber qué iba a pasar.",
  349: "¿Él quería salir el viernes por la noche?",
  350: "Sí, quería ver a unos viejos amigos.",
  351: "No, no quería dejarme solo.",
  352: "Incluso si quisiera no podría.",
  353: "Ella necesitaba correr alrededor del campo.",
  354: "Él no necesitaba parecer enojado.",
  355: "¿Ella necesitaba hablar con esa mujer que conoces?",
  356: "Sí, tenían algo importante que discutir.",
  357: "No, ella solo quería enviarle un mensaje.",
  358: "Tu amigo dijo que no podía alcanzar la cima.",
  359: "Tu amigo dijo que podía girar a la izquierda.",
  360: "¿Tu amigo dijo algo más?",
  361: "Estaba callado.",
  362: "No, estaba bastante callado después de que te fuiste.",
  363: "Sí, tenía ganas de hablar mucho.",
  364: "Escuché que no le gustaba ese lugar.",
  365: "No escuché lo que ella le dijo.",
  366: "¿Escuchaste qué quería cultivar?",
  367: "No, nadie me dijo.",
  368: "Sí, escuché que quería cultivar tomates.",
  369: "Vi varios caballos en la carretera.",
  370: "No vi a nadie que conociera.",
  371: "Fui a ver una película el miércoles.",
  372: "¿Viste lo que ella estaba intentando crear?",
  373: "Era hermoso.",
  374: "Sí, pensé que era muy hermoso.",
  375: "No, no sabía lo que estaba haciendo.",
  376: "No fui a ninguna parte el mes pasado.",
  377: "¿Fuiste a alguna parte del mundo el año pasado?",
  378: "No, no tenía suficiente dinero para vacaciones.",
  379: "Sí, tuve la suerte de viajar a África.",
  380: "Pregunté qué quería incluir.",
  381: "No pregunté si quería seguirnos.",
  382: "¿Preguntaste dónde quería ponerlo?",
  383: "Sí, dijo que quería ponerlo en el jardín.",
  384: "No pude estar de acuerdo con lo que dijo hace un momento.",
  385: "¿Estuviste de acuerdo con ella?",
  386: "Sí, estuve de acuerdo con ella.",
  387: "No, no pensé que tuviera razón.",
  388: "Esa persona con la que trabajas.",
  389: "Esa persona de allí.",
  390: "La que está parada cerca de la entrada.",
  391: "La que está caminando hacia el autobús.",
  392: "Ese niño con el cabello negro frente a la oficina de correos.",
  393: "Ese niño con la camisa verde.",
  394: "Esa niña con el vestido amarillo.",
  395: "Necesitamos girar a la izquierda en la próxima esquina.",
  396: "No necesitamos estar de pie hasta que todos los demás estén listos.",
  397: "¿Necesitamos prepararnos pronto?",
  398: "Queremos ser más pacientes con nuestros hijos.",
  399: "No queremos perder la esperanza.",
  400: "¿Queremos comer algo más tarde?",
  401: "No, sería mejor ir directamente a casa.",
  402: "Sí, sería agradable parar en algún lugar para comer.",
  403: "Deberíamos permanecer callados el mayor tiempo posible.",
  404: "No deberíamos esperar terminar antes del jueves.",
  405: "¿Deberíamos preguntar si tenemos que reservar?",
  406: "No, estoy seguro de que estará bien.",
  407: "¿No deberíamos intentar dar un buen ejemplo?",
  408: "Sí, esa es la mejor manera de hacer una familia feliz.",
  409: "No, no importa lo que hagamos.",
  410: "Todavía pelean entre ellos.",
  411: "Nos gustaría reservar una mesa para cuatro esta noche.",
  412: "No podíamos permitirles ganar todo.",
  413: "Podríamos caernos si vamos demasiado cerca del borde.",
  414: "¿Podríamos tener una botella de vino tinto por favor?",
  415: "Eso no sería un problema si me preguntas.",
  416: "Quieren liderar el camino el año que viene.",
  417: "¿Quieren matar esas hormigas?",
  418: "Necesitan servir a la comunidad.",
  419: "Si quieren que la gente los quiera.",
  420: "No necesitan preguntar cuántos años tiene.",
  421: "Porque ya saben que se está debilitando.",
  422: "Una pregunta.",
  423: "¿Necesitan hacer una pregunta tan obvia?",
  424: "No, están perdiendo el tiempo de todos.",
  425: "Sí, necesitan asegurarse de que entienden.",
  426: "Les gustaría amarse pero son infelices.",
  427: "No les gustaría que pensaras que están aburridos.",
  428: "¿Les gustaría visitarnos el martes?",
  429: "Sí, eso sería perfecto para ellos.",
  430: "No, eso no sería posible.",
  431: "Todavía no están listos pero estarán listos pronto.",
  432: "Podrían significar que quieren que preguntes.",
  433: "No pudieron averiguar cuándo empezaba la película.",
  434: "¿Podrían reducir el número de estudiantes que aceptan?",
  435: "Sí, podrían si quisieran.",
  436: "No, hay un número mínimo que necesitan.",
  437: "Querían recaudar tanto como fuera posible para caridad.",
  438: "No querían decidir qué debería hacer.",
  439: "No quieren morir.",
  440: "Quieren viajar mientras todavía son jóvenes.",
  441: "Un enfoque.",
  442: "¿Querían desarrollar un nuevo enfoque?",
  443: "No, querían seguir haciéndolo de la misma manera.",
  444: "Sí, pensaron que podría hacerse más eficientemente.",
  445: "Podrán llevar esa maleta.",
  446: "No podrán romper esa ventana.",
  447: "¿Podrán llevarnos a casa después de la comida?",
  448: "Sí, estarán felices de ayudar.",
  449: "Dijeron que estaban casi listos.",
  450: "No, tienen que tomar el tren ellos mismos.",
  451: "Dijeron lo que querían hacer.",
  452: "No dijeron lo que querían hacer.",
  453: "¿Dijeron a quién vieron anoche?",
  454: "Nuestros amigos vinieron alrededor de las seis.",
  455: "Tuvimos que irnos porque los niños estaban cansados.",
  456: "Él podría estar allí pero no es muy probable.",
  457: "Parte del problema es el número de diferentes áreas.",
  458: "Todo era mucho más fácil en el pasado.",
  459: "No estaba delante del letrero azul.",
  460: "Quiero encontrar una tienda cerca del hotel.",
  461: "Una tienda donde pueda comprar algunas postales.",
  462: "Mi abuelo luchó en Italia durante la guerra.",
  463: "Mi número de habitación.",
  464: "Le dije mi número de habitación una vez pero lo olvidó.",
  465: "La próxima vez le preguntaré cuál es su nombre.",
  466: "Déjame lanzarlo sobre la pared.",
  467: "Está al lado del estacionamiento.",
  468: "Es un mundo grande.",
  469: "Pero eso no significa que no podamos cambiarlo.",
  470: "¿Qué tan alto quieres escalar antes de que paremos?",
  471: "¿Quieres parar para descansar?",
  472: "Parte del problema es que no conocemos los hechos.",
  473: "No lo quiero.",
  474: "Ni siquiera lo quiero como oferta gratis.",
  475: "Hay muchas razones para considerar esperar.",
  476: "Estoy esperando el final de la segunda mitad.",
  477: "Él ha estado enfermo desde el segundo día de las vacaciones.",
  478: "Ella tiene un corazón tan amable.",
  479: "Es lo menos que podría hacer.",
  480: "Diga lo que diga no está lejos ahora.",
  481: "Es la única esperanza real que nos queda.",
  482: "La única esperanza real es que no van en serio.",
  483: "La vida no es fácil pero no se supone que sea fácil.",
  484: "Se supone que sea un desafío.",
  485: "Nada me haría más feliz que escapar.",
  486: "Creo que tus ojos son hermosos.",
  487: "Está debajo del puente.",
  488: "Está del otro lado de esa línea amarilla.",
  489: "Si no me haces una taza fuerte de café ahora mismo.",
  490: "Entonces nunca confiaré en nadie nunca más.",
  491: "Me encanta la forma en que intentas ayudar.",
  492: "¿Cuál de esos lugares crees que es el más interesante?",
  493: "¿Qué va a venir después?",
  494: "¿Qué pasa después de la primera parte del espectáculo?",
  495: "Cuando importa.",
  496: "No estoy planeando perder cuando realmente importa.",
  497: "Eso suena como que necesitas dormir un poco.",
  498: "Él está parado solo ahí dentro de la entrada.",
  499: "Tal vez deberíamos abrir la puerta y cerrar la ventana.",
  500: "¿Por qué no quieres sentarte entre las dos niñas?",
  501: "Si tan solo pudiera confiar en que jueguen juntos sin discutir.",
  502: "Ella casi se perdió porque giró a la izquierda en vez de a la derecha.",
  503: "Odio causar problemas pero ese es mío.",
  504: "Voy a correr a través del césped.",
  505: "Para que no me dejen atrás.",
  506: "Solía vivir por aquí hace años antes de que nos mudáramos.",
  507: "Nos mudamos a la ciudad.",
  508: "No tiene sentido preocuparse por cómo vas a pagar.",
  509: "Escuché que vas a pagar por una cama nueva.",
  510: "Ella ha ido a buscar un lugar seguro para estacionar el coche.",
  511: "Las noticias tardaron varias horas en llegar a todos en la oficina.",
  512: "¿Puedes mantener la puerta abierta mientras busco las llaves?",
  513: "Me duele más cuando muevo la cabeza arriba y abajo.",
  514: "Encontré la casa perfecta el primer día.",
  515: "El primer día del año nuevo.",
  516: "Ambos vinieron solos.",
  517: "Pero se fueron juntos.",
  518: "No podía imaginarme teniendo exactamente el mismo problema.",
  519: "Todavía no he visto a su nuevo bebé.",
  520: "Le podría haber pasado a toda la familia.",
  521: "Me temo que olvidarás por qué necesitábamos quedarnos aquí.",
  522: "Acordemos que fue estúpido decir la verdad.",
  523: "En lugar de dar una excusa.",
  524: "Te llamaré de vuelta en tres o cuatro minutos.",
  525: "Para verificar si has podido terminar.",
  526: "Me cuesta creer que no puedas adivinar.",
  527: "Adivina quién me contó esa historia divertida.",
  528: "Probablemente se supone que debo guardar esas cosas en otra habitación.",
  529: "¿Pueden todos levantar las manos?",
  530: "Para que pueda contarlas",
  531: "No es verdad que cualquiera pueda ganar el juego.",
  532: "A menos que tengan suerte.",
  533: "Ella no escuchará cada palabra que digas.",
  534: "No salgamos en este clima horrible.",
  535: "Él hizo una promesa de que no elegiría el trabajo equivocado.",
  536: "Solía pensar que estar loco era malo.",
  537: "Pero me equivoqué.",
  538: "No quiero parecer como si no me importara.",
  539: "Pero se está haciendo tarde.",
  540: "No me importa si quieres irte sin el coche.",
  541: "Es una buena idea intentar respirar lentamente.",
  542: "Cada vez que te sientas enojado.",
  543: "Ella tenía razón.",
  544: "Quien dijo que sería difícil tenía toda la razón.",
  545: "Es tu turno de llevar la ropa limpia arriba.",
  546: "El perro está sucio y mojado.",
  547: "Porque ha estado jugando en el barro.",
  548: "Me siento triste en este momento.",
  549: "Porque tengo que estar callado.",
  550: "El final del pueblo.",
  551: "La iglesia es fea.",
  552: "La iglesia al otro extremo del pueblo es fea.",
  553: "Creo que la iglesia pequeña es muy fea.",
  554: "Esta toalla no está seca.",
  555: "Y estoy demasiado cansado para buscar una nueva.",
  556: "Ponen música tarde en la noche.",
  557: "Desearía que no pusieran música tan fuerte.",
  558: "Es tan tarde en la noche.",
  559: "¿Has encontrado el camino a través del bosque?",
  560: "Baja hasta la playa",
  561: "No me importa si es un coche rápido.",
  562: "Solo quiero llegar allí de forma segura.",
  563: "No habría podido seguir más tiempo.",
  564: "No habría podido sin tu ayuda.",
  565: "Lo habría pensado más cuidadosamente.",
  566: "Habría pensado más si hubiera sido mi elección.",
  567: "Ha sido encantador pasar tiempo al aire libre viendo jugar a los niños.",
  568: "Espero ver una mejora la próxima vez que nos veamos.",
  569: "¿Has decidido cuánto estás dispuesto a pagar?",
  570: "¿Cuánto estás dispuesto a pagar por tu boleto?",
  571: "No estoy convencido de que esa sería una muy buena idea.",
  572: "¿Has olvidado lo que pasó la última vez que nos visitaron?",
  573: "Es el tipo de cosa que hace que las vacaciones sean muy especiales.",
  574: "Las vacaciones son muy especiales para todos.",
  575: "Ha sido perturbador.",
  576: "Ha sido muy perturbador esperar.",
  577: "Hemos estado esperando las noticias del hospital.",
  578: "Algún lugar más cálido.",
  579: "A menudo lo hemos intentado.",
  580: "A menudo hemos querido llevar a los niños a algún lugar un poco más cálido.",
  581: "A él le gustaría saber un poco más sobre cómo es.",
  582: "¿Cómo es crecer aquí?",
  583: "¿Cómo es en esta parte del mundo?",
  584: "¿Cómo es despertar cada mañana y ver las montañas?",
  585: "Puedo ver las montañas desde la ventana de mi dormitorio.",
  586: "Quiero veinte huevos cocidos.",
  587: "Ella solía insistir en que comiéramos huevos para cenar.",
  588: "Así que quería crecer e irme de casa.",
  589: "Me dijo que acababa de ver el último autobús.",
  590: "Vi el último autobús saliendo de la estación.",
  591: "Me siguió hasta las tiendas.",
  592: "Y por la carretera principal.",
  593: "Por mucho que argumenté todavía tuve que compartir.",
  594: "Tuve que compartir mis juguetes con mi hermana.",
  595: "Necesito acostarme en el jardín.",
  596: "Y necesito cerrar los ojos por un rato.",
  597: "Sospecho que él ha escuchado cien historias sobre ello.",
  598: "Él ha escuchado mil historias sobre lo que estaban haciendo.",
  599: "Habría estado feliz de conducir si me lo hubieras dicho.",
  600: "Habría conducido si me hubieras dicho lo cansado que estabas.",
  601: "Estábamos hablando de cómo empezó todo.",
  602: "Cómo empezó en primer lugar.",
  603: "No teníamos dónde vivir en ese momento.",
  604: "Ella se ofreció a dejarnos quedarnos con ella.",
  605: "Porque necesitábamos ayuda.",
  606: "Si hubiera sabido entonces lo que sé ahora habría esperado.",
  607: "Si lo hubiera sabido habría hecho las cosas diferente.",
  608: "Habría sido lo sensato de hacer.",
  609: "Lo sensato habría sido preguntar.",
  610: "Él necesita buscar trabajo.",
  611: "Habría estado listo para buscar en otro lugar.",
  612: "Habríamos comprado algo.",
  613: "Probablemente habríamos comprado una casa allí.",
  614: "Está cerca de donde vive tu familia.",
  615: "Pensé que fuiste muy valiente al decir eso.",
  616: "Fuiste muy valiente al decir que pensabas eso.",
  617: "Pensaste que era un error.",
  618: "No se siente como mucho tiempo.",
  619: "Hace mucho tiempo que no nos vemos.",
  620: "Hace mucho tiempo desde la última vez que nos vimos.",
  621: "No me habría atrevido a decirle que estaba roto.",
  622: "Sabía que los niños lo habían roto.",
  623: "¿Quieres una taza de café o té?",
  624: "Sí, eso sería genial, por favor.",
  625: "¿Quieres algo de beber?",
  626: "No, no tengo sed, gracias.",
  627: "Tu café está listo.",
  628: "¿Te gusta el té?",
  629: "Me gusta con leche pero sin azúcar.",
  630: "¿Puedo tomar algo de beber por favor?",
  631: "¿Qué te gustaría?",
  632: "Un vaso de agua.",
  633: "Un vaso grande de agua estaría bien.",
  634: "Me gustaría uno de esos.",
  635: "Ese es el bolso de Jane.",
  636: "Creo que ese es el bolso de Jane.",
  637: "¿Dónde está su bolso?",
  638: "Estoy intentando pensar.",
  639: "con usted señor",
  640: "Es el rojo.",
  641: "Creo que es el rojo en esa silla.",
  642: "¿cómo se siente señora?",
  643: "¿Quiere usted señor",
  644: "¿Podría decir eso señor?",
  645: "Puedo ayudarle señora",
  646: "Está haciendo algo señor.",
  647: "Usted lo habla señora",
  648: "lo que dijo señora",
  649: "¿Está listo señor?",
  650: "¿Quiere irse señora?",
  651: "¿Qué piensa señora?",
  652: "¿Qué necesita señor?",
  653: "¿Le importa señora?",
  654: "No estoy seguro de que pueda ayudarle, señor.",
  655: "Creo que lo está haciendo muy bien, señora.",
  656: "con ustedes",
  657: "¿cómo se sienten ustedes?",
  658: "¿Quieren ustedes?",
  659: "¿Podrían decir eso ustedes",
  660: "Puedo ayudarles",
  661: "están todos haciendo algo",
  662: "todos lo hablan",
  663: "lo que dijeron todos",
  664: "¿Están todos listos?",
  665: "¿Quieren irse todos?",
  666: "¿Qué piensan todos?",
  667: "¿Les importa a todos?",
  668: "Espero que todos puedan ir"
};

function generateUUID(content) {
  return crypto.createHash('md5').update(JSON.stringify(content)).digest('hex');
}

function createTranslationAminoAcid(seedId, sourceEnglish, targetSpanish) {
  const content = {
    seed_id: `C${String(seedId).padStart(4, '0')}`,
    source: sourceEnglish,
    target: targetSpanish,
    metadata: {
      course_code: 'spa_for_eng_668seeds',
      phase: 'phase_1',
      heuristics_applied: ['naturalness', 'frequency', 'clarity', 'brevity', 'consistency', 'utility'],
      created_at: new Date().toISOString()
    }
  };

  const uuid = generateUUID(content);

  return {
    uuid,
    type: 'translation',
    ...content,
    lego_extraction_attempts: [],
    quality_status: 'pending',
    current_quality_score: null,
    total_attempts: 0,
    flagged_for_review: false,
    human_review_requested: false,
    last_reviewed_at: null
  };
}

async function generateTranslations() {
  console.log('🌍 Starting Spanish translation generation...\n');

  const seedsPath = path.join(__dirname, '../../../canonical-seeds.txt');
  const seedsContent = await fs.readFile(seedsPath, 'utf-8');
  const lines = seedsContent.split('\n');

  const translations = [];
  let processedCount = 0;

  for (const line of lines) {
    const match = line.match(/^(\d+)\t(.+)$/);
    if (!match) continue;

    const seedId = parseInt(match[1]);
    const sourceEnglish = match[2];

    // Replace {target} placeholder with Spanish
    const sourceText = sourceEnglish.replace(/\{target\}/g, 'Spanish');
    const targetSpanish = TRANSLATIONS[seedId]?.replace(/\{target\}/g, 'español') || sourceText;

    const aminoAcid = createTranslationAminoAcid(seedId, sourceText, targetSpanish);
    translations.push(aminoAcid);

    // Save individual translation amino acid
    const translationPath = path.join(__dirname, 'amino_acids/translations', `${aminoAcid.uuid}.json`);
    await fs.writeJson(translationPath, aminoAcid, { spaces: 2 });

    processedCount++;
    if (processedCount % 50 === 0) {
      console.log(`✓ Translated ${processedCount}/668 seeds`);
    }
  }

  console.log(`\n✓ All ${processedCount} seeds translated!`);

  // Save master translations file
  const masterPath = path.join(__dirname, 'spa_for_eng_668seeds_translations.json');
  await fs.writeJson(masterPath, translations, { spaces: 2 });

  console.log(`\n📦 Saved to: ${masterPath}`);
  console.log(`📁 Individual amino acids: amino_acids/translations/`);

  return translations;
}

// Run if executed directly
if (require.main === module) {
  generateTranslations().catch(console.error);
}

module.exports = { generateTranslations, SPANISH_RULES };
