-- GENERATED by tools/audio-regen-probe/dump-live-schema.cjs — do not hand-edit.
-- Function bodies and trigger definitions below are pg_get_functiondef /
-- pg_get_triggerdef output from the LIVE database, verbatim.
--
-- Deliberately omitted (bookkeeping only; cannot change which audio row a
-- content slot points at): audit_content_change, touch_course_content_stamp,
-- touch_course_audio_stamp, increment_version, bump_course_version,
-- sync_audio_duration_to_dependents, refuse_component_introduction.

-- dumped_at_utc: 2026-08-18T15:14:11.491Z

-- Table DDL for the isolated fixture. Hand-authored, column names/types taken
-- from information_schema on the live DB (see .a74-scratch/regen-repro/schema-live2.txt).
-- Trimmed to the columns the audio-identity path reads or writes; enum columns
-- (course_legos.type, .status) are plain text here because their enum types are
-- irrelevant to clip identity.
--
-- NOT reproduced: course_audio.text_stripped (a GENERATED column live), the FKs
-- to audio_clips/courses beyond course_code, and every non-unique index.

CREATE TABLE language_canonical (
  raw       text PRIMARY KEY,
  canonical text NOT NULL
);

CREATE TABLE courses (
  course_code text PRIMARY KEY,
  known_lang  text,
  target_lang text,
  seed_count  integer
);

CREATE TABLE course_audio (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  course_code      text NOT NULL REFERENCES courses(course_code) ON DELETE CASCADE,
  text             text NOT NULL,
  text_normalized  text NOT NULL,
  language         text NOT NULL,
  role             text NOT NULL,
  voice_id         text NOT NULL,
  origin           text NOT NULL CHECK (origin = ANY (ARRAY['tts','human'])),
  s3_key           text NOT NULL,
  duration_ms      integer,
  file_size_bytes  integer,
  created_at       timestamptz NOT NULL DEFAULT now(),
  lego_id          text,
  word_boundaries  jsonb,
  sequence         integer,
  audio_revision   integer NOT NULL DEFAULT 1,
  clip_id          uuid,
  rerecord_wanted  jsonb
);

CREATE TABLE course_legos (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  course_code           text NOT NULL,
  seed_number           integer NOT NULL,
  lego_index            integer NOT NULL,
  lego_id               text,
  type                  text NOT NULL DEFAULT 'word',
  is_new                boolean NOT NULL DEFAULT true,
  known_text            text,
  target_text           text NOT NULL,
  components            jsonb,
  status                text NOT NULL DEFAULT 'draft',
  version               integer NOT NULL DEFAULT 1,
  updated_at            timestamptz NOT NULL DEFAULT now(),
  created_at            timestamptz NOT NULL DEFAULT now(),
  known_audio_id        uuid,
  target1_audio_id      uuid,
  target2_audio_id      uuid,
  presentation_audio_id text,
  target1_duration_ms   integer,
  target2_duration_ms   integer
);

CREATE TABLE course_practice_phrases (
  id                    text PRIMARY KEY,
  course_code           text NOT NULL,
  seed_number           integer NOT NULL,
  lego_index            integer NOT NULL,
  position              integer NOT NULL,
  known_text            text,
  target_text           text NOT NULL,
  word_count            integer NOT NULL DEFAULT 0,
  lego_count            integer NOT NULL DEFAULT 0,
  metadata              jsonb NOT NULL DEFAULT '{}'::jsonb,
  status                text NOT NULL DEFAULT 'draft',
  version               integer NOT NULL DEFAULT 1,
  updated_at            timestamptz NOT NULL DEFAULT now(),
  created_at            timestamptz NOT NULL DEFAULT now(),
  phrase_role           text NOT NULL DEFAULT 'practice',
  known_audio_id        uuid,
  target1_audio_id      uuid,
  target2_audio_id      uuid,
  target1_duration_ms   integer,
  target2_duration_ms   integer,
  lego_id               text,
  presentation_audio_id uuid,
  introduce             boolean NOT NULL DEFAULT true
);

CREATE TABLE course_seeds (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  course_code      text NOT NULL,
  seed_number      integer NOT NULL,
  known_text       text,
  target_text      text NOT NULL,
  status           text NOT NULL DEFAULT 'released',
  version          integer NOT NULL DEFAULT 1,
  known_audio_id   uuid,
  target1_audio_id uuid,
  target2_audio_id uuid
);

CREATE TABLE content_audio_link_drops (
  id            bigserial PRIMARY KEY,
  dropped_at    timestamptz NOT NULL DEFAULT now(),
  table_name    text NOT NULL,
  row_id        text NOT NULL,
  course_code   text NOT NULL,
  seed_number   integer,
  column_name   text NOT NULL,
  role          text NOT NULL,
  old_audio_id  uuid,
  new_audio_id  uuid,
  old_text      text,
  new_text      text,
  old_voice_id  text,
  reason        text NOT NULL,
  old_link_raw  text
);

-- language_canonical rows copied from live (only the codes the tests use)
INSERT INTO language_canonical (raw, canonical) VALUES ('cy', 'cym');
INSERT INTO language_canonical (raw, canonical) VALUES ('cym', 'cym');
INSERT INTO language_canonical (raw, canonical) VALUES ('de', 'deu');
INSERT INTO language_canonical (raw, canonical) VALUES ('deu', 'deu');
INSERT INTO language_canonical (raw, canonical) VALUES ('en', 'eng');
INSERT INTO language_canonical (raw, canonical) VALUES ('eng', 'eng');
INSERT INTO language_canonical (raw, canonical) VALUES ('es', 'spa');
INSERT INTO language_canonical (raw, canonical) VALUES ('fr', 'fra');
INSERT INTO language_canonical (raw, canonical) VALUES ('fra', 'fra');
INSERT INTO language_canonical (raw, canonical) VALUES ('spa', 'spa');

-- ===== normalize_text =====
CREATE OR REPLACE FUNCTION public.normalize_text(input_text text)
 RETURNS text
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
BEGIN
  RETURN rtrim(lower(trim(input_text)), '.?!¿¡。？！');
END;
$function$;

-- ===== canonical_language =====
CREATE OR REPLACE FUNCTION public.canonical_language(code text)
 RETURNS text
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE primary_subtag text; hit text;
BEGIN
  code := lower(btrim(coalesce(code, '')));
  IF code IN ('', 'auto', 'unknown', 'multi', 'und') THEN
    RAISE EXCEPTION 'clip identity: language % is a placeholder, not a language — resolve it from the course code and role', coalesce(code,'<null>')
      USING ERRCODE = 'check_violation';
  END IF;
  primary_subtag := split_part(regexp_replace(code, '_', '-', 'g'), '-', 1);
  SELECT canonical INTO hit FROM language_canonical WHERE raw = primary_subtag;
  IF hit IS NULL THEN
    RAISE EXCEPTION 'clip identity: language % is not in language_canonical — regenerate it with tools/generate-language-canonical-sql.cjs', code
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN hit;
END $function$;

-- ===== canonical_voice_id =====
CREATE OR REPLACE FUNCTION public.canonical_voice_id(v text)
 RETURNS text
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
DECLARE part text; out_parts text[] := '{}';
BEGIN
  v := btrim(coalesce(v, ''));
  IF v = '' OR lower(v) IN ('legacy_import','legacy','human','human_recording','unknown','default','auto') THEN
    RAISE EXCEPTION 'clip identity: voice_id % is a placeholder, not a voice', coalesce(v,'<null>')
      USING ERRCODE = 'check_violation';
  END IF;
  IF v ~* '^comp:' THEN
    FOREACH part IN ARRAY string_to_array(substr(v, 6), '+') LOOP
      IF btrim(part) <> '' THEN
        out_parts := out_parts || canonical_voice_id(btrim(part));
      END IF;
    END LOOP;
    IF array_length(out_parts, 1) IS NULL THEN
      RAISE EXCEPTION 'clip identity: composite voice_id % has no parts', v USING ERRCODE = 'check_violation';
    END IF;
    RETURN 'comp:' || array_to_string(out_parts, '+');
  END IF;
  IF v ~ '^(azure|xai|elevenlabs|google|narakeet|human)_.' THEN RETURN v; END IF;
  IF v ~ '^[a-z]{2,3}-[A-Za-z]{2,4}-[A-Za-z]+Neural$' THEN RETURN 'azure_' || v; END IF;
  IF lower(v) IN ('eve','leo','ara','sal','rex','gfzdpspr5fdp','bedd6226') THEN RETURN 'xai_' || v; END IF;
  RAISE EXCEPTION 'clip identity: voice_id % has no provider prefix and no inferable provider — the writer must supply one', v
    USING ERRCODE = 'check_violation';
END $function$;

-- ===== audio_canon_voice =====
CREATE OR REPLACE FUNCTION public.audio_canon_voice(v text)
 RETURNS text
 LANGUAGE plpgsql
 STABLE
AS $function$
BEGIN
  RETURN canonical_voice_id(v);
EXCEPTION WHEN check_violation THEN
  -- Legacy placeholder ('legacy_import', 'human', …) or an id with no inferable
  -- provider — canonical_voice_id raises check_violation for exactly those.
  -- Keep it verbatim as its own identity rather than guessing.
  --
  -- ONLY check_violation is caught. A WHEN OTHERS here swallowed a transient
  -- error during the first backfill attempt and returned the raw value for a
  -- code that maps perfectly well, so the same input produced two different
  -- keys in one query. A canonicalisation function that is not deterministic
  -- is worse than none.
  RETURN lower(btrim(coalesce(v, '')));
END
$function$;

-- ===== audio_id_for_text =====
CREATE OR REPLACE FUNCTION public.audio_id_for_text(p_course text, p_text text, p_role text)
 RETURNS uuid
 LANGUAGE sql
 STABLE
AS $function$
  SELECT a.id FROM course_audio a
   WHERE a.course_code = p_course
     AND a.role = p_role
     AND a.s3_key IS NOT NULL
     AND a.text_normalized = normalize_text(p_text)
   ORDER BY (a.origin = 'human') DESC, a.created_at DESC, a.id::text DESC
   LIMIT 1;
$function$;

-- ===== audio_id_for_text_same_voice =====
CREATE OR REPLACE FUNCTION public.audio_id_for_text_same_voice(p_course text, p_text text, p_role text, p_like uuid)
 RETURNS uuid
 LANGUAGE sql
 STABLE
AS $function$
  SELECT a.id
    FROM course_audio a
    JOIN course_audio prev ON prev.id = p_like
   WHERE a.course_code = p_course
     AND a.role        = p_role
     AND a.s3_key IS NOT NULL
     AND (a.text_normalized = normalize_text(p_text)
          OR normalize_text(a.text) = normalize_text(p_text))
     AND audio_canon_voice(a.voice_id) = audio_canon_voice(prev.voice_id)
     AND a.language IS NOT DISTINCT FROM prev.language
   ORDER BY (a.origin = 'human') DESC, a.created_at DESC, a.id::text DESC
   LIMIT 1;
$function$;

-- ===== audio_normalize_text =====
CREATE OR REPLACE FUNCTION public.audio_normalize_text()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.text_normalized := normalize_text(NEW.text);
  RETURN NEW;
END;
$function$;

-- ===== course_audio_canonical_identity =====
CREATE OR REPLACE FUNCTION public.course_audio_canonical_identity()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF TG_OP = 'INSERT' OR NEW.language IS DISTINCT FROM OLD.language THEN
    NEW.language := canonical_language(NEW.language);
  END IF;
  IF TG_OP = 'INSERT' OR NEW.voice_id IS DISTINCT FROM OLD.voice_id THEN
    NEW.voice_id := canonical_voice_id(NEW.voice_id);
  END IF;
  RETURN NEW;
END $function$;

-- ===== link_audio_to_content =====
CREATE OR REPLACE FUNCTION public.link_audio_to_content()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.role = 'known' THEN
    UPDATE course_legos SET known_audio_id = NEW.id
      WHERE course_code = NEW.course_code AND known_audio_id IS NULL
        AND normalize_text(known_text) = NEW.text_normalized;
    UPDATE course_practice_phrases SET known_audio_id = NEW.id
      WHERE course_code = NEW.course_code AND known_audio_id IS NULL
        AND normalize_text(known_text) = NEW.text_normalized;
    UPDATE course_seeds SET known_audio_id = NEW.id
      WHERE course_code = NEW.course_code AND known_audio_id IS NULL
        AND normalize_text(known_text) = NEW.text_normalized;

  ELSIF NEW.role = 'target1' THEN
    UPDATE course_legos
      SET target1_audio_id = NEW.id, target1_duration_ms = NEW.duration_ms
      WHERE course_code = NEW.course_code AND target1_audio_id IS NULL
        AND normalize_text(target_text) = NEW.text_normalized;
    UPDATE course_practice_phrases
      SET target1_audio_id = NEW.id, target1_duration_ms = NEW.duration_ms
      WHERE course_code = NEW.course_code AND target1_audio_id IS NULL
        AND normalize_text(target_text) = NEW.text_normalized;
    UPDATE course_seeds SET target1_audio_id = NEW.id
      WHERE course_code = NEW.course_code AND target1_audio_id IS NULL
        AND normalize_text(target_text) = NEW.text_normalized;

  ELSIF NEW.role = 'target2' THEN
    UPDATE course_legos
      SET target2_audio_id = NEW.id, target2_duration_ms = NEW.duration_ms
      WHERE course_code = NEW.course_code AND target2_audio_id IS NULL
        AND normalize_text(target_text) = NEW.text_normalized;
    UPDATE course_practice_phrases
      SET target2_audio_id = NEW.id, target2_duration_ms = NEW.duration_ms
      WHERE course_code = NEW.course_code AND target2_audio_id IS NULL
        AND normalize_text(target_text) = NEW.text_normalized;
    UPDATE course_seeds SET target2_audio_id = NEW.id
      WHERE course_code = NEW.course_code AND target2_audio_id IS NULL
        AND normalize_text(target_text) = NEW.text_normalized;

  ELSIF NEW.role = 'presentation' THEN
    -- course_legos.presentation_audio_id is a TEXT column (see note 4 below),
    -- hence the cast; course_practice_phrases' is uuid.
    UPDATE course_legos SET presentation_audio_id = NEW.id::text
      WHERE course_code = NEW.course_code AND presentation_audio_id IS NULL
        AND normalize_text(target_text) = NEW.text_normalized;
    UPDATE course_practice_phrases SET presentation_audio_id = NEW.id
      WHERE course_code = NEW.course_code AND presentation_audio_id IS NULL
        AND normalize_text(target_text) = NEW.text_normalized;
  END IF;

  RETURN NEW;
END;
$function$;

-- ===== null_lego_audio_on_text_change =====
CREATE OR REPLACE FUNCTION public.null_lego_audio_on_text_change()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_prev            course_audio%ROWTYPE;
  v_found           boolean;
  v_sub             uuid;
  v_new_text        text;
  v_cur             uuid;
  v_raw             text;
  v_col             text;
  v_role            text;
  v_roles           text[] := ARRAY['known','target1','target2','presentation'];
  v_reason          text;
  v_known_changed   boolean;
  v_target_changed  boolean;
BEGIN
  -- Did the words actually change, or only the punctuation and whitespace?
  -- IS DISTINCT FROM, not =, because course_legos.known_text is NULLABLE (521
  -- rows are NULL today) and normalize_text(NULL) is NULL.
  v_known_changed  := normalize_text(NEW.known_text)  IS DISTINCT FROM normalize_text(OLD.known_text);
  v_target_changed := normalize_text(NEW.target_text) IS DISTINCT FROM normalize_text(OLD.target_text);

  FOREACH v_role IN ARRAY v_roles LOOP
    v_raw := NULL;
    v_cur := NULL;

    IF v_role = 'known' THEN
      CONTINUE WHEN NEW.known_text IS NOT DISTINCT FROM OLD.known_text;
      v_col := 'known_audio_id'; v_new_text := NEW.known_text; v_cur := OLD.known_audio_id;
      -- The writer set this link EXPLICITLY in the same UPDATE as the text.
      -- Respect it: they know something we do not. Without this the function
      -- reads OLD, resolves a substitute from OLD's voice, and overwrites the
      -- value the writer just supplied — so `SET known_text=…, known_audio_id=NULL`
      -- silently RESURRECTS a link the writer deliberately cleared. That is the
      -- exact shape of an audio-first text repair (render the new clip, then
      -- swap text and link together), so it is not hypothetical.
      CONTINUE WHEN NEW.known_audio_id IS DISTINCT FROM OLD.known_audio_id;

    ELSIF v_role = 'presentation' THEN
      -- Invalidation scope preserved verbatim from 20260806: a presentation clip
      -- can embed BOTH sides, so either side moving puts it in question.
      CONTINUE WHEN NEW.known_text  IS NOT DISTINCT FROM OLD.known_text
                AND NEW.target_text IS NOT DISTINCT FROM OLD.target_text;
      v_col := 'presentation_audio_id'; v_new_text := NEW.target_text;
      v_raw := OLD.presentation_audio_id;
      -- Writer-set link in the same UPDATE: respect it (see the known branch).
      CONTINUE WHEN NEW.presentation_audio_id IS DISTINCT FROM OLD.presentation_audio_id;
      CONTINUE WHEN v_raw IS NULL;

      -- The cosmetic-keep rule, expressed against the ROW's text rather than the
      -- clip's. It has to be: a presentation clip speaks a composed introduction
      -- that quotes the lego, never the lego's own text (0 of 72,062 match), so
      -- the clip-text test below can never be the thing that saves it. Without
      -- this, a trailing-space edit destroys a good presentation clip forever —
      -- which is what happens today.
      CONTINUE WHEN NOT v_known_changed AND NOT v_target_changed;

      -- text column, no FK: a value that is not uuid-shaped must be recorded and
      -- dropped, never allowed to raise. Raising would block the edit.
      IF v_raw ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN
        v_cur := v_raw::uuid;
      ELSE
        NEW.presentation_audio_id := NULL;
        INSERT INTO content_audio_link_drops (
          table_name, row_id, course_code, seed_number, column_name, role,
          old_audio_id, new_audio_id, old_text, new_text, old_voice_id,
          old_link_raw, reason
        ) VALUES (
          'course_legos', NEW.id, NEW.course_code, NEW.seed_number, v_col, v_role,
          NULL, NULL, NULL, v_new_text, NULL, v_raw, 'nulled-unparseable-link'
        );
        CONTINUE;
      END IF;

    ELSE
      CONTINUE WHEN NEW.target_text IS NOT DISTINCT FROM OLD.target_text;
      v_col := v_role || '_audio_id'; v_new_text := NEW.target_text;
      v_cur := CASE v_role WHEN 'target1' THEN OLD.target1_audio_id
                           ELSE OLD.target2_audio_id END;
      -- Writer-set link in the same UPDATE: respect it (see the known branch).
      CONTINUE WHEN CASE v_role WHEN 'target1' THEN NEW.target1_audio_id
                                ELSE NEW.target2_audio_id END
                    IS DISTINCT FROM v_cur;
    END IF;

    -- Nothing linked: nothing can be stale. link_audio_to_content (AFTER INSERT
    -- ON course_audio) already fills NULL known/target slots when matching audio
    -- lands. (It cannot fill a presentation slot — see the header, finding 3.)
    CONTINUE WHEN v_cur IS NULL;

    -- v_prev is reused across loop iterations, so it MUST be cleared: a SELECT
    -- INTO that finds nothing leaves the previous iteration's row in place, and
    -- the report row would then name another role's clip.
    v_prev := NULL;
    SELECT * INTO v_prev FROM course_audio WHERE id = v_cur;
    v_found := FOUND;

    -- The clip still speaks the new text (whitespace / casing / trailing
    -- punctuation only): keep it. normalize_text(v_prev.text) — the clip's REAL
    -- text re-normalised now — is tested as well as the stored text_normalized,
    -- because tens of thousands of course_audio rows hold a stored value the
    -- current normaliser would not produce. Testing the stored column alone would
    -- call a clip that speaks the exact right words "stale" and drop a good link.
    CONTINUE WHEN v_found AND (v_prev.text_normalized = normalize_text(v_new_text)
                            OR normalize_text(v_prev.text) = normalize_text(v_new_text));

    IF v_found AND v_role = 'presentation' THEN
      -- Rule 2 is DELIBERATELY SKIPPED for presentation, on a measurement rather
      -- than a preference. A presentation clip never speaks a bare lego
      -- target_text — 0 of 72,062 estate-wide — so this lookup provably cannot
      -- return a row. And it is not free: audio_id_for_text_same_voice costs
      -- 263ms warm and up to 4.6s cold on a large course, because the
      -- `OR normalize_text(a.text) = …` disjunct defeats the index. Paying that
      -- on every genuinely-edited lego that has a presentation link, for a result
      -- that is always NULL, is a straight tax on every content pass.
      -- An earlier draft called it "one lookup" and kept it for uniformity; the
      -- measurement is the better argument. If a future generator ever mints
      -- presentation clips whose text IS the target text, delete this branch and
      -- uniformity returns with it.
      v_sub := NULL;
    ELSIF v_found THEN
      v_sub := audio_id_for_text_same_voice(NEW.course_code, v_new_text, v_role, v_cur);
    ELSE
      -- The link points at a course_audio row that no longer exists: there is no
      -- voice to preserve, so there is no substitute we are willing to pick.
      v_sub := NULL;
    END IF;

    IF v_sub IS NOT NULL AND v_sub <> v_cur THEN
      v_reason := 'relinked-same-voice';
    ELSIF v_sub IS NOT NULL THEN
      CONTINUE;  -- resolved back to the same clip; nothing happened
    ELSIF NOT v_found THEN
      v_reason := 'nulled-dangling-link';
    ELSIF v_role = 'presentation' THEN
      -- Distinct from the reason below on purpose: we did not look for a
      -- same-voice substitute and fail to find one, we declined to look. A
      -- reader counting 'nulled-no-same-voice-clip-for-new-text' rows should not
      -- have presentation drops silently folded into that number.
      v_reason := 'nulled-presentation-not-text-addressable';
    ELSE
      v_reason := 'nulled-no-same-voice-clip-for-new-text';
    END IF;

    IF v_col = 'known_audio_id'          THEN NEW.known_audio_id        := v_sub;
    ELSIF v_col = 'target1_audio_id'     THEN NEW.target1_audio_id      := v_sub;
    ELSIF v_col = 'target2_audio_id'     THEN NEW.target2_audio_id      := v_sub;
    ELSE                                      NEW.presentation_audio_id := v_sub::text;
    END IF;

    INSERT INTO content_audio_link_drops (
      table_name, row_id, course_code, seed_number, column_name, role,
      old_audio_id, new_audio_id, old_text, new_text, old_voice_id, reason
    ) VALUES (
      'course_legos', NEW.id, NEW.course_code, NEW.seed_number, v_col, v_role,
      v_cur, v_sub, v_prev.text, v_new_text, v_prev.voice_id, v_reason
    );
  END LOOP;

  RETURN NEW;
END;
$function$;

-- ===== null_phrase_audio_on_text_change =====
CREATE OR REPLACE FUNCTION public.null_phrase_audio_on_text_change()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_prev      course_audio%ROWTYPE;
  v_found     boolean;
  v_sub       uuid;
  v_new_text  text;
  v_cur       uuid;
  v_col       text;
  v_role      text;
  v_roles     text[] := ARRAY['known','target1','target2'];
  v_reason    text;
BEGIN
  FOREACH v_role IN ARRAY v_roles LOOP
    IF v_role = 'known' THEN
      CONTINUE WHEN NEW.known_text IS NOT DISTINCT FROM OLD.known_text;
      v_col := 'known_audio_id'; v_new_text := NEW.known_text; v_cur := OLD.known_audio_id;
    ELSE
      CONTINUE WHEN NEW.target_text IS NOT DISTINCT FROM OLD.target_text;
      v_col := v_role || '_audio_id'; v_new_text := NEW.target_text;
      v_cur := CASE v_role WHEN 'target1' THEN OLD.target1_audio_id
                           ELSE OLD.target2_audio_id END;
    END IF;

    -- Nothing linked: nothing can be stale. link_audio_to_content (AFTER INSERT
    -- ON course_audio) already fills NULL phrase slots when matching audio lands.
    CONTINUE WHEN v_cur IS NULL;

    -- v_prev is reused across loop iterations, so it MUST be cleared: a SELECT
    -- INTO that finds nothing leaves the previous iteration's row in place, and
    -- the report row would then name another role's clip.
    v_prev := NULL;
    SELECT * INTO v_prev FROM course_audio WHERE id = v_cur;
    v_found := FOUND;

    -- The clip still speaks the new text (whitespace / casing / trailing
    -- punctuation only): keep it. normalize_text(v_prev.text) — the clip's REAL
    -- text re-normalised now — is tested as well as the stored text_normalized,
    -- because tens of thousands of course_audio rows hold a stored value the
    -- current normaliser would not produce. Testing the stored column alone would
    -- call a clip that speaks the exact right words "stale" and drop a good link.
    CONTINUE WHEN v_found AND (v_prev.text_normalized = normalize_text(v_new_text)
                            OR normalize_text(v_prev.text) = normalize_text(v_new_text));

    IF v_found THEN
      v_sub := audio_id_for_text_same_voice(NEW.course_code, v_new_text, v_role, v_cur);
    ELSE
      -- The link points at a course_audio row that no longer exists: there is no
      -- voice to preserve, so there is no substitute we are willing to pick.
      v_sub := NULL;
    END IF;

    IF v_sub IS NOT NULL AND v_sub <> v_cur THEN
      v_reason := 'relinked-same-voice';
    ELSIF v_sub IS NOT NULL THEN
      CONTINUE;  -- resolved back to the same clip; nothing happened
    ELSIF NOT v_found THEN
      v_reason := 'nulled-dangling-link';
    ELSE
      v_reason := 'nulled-no-same-voice-clip-for-new-text';
    END IF;

    IF v_col = 'known_audio_id'      THEN NEW.known_audio_id   := v_sub;
    ELSIF v_col = 'target1_audio_id' THEN NEW.target1_audio_id := v_sub;
    ELSE                                  NEW.target2_audio_id := v_sub;
    END IF;

    INSERT INTO content_audio_link_drops (
      table_name, row_id, course_code, seed_number, column_name, role,
      old_audio_id, new_audio_id, old_text, new_text, old_voice_id, reason
    ) VALUES (
      'course_practice_phrases', NEW.id, NEW.course_code, NEW.seed_number, v_col, v_role,
      v_cur, v_sub, v_prev.text, v_new_text, v_prev.voice_id, v_reason
    );
  END LOOP;

  RETURN NEW;
END;
$function$;

-- ===== null_seed_audio_on_text_change =====
CREATE OR REPLACE FUNCTION public.null_seed_audio_on_text_change()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_prev      course_audio%ROWTYPE;
  v_found     boolean;
  v_sub       uuid;
  v_new_text  text;
  v_cur       uuid;
  v_col       text;
  v_role      text;
  v_roles     text[] := ARRAY['known','target1','target2'];
  v_reason    text;
BEGIN
  FOREACH v_role IN ARRAY v_roles LOOP
    IF v_role = 'known' THEN
      -- The known side moves only when known_text moves.
      CONTINUE WHEN NEW.known_text IS NOT DISTINCT FROM OLD.known_text;
      v_col := 'known_audio_id'; v_new_text := NEW.known_text; v_cur := OLD.known_audio_id;
    ELSE
      CONTINUE WHEN NEW.target_text IS NOT DISTINCT FROM OLD.target_text;
      v_col := v_role || '_audio_id'; v_new_text := NEW.target_text;
      v_cur := CASE v_role WHEN 'target1' THEN OLD.target1_audio_id
                           ELSE OLD.target2_audio_id END;
    END IF;

    -- Nothing linked: nothing can be stale. Leave it for link_audio_to_content.
    CONTINUE WHEN v_cur IS NULL;

    -- v_prev is reused across loop iterations, so it MUST be cleared before the
    -- lookup: a SELECT INTO that finds nothing leaves the previous iteration's
    -- row in place, and the report row would then name another role's clip.
    v_prev := NULL;
    SELECT * INTO v_prev FROM course_audio WHERE id = v_cur;
    v_found := FOUND;

    -- The clip still speaks the new text (whitespace / casing / trailing
    -- punctuation only): keep it. This is the case the 2026-08-06 migration
    -- existed to stop breaking, and it stays unbroken here.
    --
    -- normalize_text(v_prev.text) — the clip's REAL text, re-normalised now —
    -- not v_prev.text_normalized. On the 41,900 rows whose stored column predates
    -- the normaliser's redefinition the stored value still carries the trailing
    -- '?', so testing it would call a clip that speaks the exact right words
    -- "stale" and drop a good link. The stored column is kept as a fast first
    -- disjunct; it is never the sole authority.
    CONTINUE WHEN v_found AND (v_prev.text_normalized = normalize_text(v_new_text)
                            OR normalize_text(v_prev.text) = normalize_text(v_new_text));

    IF v_found THEN
      v_sub := audio_id_for_text_same_voice(NEW.course_code, v_new_text, v_role, v_cur);
    ELSE
      -- The link points at a course_audio row that no longer exists. There is no
      -- voice to preserve, so there is no substitute we are willing to pick.
      --
      -- All three of course_seeds' audio FKs are ON DELETE SET NULL, so today
      -- this branch is unreachable — the canary confirms it cannot be provoked.
      -- It is kept because that is a property of three constraints that a future
      -- migration could change, and the cost of keeping it is one NULL check.
      v_sub := NULL;
    END IF;

    IF v_sub IS NOT NULL AND v_sub <> v_cur THEN
      v_reason := 'relinked-same-voice';
    ELSIF v_sub IS NOT NULL THEN
      CONTINUE;  -- resolved back to the same clip; nothing happened
    ELSIF NOT v_found THEN
      v_reason := 'nulled-dangling-link';
    ELSE
      v_reason := 'nulled-no-same-voice-clip-for-new-text';
    END IF;

    IF v_col = 'known_audio_id'   THEN NEW.known_audio_id   := v_sub;
    ELSIF v_col = 'target1_audio_id' THEN NEW.target1_audio_id := v_sub;
    ELSE                                 NEW.target2_audio_id := v_sub;
    END IF;

    INSERT INTO content_audio_link_drops (
      table_name, row_id, course_code, seed_number, column_name, role,
      old_audio_id, new_audio_id, old_text, new_text, old_voice_id, reason
    ) VALUES (
      'course_seeds', NEW.id, NEW.course_code, NEW.seed_number, v_col, v_role,
      v_cur, v_sub, v_prev.text, v_new_text, v_prev.voice_id, v_reason
    );
  END LOOP;

  RETURN NEW;
END;
$function$;

-- ===== pull_audio_duration_on_link =====
CREATE OR REPLACE FUNCTION public.pull_audio_duration_on_link()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_duration INTEGER;
BEGIN
  -- target1: fill duration when audio_id is set on INSERT, or relinked on UPDATE.
  IF NEW.target1_audio_id IS NOT NULL
     AND (TG_OP = 'INSERT' OR NEW.target1_audio_id IS DISTINCT FROM OLD.target1_audio_id) THEN
    SELECT duration_ms INTO v_duration
    FROM course_audio
    WHERE id = NEW.target1_audio_id;

    -- Only overwrite if course_audio has a meaningful value. If course_audio
    -- itself doesn't yet have duration_ms (rare), leave the cache as-is so the
    -- upstream trigger can populate it later when course_audio is updated.
    IF v_duration IS NOT NULL AND v_duration > 0 THEN
      NEW.target1_duration_ms := v_duration;
    END IF;
  END IF;

  -- target2: same pattern.
  IF NEW.target2_audio_id IS NOT NULL
     AND (TG_OP = 'INSERT' OR NEW.target2_audio_id IS DISTINCT FROM OLD.target2_audio_id) THEN
    SELECT duration_ms INTO v_duration
    FROM course_audio
    WHERE id = NEW.target2_audio_id;

    IF v_duration IS NOT NULL AND v_duration > 0 THEN
      NEW.target2_duration_ms := v_duration;
    END IF;
  END IF;

  RETURN NEW;
END;
$function$;

-- ===== link_all_audio_ids =====
CREATE OR REPLACE FUNCTION public.link_all_audio_ids(p_course_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
  DECLARE
    v_course RECORD;
    v_linked_legos_known INT := 0;
    v_linked_legos_t1 INT := 0;
    v_linked_legos_t2 INT := 0;
    v_linked_phrases_known INT := 0;
    v_linked_phrases_t1 INT := 0;
    v_linked_phrases_t2 INT := 0;
    v_linked_seeds_known INT := 0;
    v_linked_seeds_t1 INT := 0;
    v_linked_seeds_t2 INT := 0;
  BEGIN
    SELECT * INTO v_course FROM courses WHERE course_code = p_course_code;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'Course not found: %', p_course_code;
    END IF;

    UPDATE course_legos cl SET known_audio_id = (
      SELECT ca.id FROM course_audio ca
      WHERE ca.course_code = cl.course_code
        AND ca.text_normalized = normalize_text(cl.known_text)
        AND ca.role IN ('known', 'source')
      LIMIT 1
    )
    WHERE cl.course_code = p_course_code AND cl.known_audio_id IS NULL
      AND EXISTS (
        SELECT 1 FROM course_audio ca
        WHERE ca.course_code = cl.course_code
          AND ca.text_normalized = normalize_text(cl.known_text)
          AND ca.role IN ('known', 'source')
      );
    GET DIAGNOSTICS v_linked_legos_known = ROW_COUNT;

    UPDATE course_legos cl SET target1_audio_id = (
      SELECT ca.id FROM course_audio ca
      WHERE ca.course_code = cl.course_code
        AND ca.text_normalized = normalize_text(cl.target_text)
        AND ca.role = 'target1'
      LIMIT 1
    )
    WHERE cl.course_code = p_course_code AND cl.target1_audio_id IS NULL
      AND EXISTS (
        SELECT 1 FROM course_audio ca
        WHERE ca.course_code = cl.course_code
          AND ca.text_normalized = normalize_text(cl.target_text)
          AND ca.role = 'target1'
      );
    GET DIAGNOSTICS v_linked_legos_t1 = ROW_COUNT;

    UPDATE course_legos cl SET target2_audio_id = (
      SELECT ca.id FROM course_audio ca
      WHERE ca.course_code = cl.course_code
        AND ca.text_normalized = normalize_text(cl.target_text)
        AND ca.role = 'target2'
      LIMIT 1
    )
    WHERE cl.course_code = p_course_code AND cl.target2_audio_id IS NULL
      AND EXISTS (
        SELECT 1 FROM course_audio ca
        WHERE ca.course_code = cl.course_code
          AND ca.text_normalized = normalize_text(cl.target_text)
          AND ca.role = 'target2'
      );
    GET DIAGNOSTICS v_linked_legos_t2 = ROW_COUNT;

    UPDATE course_practice_phrases cpp SET known_audio_id = (
      SELECT ca.id FROM course_audio ca
      WHERE ca.course_code = cpp.course_code
        AND ca.text_normalized = normalize_text(cpp.known_text)
        AND ca.role IN ('known', 'source')
      LIMIT 1
    )
    WHERE cpp.course_code = p_course_code AND cpp.known_audio_id IS NULL
      AND EXISTS (
        SELECT 1 FROM course_audio ca
        WHERE ca.course_code = cpp.course_code
          AND ca.text_normalized = normalize_text(cpp.known_text)
          AND ca.role IN ('known', 'source')
      );
    GET DIAGNOSTICS v_linked_phrases_known = ROW_COUNT;

    UPDATE course_practice_phrases cpp SET target1_audio_id = (
      SELECT ca.id FROM course_audio ca
      WHERE ca.course_code = cpp.course_code
        AND ca.text_normalized = normalize_text(cpp.target_text)
        AND ca.role = 'target1'
      LIMIT 1
    )
    WHERE cpp.course_code = p_course_code AND cpp.target1_audio_id IS NULL
      AND EXISTS (
        SELECT 1 FROM course_audio ca
        WHERE ca.course_code = cpp.course_code
          AND ca.text_normalized = normalize_text(cpp.target_text)
          AND ca.role = 'target1'
      );
    GET DIAGNOSTICS v_linked_phrases_t1 = ROW_COUNT;

    UPDATE course_practice_phrases cpp SET target2_audio_id = (
      SELECT ca.id FROM course_audio ca
      WHERE ca.course_code = cpp.course_code
        AND ca.text_normalized = normalize_text(cpp.target_text)
        AND ca.role = 'target2'
      LIMIT 1
    )
    WHERE cpp.course_code = p_course_code AND cpp.target2_audio_id IS NULL
      AND EXISTS (
        SELECT 1 FROM course_audio ca
        WHERE ca.course_code = cpp.course_code
          AND ca.text_normalized = normalize_text(cpp.target_text)
          AND ca.role = 'target2'
      );
    GET DIAGNOSTICS v_linked_phrases_t2 = ROW_COUNT;

    UPDATE course_seeds cs SET known_audio_id = (
      SELECT ca.id FROM course_audio ca
      WHERE ca.course_code = cs.course_code
        AND ca.text_normalized = normalize_text(cs.known_text)
        AND ca.role IN ('known', 'source')
      LIMIT 1
    )
    WHERE cs.course_code = p_course_code AND cs.known_audio_id IS NULL
      AND EXISTS (
        SELECT 1 FROM course_audio ca
        WHERE ca.course_code = cs.course_code
          AND ca.text_normalized = normalize_text(cs.known_text)
          AND ca.role IN ('known', 'source')
      );
    GET DIAGNOSTICS v_linked_seeds_known = ROW_COUNT;

    UPDATE course_seeds cs SET target1_audio_id = (
      SELECT ca.id FROM course_audio ca
      WHERE ca.course_code = cs.course_code
        AND ca.text_normalized = normalize_text(cs.target_text)
        AND ca.role = 'target1'
      LIMIT 1
    )
    WHERE cs.course_code = p_course_code AND cs.target1_audio_id IS NULL
      AND EXISTS (
        SELECT 1 FROM course_audio ca
        WHERE ca.course_code = cs.course_code
          AND ca.text_normalized = normalize_text(cs.target_text)
          AND ca.role = 'target1'
      );
    GET DIAGNOSTICS v_linked_seeds_t1 = ROW_COUNT;

    UPDATE course_seeds cs SET target2_audio_id = (
      SELECT ca.id FROM course_audio ca
      WHERE ca.course_code = cs.course_code
        AND ca.text_normalized = normalize_text(cs.target_text)
        AND ca.role = 'target2'
      LIMIT 1
    )
    WHERE cs.course_code = p_course_code AND cs.target2_audio_id IS NULL
      AND EXISTS (
        SELECT 1 FROM course_audio ca
        WHERE ca.course_code = cs.course_code
          AND ca.text_normalized = normalize_text(cs.target_text)
          AND ca.role = 'target2'
      );
    GET DIAGNOSTICS v_linked_seeds_t2 = ROW_COUNT;

    RETURN jsonb_build_object(
      'course_code', p_course_code,
      'legos', jsonb_build_object('known', v_linked_legos_known, 'target1', v_linked_legos_t1, 'target2', v_linked_legos_t2),
      'phrases', jsonb_build_object('known', v_linked_phrases_known, 'target1', v_linked_phrases_t1, 'target2', v_linked_phrases_t2),
      'seeds', jsonb_build_object('known', v_linked_seeds_known, 'target1', v_linked_seeds_t1, 'target2', v_linked_seeds_t2)
    );
  END;
  $function$;

-- ===== triggers =====
CREATE TRIGGER audio_autolink AFTER INSERT ON public.course_audio FOR EACH ROW EXECUTE FUNCTION link_audio_to_content();
CREATE TRIGGER trg_course_audio_canonical_identity BEFORE INSERT OR UPDATE OF language, voice_id ON public.course_audio FOR EACH ROW EXECUTE FUNCTION course_audio_canonical_identity();
CREATE TRIGGER trg_course_audio_normalize BEFORE INSERT OR UPDATE ON public.course_audio FOR EACH ROW EXECUTE FUNCTION audio_normalize_text();
CREATE TRIGGER course_legos_pull_duration BEFORE INSERT OR UPDATE OF target1_audio_id, target2_audio_id ON public.course_legos FOR EACH ROW EXECUTE FUNCTION pull_audio_duration_on_link();
CREATE TRIGGER trg_null_lego_audio_on_text_change BEFORE UPDATE ON public.course_legos FOR EACH ROW WHEN (((old.known_text IS DISTINCT FROM new.known_text) OR (old.target_text IS DISTINCT FROM new.target_text))) EXECUTE FUNCTION null_lego_audio_on_text_change();
CREATE TRIGGER course_practice_phrases_pull_duration BEFORE INSERT OR UPDATE OF target1_audio_id, target2_audio_id ON public.course_practice_phrases FOR EACH ROW EXECUTE FUNCTION pull_audio_duration_on_link();
CREATE TRIGGER trg_null_phrase_audio_on_text_change BEFORE UPDATE ON public.course_practice_phrases FOR EACH ROW WHEN (((old.known_text IS DISTINCT FROM new.known_text) OR (old.target_text IS DISTINCT FROM new.target_text))) EXECUTE FUNCTION null_phrase_audio_on_text_change();
CREATE TRIGGER trg_null_seed_audio_on_text_change BEFORE UPDATE ON public.course_seeds FOR EACH ROW WHEN (((old.known_text IS DISTINCT FROM new.known_text) OR (old.target_text IS DISTINCT FROM new.target_text))) EXECUTE FUNCTION null_seed_audio_on_text_change();

-- ===== the clip-identity constraint =====
ALTER TABLE course_audio ADD CONSTRAINT unique_course_audio_per_voice UNIQUE (course_code, text_normalized, language, role, voice_id);
