/**
 * THE HOUSE LOUDNESS, PROVED ON REAL AUDIO — and proved not to touch timbre.
 *
 * Tom, 2026-08-24, on Italian Pod 1: "Enzo is quite a LOT quieter than Ara and
 * also the known language voices. Our mastering process … probably needs
 * tweaking for volume similarity." The ruling that followed has two halves and
 * this file guards both:
 *
 *   1. BAKE THE LOUDNESS MATCHING IN. Every render path masters through the same
 *      closed loop to the same target, so consistency is a property of the chain
 *      rather than of whoever wired the path.
 *   2. NEVER TOUCH TIMBRE. "Never lift a voice to change its timbre, deeper
 *      voices sound better on bass-heavy speakers." The >500 Hz spectral lift
 *      that was measured alongside the loudness fix is rejected PERMANENTLY. So
 *      a test that only proved the levels match would be proving the cheap half:
 *      the tests below also measure the spectrum, and fail if the chain moves
 *      one voice's tone toward another's.
 *
 * WHAT IS EXERCISED HERE. All of it is real: real ffmpeg, real ebur128
 * measurement, the real `volume → true-peak limit → anti-click fade` chain
 * imported from the module rather than restated, the real convergence loop, and
 * — where the machine has a lame binary — the real MP3 render and the real
 * human-recording path end to end. `lame` is off PATH on watson-1 and resolved
 * through LAME_BIN (see the top of audio-processor.cjs), so the mp3 tests probe
 * for it through the module's own checkLameInstalled and say so when it is
 * missing rather than passing quietly on a machine that rendered nothing.
 *
 * No TTS is generated by this file. The clips are synthesised locally.
 *
 * Run: npx vitest run services/audio-processor.house-loudness
 */

import { describe, it, expect, beforeAll } from 'vitest'
const { execFileSync, spawnSync } = require('child_process')
const fs = require('fs')
const os = require('os')
const path = require('path')

const {
  convergeLoudness,
  masterToHouseLoudness,
  HOUSE_LOUDNESS,
  TRUE_PEAK_LIMIT,
  ANTI_CLICK_FADE,
  checkFfmpegInstalled,
  checkLameInstalled,
} = require('./audio-processor.cjs')

let tmpDir
let haveFfmpeg = false
let haveLame = false

// ffmpeg reports both the ebur128 summary and volumedetect on STDERR, so both
// streams are read — a measurement helper that reads only stdout finds nothing.
function ffmpegOutput (args) {
  const r = spawnSync('ffmpeg', args, { encoding: 'utf8', maxBuffer: 1e8 })
  return `${r.stdout || ''}${r.stderr || ''}`
}

/** Integrated loudness of a file, ffmpeg's own EBU R128 meter. */
function lufs (file) {
  const out = ffmpegOutput(['-hide_banner', '-nostats', '-i', file,
    '-af', 'ebur128=framelog=quiet', '-f', 'null', '-'])
  const all = out.match(/I:\s*(-?[\d.]+)\s*LUFS/g) || []
  if (!all.length) throw new Error(`no integrated loudness for ${file}`)
  return parseFloat(all.pop().match(/-?[\d.]+/)[0])
}

/** Mean RMS level of one frequency band, in dB — the timbre probe. */
function bandLevelDb (file, filter) {
  const out = ffmpegOutput(['-hide_banner', '-nostats', '-i', file,
    '-af', `${filter},volumedetect`, '-f', 'null', '-'])
  const m = out.match(/mean_volume:\s*(-?[\d.]+) dB/)
  if (!m) throw new Error(`no mean_volume for ${filter}`)
  return parseFloat(m[1])
}

/**
 * A voice's TONE, independent of how loud it is: the level below 500 Hz minus
 * the level above it. 500 Hz because that is the band a phone speaker throws
 * away, i.e. exactly the axis the rejected spectral lift would have moved.
 * A gain stage cannot change this number; a tilt changes nothing else.
 */
function tiltDb (file) {
  return +(bandLevelDb(file, 'lowpass=f=500') - bandLevelDb(file, 'highpass=f=500')).toFixed(2)
}

/** Synthesise a clip: a set of partials, mixed, at a chosen level. */
function synth (name, freqs, levelDb, seconds = 4) {
  const file = path.join(tmpDir, `${name}.wav`)
  const inputs = freqs.flatMap(f => ['-f', 'lavfi', '-i', `sine=f=${f}:d=${seconds}:r=48000`])
  execFileSync('ffmpeg', ['-y', '-hide_banner', '-loglevel', 'error', ...inputs,
    '-filter_complex', `amix=inputs=${freqs.length}:normalize=0,volume=${levelDb}dB`,
    '-ac', '1', '-ar', '48000', file])
  return file
}

/**
 * A "take" as the recorder uploads one: speech-like partials with real silence
 * either side, Opus-in-WebM, at a chosen recording level.
 */
function takeWebm (name, levelDb) {
  const file = path.join(tmpDir, `${name}.webm`)
  const freqs = [140, 280, 560, 1400]
  const inputs = freqs.flatMap(f => ['-f', 'lavfi', '-i', `sine=f=${f}:d=2:r=48000`])
  execFileSync('ffmpeg', ['-y', '-hide_banner', '-loglevel', 'error', ...inputs,
    '-filter_complex', `amix=inputs=${freqs.length}:normalize=0,volume=${levelDb}dB,adelay=500,apad=pad_dur=0.5`,
    '-ac', '1', '-c:a', 'libopus', '-b:a', '96k', file])
  return file
}

/**
 * A PEAKY source — bass-heavy partials under a syllabic envelope with sharp
 * transients. This is the shape that made the old chain fall short: the true
 * peak limiter pulls gain back out of a peaky voice, so a single measured-once
 * gain lands under target, and lands further under the more gain it needed.
 * Written sample by sample because ffmpeg's generators are all low-crest.
 */
function peakyWav (name, scale) {
  const SR = 48000
  const N = SR * 4
  const buf = Buffer.alloc(44 + N * 2)
  buf.write('RIFF', 0); buf.writeUInt32LE(36 + N * 2, 4); buf.write('WAVE', 8); buf.write('fmt ', 12)
  buf.writeUInt32LE(16, 16); buf.writeUInt16LE(1, 20); buf.writeUInt16LE(1, 22); buf.writeUInt32LE(SR, 24)
  buf.writeUInt32LE(SR * 2, 28); buf.writeUInt16LE(2, 32); buf.writeUInt16LE(16, 34)
  buf.write('data', 36); buf.writeUInt32LE(N * 2, 40)
  for (let i = 0; i < N; i++) {
    const t = i / SR
    const carrier = 0.6 * Math.sin(2 * Math.PI * 120 * t) + 0.4 * Math.sin(2 * Math.PI * 240 * t) + 0.2 * Math.sin(2 * Math.PI * 900 * t)
    const syllable = Math.max(0, Math.sin(2 * Math.PI * 3.1 * t)) ** 2
    const plosive = (t % 0.62 < 0.006) ? 2.5 : 0
    const s = Math.max(-1, Math.min(1, carrier * (0.12 * syllable + plosive * 0.15) * scale))
    buf.writeInt16LE(Math.round(s * 32767), 44 + i * 2)
  }
  const file = path.join(tmpDir, `${name}.wav`)
  fs.writeFileSync(file, buf)
  return file
}

/**
 * The REAL house filter chain, rendered to WAV instead of MP3 — same volume
 * stage, same true-peak limiter, same anti-click fade, all imported from the
 * module rather than restated, so a change to the chain reaches this test.
 */
function renderWav (inputPath, outputPath, gainDb) {
  execFileSync('ffmpeg', ['-y', '-hide_banner', '-loglevel', 'error', '-i', inputPath,
    '-filter:a', `volume=${gainDb.toFixed(2)}dB,${TRUE_PEAK_LIMIT},${ANTI_CLICK_FADE}`,
    '-ac', '1', '-ar', '48000', outputPath])
}

/** Drive the SHIPPING loop over the real chain, writing WAV. */
function houseMasterWav (inputPath, outputPath, targetLufs = HOUSE_LOUDNESS.targetLufs) {
  return convergeLoudness({
    inputLufs: lufs(inputPath),
    targetLufs,
    toleranceDb: HOUSE_LOUDNESS.toleranceDb,
    maxPasses: HOUSE_LOUDNESS.maxPasses,
    renderAtGain: async (gainDb) => renderWav(inputPath, outputPath, gainDb),
    measureOutput: async () => lufs(outputPath),
  })
}

beforeAll(async () => {
  haveFfmpeg = await checkFfmpegInstalled()
  haveLame = await checkLameInstalled()
  if (haveFfmpeg) tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'house-loudness-'))
})

describe('convergeLoudness — the loop, on injected renders', () => {
  /**
   * A limiter that eats part of the gain it is given: this is the defect the
   * loop exists for. The single-pass chain measured the INPUT, applied one gain
   * and never looked again, so the more gain a clip needed the further short it
   * landed — which is why the quietest voice in a pod stayed the quietest.
   */
  const limiterEats = (fraction) => (inputLufs) => {
    let out = null
    return {
      renderAtGain: async (g) => { out = inputLufs + g - fraction * Math.max(0, g) },
      measureOutput: async () => out,
      get outputLufs () { return out },
    }
  }

  it('lands two voices of very different input level on the same target', async () => {
    const quiet = limiterEats(0.2)(-24)   // a quiet, peaky voice — Enzo's shape
    const loud = limiterEats(0.2)(-13)    // a voice that arrives near target

    const a = await convergeLoudness({ inputLufs: -24, targetLufs: -16, ...quiet })
    const b = await convergeLoudness({ inputLufs: -13, targetLufs: -16, ...loud })

    expect(Math.abs(a.outputLUFS - (-16))).toBeLessThanOrEqual(0.5)
    expect(Math.abs(b.outputLUFS - (-16))).toBeLessThanOrEqual(0.5)
    // The point of the whole exercise: the two voices now match EACH OTHER.
    expect(Math.abs(a.outputLUFS - b.outputLUFS)).toBeLessThanOrEqual(1.0)
    expect(a.converged && b.converged).toBe(true)
  })

  it('single-pass would have left the quiet voice short — the loop is what closes it', async () => {
    const quiet = limiterEats(0.2)(-24)
    const singlePassGain = -16 - (-24)              // what the old chain applied
    await quiet.renderAtGain(singlePassGain)
    expect(quiet.outputLufs).toBeLessThan(-17.0)    // 1.6 dB short, and invisible

    const converged = await convergeLoudness({ inputLufs: -24, targetLufs: -16, ...limiterEats(0.2)(-24) })
    expect(Math.abs(converged.outputLUFS - (-16))).toBeLessThanOrEqual(0.5)
    expect(converged.passes).toBeGreaterThan(1)
  })

  it('never re-processes its own output — every pass renders from the source', async () => {
    // A loop that fed each pass back into itself would stack limiter after
    // limiter and colour the clip. Each render must start from the original, so
    // what ships has been through exactly one gain, one limiter and one fade.
    const renders = []
    await convergeLoudness({
      inputLufs: -25, targetLufs: -16,
      renderAtGain: async (g) => { renders.push(g) },
      measureOutput: async () => -25 + renders[renders.length - 1] * 0.75,
    })
    // Gains are absolute corrections of the SAME source, not increments applied
    // on top of the last render.
    expect(renders.length).toBeGreaterThan(1)
    expect(renders[0]).toBeCloseTo(9, 1)
  })
})

describe('the house chain on real audio — matched level, untouched timbre', () => {
  it('matches a deep voice and a bright voice to the target without moving either one\'s tone', async () => {
    if (!haveFfmpeg) return
    // Two "voices" with deliberately different spectra and 12 dB between them:
    // the bass-heavy one is the Enzo shape, the bright one its neighbour.
    const deepIn = synth('deep-in', [110, 165, 220, 440, 1200], -30)
    const brightIn = synth('bright-in', [300, 900, 1800, 3200], -18)

    const deepOut = path.join(tmpDir, 'deep-out.wav')
    const brightOut = path.join(tmpDir, 'bright-out.wav')

    const deepTiltBefore = tiltDb(deepIn)
    const brightTiltBefore = tiltDb(brightIn)
    expect(deepTiltBefore).toBeGreaterThan(brightTiltBefore + 6) // genuinely different voices

    const d = await houseMasterWav(deepIn, deepOut)
    const b = await houseMasterWav(brightIn, brightOut)

    // 1. LEVEL: both land on target, and therefore on each other.
    expect(Math.abs(lufs(deepOut) - HOUSE_LOUDNESS.targetLufs)).toBeLessThanOrEqual(HOUSE_LOUDNESS.toleranceDb)
    expect(Math.abs(lufs(brightOut) - HOUSE_LOUDNESS.targetLufs)).toBeLessThanOrEqual(HOUSE_LOUDNESS.toleranceDb)
    expect(Math.abs(lufs(deepOut) - lufs(brightOut))).toBeLessThanOrEqual(2 * HOUSE_LOUDNESS.toleranceDb)
    expect(d.converged && b.converged).toBe(true)

    // 2. TIMBRE: each voice's own low/high balance is what it was. This is the
    //    assertion that fails the moment anybody puts a shelf, a tilt or an EQ
    //    into the chain — Tom's ruling of 2026-08-24, made permanent in a test.
    expect(Math.abs(tiltDb(deepOut) - deepTiltBefore)).toBeLessThanOrEqual(0.5)
    expect(Math.abs(tiltDb(brightOut) - brightTiltBefore)).toBeLessThanOrEqual(0.5)

    // 3. AND THE VOICES STAY DIFFERENT FROM EACH OTHER. Matching loudness must
    //    never converge two voices' tone: the deep voice is still exactly as
    //    much deeper than the bright one as it was before mastering.
    const spreadBefore = deepTiltBefore - brightTiltBefore
    const spreadAfter = tiltDb(deepOut) - tiltDb(brightOut)
    expect(Math.abs(spreadAfter - spreadBefore)).toBeLessThanOrEqual(0.5)
  }, 120000)

  it('lifts a clip that arrives 18 dB quiet, still without touching its tone', async () => {
    if (!haveFfmpeg) return
    const src = synth('veryquiet', [140, 280, 700, 1600], -34)
    const out = path.join(tmpDir, 'veryquiet-out.wav')
    const tiltBefore = tiltDb(src)

    const r = await houseMasterWav(src, out)

    expect(r.converged).toBe(true)
    expect(Math.abs(lufs(out) - HOUSE_LOUDNESS.targetLufs)).toBeLessThanOrEqual(HOUSE_LOUDNESS.toleranceDb)
    expect(Math.abs(tiltDb(out) - tiltBefore)).toBeLessThanOrEqual(0.5)
  }, 120000)
})

describe('the shipping MP3 path', () => {
  it('masters to the house loudness through lame, and the codec does not tilt it either', async () => {
    if (!haveFfmpeg || !haveLame) {
      // Loud, on purpose: a machine with no lame renders no MP3, and a quietly
      // green tick there would be claiming a proof that never ran.
      console.warn('[house-loudness] NOT RUN: no lame binary (LAME_BIN) on this machine — the MP3 path is unproven here.')
      return
    }
    const src = synth('mp3src', [150, 300, 900, 2400], -27)
    const out = path.join(tmpDir, 'mp3out.mp3')
    const tiltBefore = tiltDb(src)

    const r = await masterToHouseLoudness(src, out)

    expect(r.converged).toBe(true)
    expect(Math.abs(lufs(out) - HOUSE_LOUDNESS.targetLufs)).toBeLessThanOrEqual(HOUSE_LOUDNESS.toleranceDb)
    expect(Math.abs(tiltDb(out) - tiltBefore)).toBeLessThanOrEqual(0.7) // +0.2 for the codec
  }, 120000)

  it('reaches target on a peaky voice where the old open-loop chain fell short — and comes out with the SAME tone as it', async () => {
    if (!haveFfmpeg || !haveLame) {
      console.warn('[house-loudness] NOT RUN: no lame binary — the old-vs-new comparison is unproven here.')
      return
    }
    // This is the Enzo defect, reproduced: a peaky, bass-heavy voice.
    const { normalizeAudioClean } = require('./audio-processor.cjs')
    const src = peakyWav('peaky', 1.0)
    const oldOut = path.join(tmpDir, 'peaky-old.mp3')
    const newOut = path.join(tmpDir, 'peaky-new.mp3')

    const before = await normalizeAudioClean(src, oldOut, HOUSE_LOUDNESS.targetLufs)
    const after = await masterToHouseLoudness(src, newOut)

    // The old chain aimed at the target and missed, silently, downward.
    expect(before.outputLUFS).toBeLessThan(HOUSE_LOUDNESS.targetLufs - 1.0)
    // The loop gets there.
    expect(Math.abs(after.outputLUFS - HOUSE_LOUDNESS.targetLufs)).toBeLessThanOrEqual(HOUSE_LOUDNESS.toleranceDb)

    // AND THE TONE IS IDENTICAL TO THE OLD CHAIN'S. Both go through the same
    // true-peak limiter, which does nudge the balance of a heavily-limited clip;
    // what matters is that closing the loudness loop adds NOTHING of its own.
    // Anyone who adds a shelf, tilt or EQ breaks this assertion, which is the
    // point of it — Tom's ruling of 2026-08-24 is permanent.
    expect(Math.abs(tiltDb(newOut) - tiltDb(oldOut))).toBeLessThanOrEqual(0.2)
  }, 180000)

  it('a human take comes out of processRecordingBuffer on the same target as a TTS clip', async () => {
    if (!haveFfmpeg || !haveLame) {
      console.warn('[house-loudness] NOT RUN: no lame binary — the recording path is unproven here.')
      return
    }
    // THIS IS THE PATH THE RECORDIST'S TAKES GO DOWN. It used to level with a
    // single in-chain `loudnorm`; it now closes the same loop as masterAudio,
    // and this is the test that says so on real bytes.
    const { processRecordingBuffer } = require('./audio-processor.cjs')

    // The same "take", recorded quiet and recorded loud — the two ends of a
    // recordist's session, or two different recordists.
    const quietTake = takeWebm('quiet-take', -32)
    const loudTake = takeWebm('loud-take', -14)

    const q = await processRecordingBuffer(fs.readFileSync(quietTake), { inputFormat: 'webm' })
    const l = await processRecordingBuffer(fs.readFileSync(loudTake), { inputFormat: 'webm' })
    expect(q.metadata.processed && l.metadata.processed).toBe(true)

    const qOut = path.join(tmpDir, 'quiet-take-out.mp3')
    const lOut = path.join(tmpDir, 'loud-take-out.mp3')
    fs.writeFileSync(qOut, q.buffer)
    fs.writeFileSync(lOut, l.buffer)

    // Both on target, and therefore on each other — 18 dB apart going in.
    expect(Math.abs(lufs(qOut) - HOUSE_LOUDNESS.targetLufs)).toBeLessThanOrEqual(HOUSE_LOUDNESS.toleranceDb)
    expect(Math.abs(lufs(lOut) - HOUSE_LOUDNESS.targetLufs)).toBeLessThanOrEqual(HOUSE_LOUDNESS.toleranceDb)
    expect(Math.abs(lufs(qOut) - lufs(lOut))).toBeLessThanOrEqual(2 * HOUSE_LOUDNESS.toleranceDb)

    // And the achieved loudness is reported, not thrown away — the whole reason
    // the shortfall went unseen for so long is that nobody measured the output.
    expect(q.metadata.loudnessConverged).toBe(true)
    expect(q.metadata.loudnessOutLufs).toBeGreaterThan(q.metadata.loudnessInLufs)

    // The format the recordist path has always written is unchanged by moving
    // the loudness stage out of the filter chain: 44.1k mono, one lame encode.
    expect(q.metadata.sampleRate).toBe(44100)
    expect(q.metadata.channels).toBe(1)
  }, 180000)
})
