-- Clip identity, canonical forms — the database half.
--
-- Part 1 of 2. This migration is INERT: it creates a lookup table and three
-- functions and wires them to nothing. No existing row changes, no write
-- behaviour changes. Safe to apply at any time, and it is what the back-fill
-- and the lint need in order to run server-side.
-- Part 2 (20260806_clip_identity_canonical_enforce.sql) attaches the trigger
-- and the constraints, and must NOT be applied until every writer is converted.
--
-- WHY THE DATABASE NEEDS ITS OWN COPY
-- The canonical forms live in services/shared/clip-identity.cjs. Two things
-- write these columns that cannot call it: direct SQL, and any future caller in
-- another repo. A JS-only guard means applying the CHECK constraint turns every
-- writer we missed into a failed insert — silent audio on a live pipeline. A
-- database-side canonicaliser turns the same miss into a corrected insert.
-- That is make-before-break, and it is the pattern the estate already uses for
-- text_normalized (normalize_text + trg_course_audio_normalize).
--
-- HOW THE TWO COPIES ARE KEPT IN STEP
-- They are not two maps. `language_canonical` below is GENERATED from the one
-- map (tools/sync/reference/language_codes.csv) by the one canonicaliser, via
-- tools/generate-language-canonical-sql.cjs, and services/shared/
-- clip-identity.test.js asserts the generator and the module agree. The voice
-- rule is short enough to state directly and is asserted the same way.
--
-- Proven equivalent to the JS on 2026-08-06: all 503 distinct (language,
-- voice_id) values in the live 2.5M-row course_audio agree, both directions,
-- including the values that must RAISE. The proof ran inside a rolled-back
-- transaction against production.
--
-- Rollback: 20260806_clip_identity_canonical_functions.ROLLBACK.sql

BEGIN;

CREATE TABLE IF NOT EXISTS language_canonical (
  raw       text PRIMARY KEY,
  canonical text NOT NULL CHECK (canonical ~ '^[a-z]{3}$')
);

CREATE OR REPLACE FUNCTION canonical_language(code text) RETURNS text
LANGUAGE plpgsql STABLE AS $$
DECLARE primary_subtag text; hit text;
BEGIN
  code := lower(btrim(coalesce(code, '')));
  IF code IN ('', 'auto', 'unknown', 'multi', 'und') THEN
    RAISE EXCEPTION 'clip identity: language % is a placeholder, not a language — resolve it from the course code and role', coalesce(code,'<null>')
      USING ERRCODE = 'check_violation';
  END IF;
  primary_subtag := split_part(regexp_replace(code, '_', '-', 'g'), '-', 1);
  SELECT canonical INTO hit FROM language_canonical WHERE raw = primary_subtag;
  IF hit IS NULL THEN
    RAISE EXCEPTION 'clip identity: language % is not in language_canonical — regenerate it with tools/generate-language-canonical-sql.cjs', code
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN hit;
END $$;

CREATE OR REPLACE FUNCTION canonical_voice_id(v text) RETURNS text
LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE part text; out_parts text[] := '{}';
BEGIN
  v := btrim(coalesce(v, ''));
  IF v = '' OR lower(v) IN ('legacy_import','legacy','human','human_recording','unknown','default','auto') THEN
    RAISE EXCEPTION 'clip identity: voice_id % is a placeholder, not a voice', coalesce(v,'<null>')
      USING ERRCODE = 'check_violation';
  END IF;
  IF v ~* '^comp:' THEN
    FOREACH part IN ARRAY string_to_array(substr(v, 6), '+') LOOP
      IF btrim(part) <> '' THEN
        out_parts := out_parts || canonical_voice_id(btrim(part));
      END IF;
    END LOOP;
    IF array_length(out_parts, 1) IS NULL THEN
      RAISE EXCEPTION 'clip identity: composite voice_id % has no parts', v USING ERRCODE = 'check_violation';
    END IF;
    RETURN 'comp:' || array_to_string(out_parts, '+');
  END IF;
  IF v ~ '^(azure|xai|elevenlabs|google|narakeet|human)_.' THEN RETURN v; END IF;
  IF v ~ '^[a-z]{2,3}-[A-Za-z]{2,4}-[A-Za-z]+Neural$' THEN RETURN 'azure_' || v; END IF;
  IF lower(v) IN ('eve','leo','ara','sal','rex','gfzdpspr5fdp','bedd6226') THEN RETURN 'xai_' || v; END IF;
  RAISE EXCEPTION 'clip identity: voice_id % has no provider prefix and no inferable provider — the writer must supply one', v
    USING ERRCODE = 'check_violation';
END $$;

-- ── the generated language map ──────────────────────────────────────────────
-- generated by tools/generate-language-canonical-sql.cjs — do not hand-edit
INSERT INTO language_canonical (raw, canonical) VALUES
  ('af','afr'),
  ('afr','afr'),
  ('am','amh'),
  ('amh','amh'),
  ('ar','ara'),
  ('ara','ara'),
  ('as','asm'),
  ('asm','asm'),
  ('az','aze'),
  ('aze','aze'),
  ('be','bel'),
  ('bel','bel'),
  ('ben','ben'),
  ('bg','bul'),
  ('bn','ben'),
  ('bos','bos'),
  ('br','bre'),
  ('bs','bos'),
  ('bul','bul'),
  ('ca','cat'),
  ('cat','cat'),
  ('ceb','ceb'),
  ('ces','ces'),
  ('cmn','zho'),
  ('cs','ces'),
  ('cy','cym'),
  ('cy-north','cym'),
  ('cy-south','cym'),
  ('cym','cym'),
  ('da','dan'),
  ('dan','dan'),
  ('de','deu'),
  ('deu','deu'),
  ('el','ell'),
  ('ell','ell'),
  ('en','eng'),
  ('eng','eng'),
  ('es','spa'),
  ('es-es','spa'),
  ('es-mx','spa'),
  ('est','est'),
  ('et','est'),
  ('eu','eus'),
  ('eus','eus'),
  ('fa','fas'),
  ('fas','fas'),
  ('fi','fin'),
  ('fil','fil'),
  ('fin','fin'),
  ('fr','fra'),
  ('fra','fra'),
  ('fur','fur'),
  ('ga','gle'),
  ('gd','gla'),
  ('gl','glg'),
  ('gla','gla'),
  ('gle','gle'),
  ('glg','glg'),
  ('glv','glv'),
  ('gu','guj'),
  ('guj','guj'),
  ('gv','glv'),
  ('ha','hau'),
  ('hak','hak'),
  ('hau','hau'),
  ('he','heb'),
  ('heb','heb'),
  ('hi','hin'),
  ('hin','hin'),
  ('hr','hrv'),
  ('hrv','hrv'),
  ('hu','hun'),
  ('hun','hun'),
  ('hy','hye'),
  ('hye','hye'),
  ('id','ind'),
  ('ind','ind'),
  ('is','isl'),
  ('isl','isl'),
  ('it','ita'),
  ('ita','ita'),
  ('ja','jpn'),
  ('jav','jav'),
  ('jpn','jpn'),
  ('jv','jav'),
  ('ka','kat'),
  ('kan','kan'),
  ('kat','kat'),
  ('kaz','kaz'),
  ('khm','khm'),
  ('kir','kir'),
  ('kk','kaz'),
  ('km','khm'),
  ('kn','kan'),
  ('ko','kor'),
  ('kor','kor'),
  ('kw','cor'),
  ('ky','kir'),
  ('lao','lao'),
  ('lav','lav'),
  ('lb','ltz'),
  ('lin','lin'),
  ('lit','lit'),
  ('lmo','lmo'),
  ('ln','lin'),
  ('lo','lao'),
  ('lt','lit'),
  ('ltz','ltz'),
  ('lv','lav'),
  ('mal','mal'),
  ('mar','mar'),
  ('mk','mkd'),
  ('mkd','mkd'),
  ('ml','mal'),
  ('mlt','mlt'),
  ('mr','mar'),
  ('ms','msa'),
  ('msa','msa'),
  ('mt','mlt'),
  ('my','mya'),
  ('mya','mya'),
  ('nan','nan'),
  ('nap','nap'),
  ('nb','nor'),
  ('ne','nep'),
  ('nep','nep'),
  ('nl','nld'),
  ('nld','nld'),
  ('nn','nno'),
  ('nno','nno'),
  ('no','nor'),
  ('nor','nor'),
  ('ny','nya'),
  ('nya','nya'),
  ('pa','pan'),
  ('pan','pan'),
  ('pdc','pdc'),
  ('pl','pol'),
  ('pol','pol'),
  ('por','por'),
  ('ps','pus'),
  ('pt','por'),
  ('pt-br','por'),
  ('pt-pt','por'),
  ('pus','pus'),
  ('rgn','rgn'),
  ('rm','roh'),
  ('ro','ron'),
  ('roh','roh'),
  ('ron','ron'),
  ('ru','rus'),
  ('rus','rus'),
  ('scn','scn'),
  ('sd','snd'),
  ('se','sme'),
  ('si','sin'),
  ('sin','sin'),
  ('sk','slk'),
  ('sl','slv'),
  ('slk','slk'),
  ('slv','slv'),
  ('sme','sme'),
  ('snd','snd'),
  ('so','som'),
  ('som','som'),
  ('spa','spa'),
  ('sq','sqi'),
  ('sqi','sqi'),
  ('sr','srp'),
  ('srp','srp'),
  ('sv','swe'),
  ('sw','swa'),
  ('swa','swa'),
  ('swe','swe'),
  ('ta','tam'),
  ('tam','tam'),
  ('te','tel'),
  ('tel','tel'),
  ('th','tha'),
  ('tha','tha'),
  ('tr','tur'),
  ('tur','tur'),
  ('uk','ukr'),
  ('ukr','ukr'),
  ('ur','urd'),
  ('urd','urd'),
  ('uz','uzb'),
  ('uzb','uzb'),
  ('vec','vec'),
  ('vi','vie'),
  ('vie','vie'),
  ('xh','xho'),
  ('xho','xho'),
  ('yi','yid'),
  ('yid','yid'),
  ('yo','yor'),
  ('yor','yor'),
  ('yue','yue'),
  ('zh','zho'),
  ('zho','zho'),
  ('zu','zul'),
  ('zul','zul'),
  ('zzz','zzz')
ON CONFLICT (raw) DO UPDATE SET canonical = EXCLUDED.canonical;

-- ── non-throwing variants, for audits and the back-fill ─────────────────────
CREATE OR REPLACE FUNCTION try_canonical_language(code text) RETURNS text
LANGUAGE plpgsql STABLE AS $$
BEGIN RETURN canonical_language(code); EXCEPTION WHEN OTHERS THEN RETURN NULL; END $$;

CREATE OR REPLACE FUNCTION try_canonical_voice_id(v text) RETURNS text
LANGUAGE plpgsql IMMUTABLE AS $$
BEGIN RETURN canonical_voice_id(v); EXCEPTION WHEN OTHERS THEN RETURN NULL; END $$;

COMMENT ON TABLE language_canonical IS
  'Generated by tools/generate-language-canonical-sql.cjs from tools/sync/reference/language_codes.csv. Do not hand-edit; regenerate.';
COMMENT ON FUNCTION canonical_language(text) IS
  'Region-free three-letter database_code. Mirror of canonicalLanguage() in services/shared/clip-identity.cjs.';
COMMENT ON FUNCTION canonical_voice_id(text) IS
  '<provider>_<provider voice id>; composites keep the comp: namespace. Mirror of canonicalVoiceId() in services/shared/clip-identity.cjs.';

COMMIT;
