-- Add bookend role types for LISTEN-block audio bookends
--
-- Each round that contains LISTEN cycles (retired seeds replayed in target
-- language) now gets a known-language audio clip before and after the block
-- so learners aren't blindsided by the mode switch:
--   "And now, just listen to the following sentences."   <- bookend_listen_intro
--   [LISTEN x N retired seeds]
--   "And now, let's go back to speaking practice."       <- bookend_listen_outro
--
-- Stored in shared_audio (one row per known language, generated by Azure TTS in
-- the course's most-common known voice) and copied into course_audio per
-- course, mirroring the existing instruction/encouragement workflow.
--
-- Why new role values rather than reusing 'instruction':
-- - MetaCommentaryService loads role='instruction' rows and plays them between
--   rounds in sequence. Bookends must only play around LISTEN blocks — never
--   standalone — so they need their own role to stay out of that rotation.

-- ----------------------------------------------------------------------------
-- shared_audio.audio_type
-- ----------------------------------------------------------------------------
ALTER TABLE shared_audio DROP CONSTRAINT IF EXISTS shared_audio_audio_type_check;
ALTER TABLE shared_audio ADD CONSTRAINT shared_audio_audio_type_check
  CHECK (audio_type IN (
    'encouragement',
    'instruction',
    'paywall',
    'bookend_listen_intro',
    'bookend_listen_outro'
  ));

-- ----------------------------------------------------------------------------
-- course_audio.role
-- ----------------------------------------------------------------------------
-- 'welcome' is undocumented in apml/core/audio-registry-v13.apml but exists in
-- production (89 rows). Preserving so the constraint doesn't violate existing
-- data — log it here so a future schema audit can decide whether to formalise
-- or migrate it.
ALTER TABLE course_audio DROP CONSTRAINT IF EXISTS course_audio_role_check;
ALTER TABLE course_audio ADD CONSTRAINT course_audio_role_check
  CHECK (role IN (
    'known',
    'target1',
    'target2',
    'presentation',
    'encouragement',
    'instruction',
    'welcome',
    'bookend_listen_intro',
    'bookend_listen_outro'
  ));
