<template>
  <section class="bg-surface rounded-lg border border-line p-6 shadow-sm">
    <div class="flex items-center gap-3 mb-6">
      <svg class="w-6 h-6 shared-audio-icon text-cyan-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z"></path>
      </svg>
      <div>
        <h3 class="text-lg font-semibold text-ink">Shared Audio</h3>
        <p class="text-sm text-muted">Welcome, encouragements, instructions — generated by separate scripts, not by Generate Missing Audio.</p>
      </div>
    </div>

    <div v-if="loading" class="text-faint text-sm">Loading shared audio status...</div>
    <div v-else-if="error" class="text-danger text-sm">{{ error }}</div>
    <div v-else-if="status" class="space-y-3">
      <!-- Welcome — single audio, prominent listen button -->
      <div class="bg-surface-2 rounded-lg p-4 border border-line">
        <div class="flex items-center justify-between gap-3">
          <div class="flex items-center gap-3">
            <span class="inline-block w-2.5 h-2.5 rounded-full shared-audio-pip"
                  :class="status.welcome.populated ? 'pip-ok bg-emerald-400' : 'pip-warn bg-amber-400'"></span>
            <div>
              <div class="text-ink font-medium">Welcome</div>
              <div class="text-xs text-faint">
                {{ status.welcome.populated ? 'Populated' : 'Missing — generate or fetch from shared bank' }}
              </div>
            </div>
          </div>
          <div class="flex items-center gap-2">
            <button v-if="status.welcome.populated && status.welcome.s3_key"
                    @click="playWelcome"
                    :disabled="playingWelcome"
                    class="shared-audio-listen px-3 py-1.5 bg-cyan-600/80 hover:bg-cyan-600 disabled:bg-surface-2 rounded text-xs text-white">
              {{ playingWelcome ? 'Playing…' : '▶ Listen' }}
            </button>
          </div>
        </div>
        <div v-if="status.welcome.text" class="mt-2 text-xs text-muted italic">
          "{{ status.welcome.text.slice(0, 120) }}{{ status.welcome.text.length > 120 ? '…' : '' }}"
        </div>
      </div>

      <!-- Instructions (legacy: ordered encouragements) -->
      <SharedBucketRow
        label="Instructions (Ordered encouragements)"
        :populated="status.ordered.populated_count"
        :total="status.ordered.total"
        :complete="status.ordered.complete"
        sub="Played in sequence at fixed points in the course."
      />

      <!-- Encouragements (legacy: pooled encouragements) -->
      <SharedBucketRow
        label="Encouragements (Pooled encouragements)"
        :populated="status.pooled.populated_count"
        :total="status.pooled.total"
        :complete="status.pooled.complete"
        sub="Played randomly between exercises."
      />

      <!-- Paywall — render for ALL courses; show "Not required" for non-paid -->
      <div v-if="!status.paywall.applies" class="bg-surface-2 rounded-lg p-4 border border-line opacity-70">
        <div class="flex items-center gap-3">
          <span class="inline-block w-2.5 h-2.5 rounded-full bg-faint"></span>
          <div class="flex-1">
            <div class="flex items-center justify-between">
              <span class="text-ink font-medium">Paywall Encouragements</span>
              <span class="text-xs text-faint italic">Not required for this course</span>
            </div>
            <div class="text-xs text-faint mt-0.5">
              Course target language ({{ getLanguageName(status.targetLang) }}) is not in the paid set — paywall content not used.
            </div>
          </div>
        </div>
      </div>
      <SharedBucketRow
        v-else
        label="Paywall Encouragements"
        :populated="status.paywall.populated_count"
        :total="null"
        :complete="status.paywall.populated_count > 0"
        :sub="status.paywall.populated_count > 0
          ? 'Sequential prompts for free-tier users after free content ends.'
          : 'REQUIRED: course target language is paid, but no paywall content for this known language yet.'"
      />
    </div>

    <!-- Hidden audio element for welcome playback -->
    <audio ref="welcomeAudio" @ended="playingWelcome = false" @pause="playingWelcome = false"></audio>
  </section>
</template>

<script setup lang="ts">
import { ref, watch, onMounted, h, defineComponent } from 'vue'
import { getApiUrl } from '@/services/api'
import { useCourses } from '@/composables/useCourses'

interface SharedAudioStatus {
  knownLang: string
  targetLang: string
  welcome: { populated: boolean; text: string | null; s3_key: string | null }
  ordered: { populated_count: number; total: number; complete: boolean }
  pooled: { populated_count: number; total: number; complete: boolean }
  paywall: { applies: boolean; populated_count: number }
}

const props = defineProps<{ courseCode: string }>()

const { getLanguageName } = useCourses()

const status = ref<SharedAudioStatus | null>(null)
const loading = ref(true)
const error = ref<string | null>(null)
const welcomeAudio = ref<HTMLAudioElement | null>(null)
const playingWelcome = ref(false)

async function load() {
  loading.value = true
  error.value = null
  try {
    const apiUrl = getApiUrl()
    const r = await fetch(`${apiUrl}/api/production/${props.courseCode}/shared-audio-status`)
    if (!r.ok) throw new Error(`HTTP ${r.status}`)
    status.value = await r.json()
  } catch (e: any) {
    error.value = e.message || String(e)
  } finally {
    loading.value = false
  }
}

async function playWelcome() {
  if (!status.value?.welcome.s3_key) return
  try {
    // Welcome audio is stored under the course's course_audio with role=welcome.
    // Resolve a signed URL via the existing audio-url endpoint.
    const m = status.value.welcome.s3_key.match(/([0-9A-Fa-f-]{36})/)
    if (!m) return
    const apiUrl = getApiUrl()
    const r = await fetch(`${apiUrl}/api/production/${props.courseCode}/audio/${m[1]}/url`)
    if (!r.ok) return
    const { url } = await r.json()
    if (welcomeAudio.value && url) {
      welcomeAudio.value.src = url
      playingWelcome.value = true
      welcomeAudio.value.play().catch(() => { playingWelcome.value = false })
    }
  } catch (e) {
    console.error('[SharedAudio] welcome play failed', e)
  }
}

onMounted(load)
watch(() => props.courseCode, load)

// Inline sub-component: a single row showing populated/total + status pip + sub-text
const SharedBucketRow = defineComponent({
  props: {
    label: { type: String, required: true },
    populated: { type: Number, required: true },
    total: { type: Number as any, default: null },
    complete: { type: Boolean, default: false },
    sub: { type: String, default: '' }
  },
  setup(p) {
    return () => h('div', { class: 'bg-surface-2 rounded-lg p-4 border border-line' }, [
      h('div', { class: 'flex items-center gap-3' }, [
        h('span', {
          class: 'inline-block w-2.5 h-2.5 rounded-full shared-audio-pip ' +
            (p.complete ? 'pip-ok' : (p.populated > 0 ? 'pip-warn' : 'pip-bad'))
        }),
        h('div', { class: 'flex-1' }, [
          h('div', { class: 'flex items-center justify-between' }, [
            h('span', { class: 'text-ink font-medium' }, p.label),
            h('span', { class: 'text-sm text-ink font-mono' },
              p.total !== null ? `${p.populated} / ${p.total}` : `${p.populated}`)
          ]),
          p.sub ? h('div', { class: 'text-xs text-faint mt-0.5' }, p.sub) : null
        ])
      ])
    ])
  }
})
</script>

<style scoped>
/* Status pips — keep the original dark-mode hues; darken for legibility on light surfaces. */
.shared-audio-pip.pip-ok   { background: var(--accent-2); }
.shared-audio-pip.pip-warn { background: #fbbf24; }
.shared-audio-pip.pip-bad  { background: var(--danger); }

:root[data-theme="light"] .shared-audio-pip.pip-ok   { background: #059669; }
:root[data-theme="light"] .shared-audio-pip.pip-warn { background: #b45309; }
:root[data-theme="light"] .shared-audio-pip.pip-bad  { background: #dc2626; }

/* Header icon: cyan reads fine on dark; needs a darker cyan to hit ~3:1 on white. */
:root[data-theme="light"] .shared-audio-icon { color: #0e7490; }

/* Listen button: cyan-600/80 leaves white text under AA on light; solidify + darken. */
:root[data-theme="light"] .shared-audio-listen:not(:disabled) { background-color: #0e7490; }
:root[data-theme="light"] .shared-audio-listen:hover:not(:disabled) { background-color: #155e75; }
</style>
