<script setup>
/**
 * VAD Lab — /admin/labs/vad
 *
 * The prosody-measurement work made audible and visible. Sibling to the Pod
 * Lab. Data is the 2026-07-28 invariance study (774 clips, 388 pairs) baked
 * to public/vad-lab/lab-data.json by tools/prosody-lab/build-lab-data.cjs;
 * findings doc: docs/course-optimization/prosody-lab-poc.md; parent theory:
 * ssi-learning-app/docs/vad-feedback-design.md.
 *
 * v2 (founder-commissioned, 2026-07-29):
 *  - live contour view: energy envelope + moving playhead + syllable ticks
 *    (VadContour.vue) — watch what the number sees, not just trust it
 *  - record-yourself flow: record against any model clip, scored by the SAME
 *    extractor on both sides (vadProsody.js mirrors prosody.py); recordings
 *    tagged language + self-rated proficiency → /api/vad-recordings (S3) as
 *    the calibration corpus. Private admin tool — no learner exposure.
 *  - experimental pitch-shape track (register-normalised semitones), display
 *    only, NEVER folded into a score — melody is voice-dominated (AUC 0.464)
 *  - founder ruling applied: "human v TTS speed is not a thing" — no tempo
 *    claim is framed as human-vs-TTS anywhere on this surface
 *
 * Honest-science surface, not a marketing toy: the voice-dominated dimensions
 * are shown AS failures, the deceptive pair is curated on purpose, and the
 * confounded Welsh comparison carries its confound in the copy.
 *
 * Zero LLM at runtime. Audio streams from the deployed learning-app proxy —
 * every study clip is a course_audio row, so nothing is copied anywhere.
 */
import { ref, computed, onMounted, onBeforeUnmount } from 'vue'
import VadContour from './VadContour.vue'
import { languageName } from '@/utils/languageNames'
import { dirFor } from '@/utils/textDirection.js'
import {
  dtwWarp,
  extractFeatures,
  trimWindow,
  decodeTo16kMono,
  comparePhraseDims,
  activeSpeechDb,
  renderLoudnessMatchedWav,
} from './vadProsody.js'

const AUDIO_BASE = 'https://saysomethingin.app/api/audio'
const REC_API = '/api/vad-recordings'

// ── data ────────────────────────────────────────────────────────────────────
const loading = ref(true)
const loadError = ref('')
const lab = ref(null) // lab-data.json payload

onMounted(async () => {
  // The payload is committed as ~30KB part-files (see build-lab-data.cjs for
  // why) — fetch the manifest, pull all parts, reassemble bytes, parse once.
  try {
    const base = `${import.meta.env.BASE_URL}vad-lab/`
    const man = await fetch(`${base}manifest.json`)
    if (!man.ok) throw new Error(`manifest HTTP ${man.status}`)
    const { parts } = await man.json()
    const bufs = await Promise.all(
      parts.map(async (name) => {
        const res = await fetch(`${base}${name}`)
        if (!res.ok) throw new Error(`${name} HTTP ${res.status}`)
        return new Uint8Array(await res.arrayBuffer())
      })
    )
    const total = bufs.reduce((n, b) => n + b.length, 0)
    const bytes = new Uint8Array(total)
    let off = 0
    for (const b of bufs) {
      bytes.set(b, off)
      off += b.length
    }
    lab.value = JSON.parse(new TextDecoder().decode(bytes))
  } catch (e) {
    loadError.value = `Could not load lab data: ${e.message}`
  } finally {
    loading.value = false
  }
})

// ── clean-mastered xAI copies (founder ruling 2026-07-29) ───────────────────
// public/vad-lab-clean/ holds re-renders of the lab's xAI clips mastered
// WITHOUT the compressor stage that lifts the clones' noise floor ("that
// hissy mastering stuff"). Generated by tools/prosody-lab/
// remaster-vad-lab-clean.cjs; absent until that has run — the A/B affordance
// below simply stays hidden.
const cleanClips = ref(null)
const cleanBase = `${import.meta.env.BASE_URL}vad-lab-clean/`
onMounted(async () => {
  try {
    const res = await fetch(`${cleanBase}manifest.json`)
    if (res.ok) cleanClips.value = (await res.json()).clips || null
  } catch {
    /* no clean clips yet */
  }
})
const cleanFor = (id) => (cleanClips.value && cleanClips.value[id] ? cleanClips.value[id] : null)
const cleanSrc = (id) => `${cleanBase}${id}.mp3`

const pairById = computed(() => {
  const m = new Map()
  if (lab.value) for (const p of lab.value.pairs) m.set(p.pair_id, p)
  return m
})

// ── tabs ────────────────────────────────────────────────────────────────────
const tab = ref('tour') // tour | lab | record | proves

// ── labels ──────────────────────────────────────────────────────────────────
const CATEGORY_META = {
  rerender: { label: 'Same voice, re-rendered', short: 'RE-RENDER' },
  crossvoice: { label: 'Same phrase, new voice', short: 'NEW VOICE' },
  crossprovider: { label: 'Same phrase, new provider', short: 'NEW PROVIDER' },
  diffphrase: { label: 'Different phrases', short: 'DIFF PHRASE' },
  human_tts_eng: { label: 'Human recording vs TTS · English', short: 'HUMAN v TTS' },
  human_tts_cym: { label: 'Cross-human, same phrase · Welsh', short: 'CROSS-HUMAN' },
}
const catMeta = (c) => CATEGORY_META[c] || { label: c, short: c }

const langName = (l) => languageName(l)

function voiceLabel(side) {
  if (side.origin === 'human') return 'Human recording'
  // Welsh estate is 100% human-recorded — the DB's 'tts' origin tag on some
  // legacy Welsh rows is a labelling artefact, not a synthetic voice. Any
  // 'legacy_import' voice id is a human recording regardless of that tag.
  if (side.voice === 'legacy_import') return 'Human recording (different voice)'
  const v = side.voice || ''
  const az = v.match(/^azure_([a-z]{2}-[A-Z]{2})-(.+?)(Neural)?$/)
  if (az) return `Azure · ${az[2]} (${az[1]})`
  if (v.startsWith('xai_') || side.provider === 'xai') return `xAI · ${v.replace(/^xai_/, '')}`
  if (v === 'eve') return 'xAI · eve'
  return v || side.provider || 'TTS'
}

// ── audio playback (one shared element; tap toggles; playhead via rAF) ─────
const playingId = ref('')
const playFrac = ref(0) // 0..1 through the playing clip (FULL untrimmed timeline)
const playTime = ref(0) // seconds into the playing clip
let audioEl = null
let rafId = 0
function tickPlayhead() {
  // Keep looping for as long as a clip is nominally playing — duration is NaN
  // for the first frames after src is set, so gating survival on it killed the
  // loop before metadata ever arrived. Only the UPDATE needs valid data.
  if (!playingId.value) return
  if (audioEl && audioEl.duration > 0) {
    playFrac.value = audioEl.currentTime / audioEl.duration
    playTime.value = audioEl.currentTime
  }
  rafId = requestAnimationFrame(tickPlayhead)
}
function play(clipId, src) {
  if (playingId.value === clipId) {
    audioEl?.pause()
    playingId.value = ''
    return
  }
  if (!audioEl) {
    audioEl = new Audio()
    audioEl.addEventListener('ended', () => (playingId.value = ''))
    audioEl.addEventListener('error', () => (playingId.value = ''))
  }
  audioEl.src = src || `${AUDIO_BASE}/${clipId}`
  audioEl.play().catch(() => {
    if (playingId.value === clipId) playingId.value = ''
  })
  playingId.value = clipId
  playFrac.value = 0
  playTime.value = 0
  if (!src) ensureTrim(clipId) // study clip — resolve its trim window
  cancelAnimationFrame(rafId)
  rafId = requestAnimationFrame(tickPlayhead)
}

// ── playhead honesty: map clip time onto the contour's trimmed window ──────
// The contours (baked AND live) span only the silence-trimmed speech, but the
// audio element plays the FULL clip — so currentTime/duration lies whenever a
// clip carries lead/tail silence. Each clip's trim window is computed in the
// browser by the extractor's own silence gate (trimWindow) and cached; the
// playhead then runs (t − trimStart)/durS, parked at 0 before speech starts
// and at 1 after it ends — which IS the honest position. Until a window
// resolves (first play of a clip, sub-second decode) the raw fraction stands.
const trims = ref({}) // clipId → { trimStartS, durS } | null (unusable → raw)
const trimPending = new Set()
async function ensureTrim(clipId) {
  if (clipId in trims.value || trimPending.has(clipId)) return
  trimPending.add(clipId)
  try {
    const cached = modelFeatCache.get(clipId)
    const tw = cached
      ? { trimStartS: cached.feat.trim_start_s, durS: cached.feat.duration_s }
      : await (async () => {
          const res = await fetch(`${AUDIO_BASE}/${clipId}`)
          if (!res.ok) throw new Error(`HTTP ${res.status}`)
          return trimWindow(await decodeTo16kMono(await res.arrayBuffer()))
        })()
    trims.value = { ...trims.value, [clipId]: tw }
  } catch {
    trims.value = { ...trims.value, [clipId]: null }
  } finally {
    trimPending.delete(clipId)
  }
}
const mappedPlayFrac = computed(() => {
  const id = playingId.value
  if (!id) return 0
  const tw =
    id === 'self-recording'
      ? recFeat.value && { trimStartS: recFeat.value.trim_start_s, durS: recFeat.value.duration_s }
      : trims.value[id]
  if (!tw || !(tw.durS > 0)) return playFrac.value
  return Math.min(1, Math.max(0, (playTime.value - tw.trimStartS) / tw.durS))
})
function playSideFor(pair) {
  if (playingId.value === pair.a.id) return 'a'
  if (playingId.value === pair.b.id) return 'b'
  return ''
}
onBeforeUnmount(() => {
  audioEl?.pause()
  cancelAnimationFrame(rafId)
  stopStream()
  if (recUrl.value) URL.revokeObjectURL(recUrl.value)
})

// ── contour overlay ─────────────────────────────────────────────────────────
// Energy contours are z-scored, 150 points. DTW alignment (same cost as the
// study: mean |a-b| along the optimal path) is cheap at 150×150, computed on
// demand and cached per pair. The warp also yields bmap — b-index → a-index —
// so the playhead and clip-b's syllable ticks land where the alignment put
// that moment of audio.
const dtwCache = new Map()
function contourPair(pair, aligned) {
  const ca = lab.value?.contours?.[pair.a.id]
  const cb = lab.value?.contours?.[pair.b.id]
  if (!ca?.e?.length || !cb?.e?.length) return null
  let bSeries = cb.e
  let bmap = null
  if (aligned) {
    const key = pair.pair_id
    if (!dtwCache.has(key)) dtwCache.set(key, dtwWarp(ca.e, cb.e))
    const w = dtwCache.get(key)
    bSeries = w.warped
    bmap = w.bmap
  }
  return {
    a: ca.e,
    b: bSeries,
    bmap,
    durA: ca.dur,
    durB: cb.dur,
    sylTA: ca.sylT || [],
    sylTB: cb.sylT || [],
    f0A: ca.f0 || null,
    f0B: cb.f0 || null,
  }
}
const showPitch = ref(true)

// ── score display ───────────────────────────────────────────────────────────
// Each dimension is shown as a dot on a track anchored by the study's own
// near (re-render) and far (different phrase) medians — the honest scale.
const DIM_META = {
  energy_dtw: { label: 'Energy contour (DTW)', hint: 'stress & prominence rhythm — the phrase carrier' },
  dur_log_ratio: { label: 'Duration (log-ratio)', hint: 'overall pacing' },
  syl_count_diff: { label: 'Syllable count Δ', hint: 'how many beats' },
  syl_rate_diff: { label: 'Syllable rate Δ', hint: 'voice-dominated — not scored' },
  f0_dtw: { label: 'F0 contour (DTW)', hint: 'melody — voice-dominated, never scored' },
  f0_range_diff_st: { label: 'F0 range Δ (st)', hint: 'voice-dominated — not scored' },
  f0_register_gap_st: { label: 'Register gap (st)', hint: 'pure voice identity' },
  voiced_frac_diff: { label: 'Voiced fraction Δ', hint: 'voice-dominated — not scored' },
}
const PHRASE_DIMS = ['energy_dtw', 'dur_log_ratio', 'syl_count_diff']
function anchors(dim) {
  const d = lab.value?.dimension_discrimination?.[dim]
  return d ? { near: d.near_p50, far: d.far_p50 } : null
}
function trackPos(dim, value) {
  const a = anchors(dim)
  if (!a || value == null) return null
  const max = Math.max(a.far * 1.4, value, 1e-6)
  return {
    v: Math.min(100, (value / max) * 100),
    near: Math.min(100, (a.near / max) * 100),
    far: Math.min(100, (a.far / max) * 100),
  }
}
function fmt(v, dp = 3) {
  if (v == null) return '—'
  return Number.isInteger(v) ? String(v) : v.toFixed(dp)
}
// Combined score verdict against the study's own category medians.
function combinedVerdict(p) {
  if (p.combined == null) return { text: 'no score', cls: 'v-na' }
  const cs = lab.value.combined_score
  const mid = (cs.p50_by_category.crossprovider + cs.p50_by_category.diffphrase) / 2
  if (p.combined <= cs.p50_by_category.crossvoice) return { text: 'same-phrase range', cls: 'v-same' }
  if (p.combined <= mid) return { text: 'borderline', cls: 'v-mid' }
  return { text: 'different-phrase range', cls: 'v-diff' }
}

// ── the listening tour (curated) ────────────────────────────────────────────
// Pair ids are stable: the study samples deterministically (order by md5).
const TOUR = [
  {
    pair_id: 'crossvoice:8a3eb330:8cfcd10d',
    title: '1 · Same phrase, new speaker — the metric barely moves',
    teaches:
      'Two different Azure voices, one female and one male, saying “para tener”. The energy contour distance is 0.031 — inside re-render territory. What survives a change of speaker is the phrase itself: this is the understandability core the whole design measures.',
  },
  {
    pair_id: 'crossprovider:344e0301:e1e31a00',
    title: '2 · Same phrase, different provider — still recognisably the same',
    teaches:
      'Azure’s Henri against xAI’s eve on “entendre la vérité” — different companies, different synthesis stacks, energy distance 0.062. Swapping vendor moves prosody more than swapping voice within one vendor, but the phrase still reads through.',
  },
  {
    pair_id: 'crossvoice:16c9db02:132a3395',
    title: '3 · Italian — a whole sentence survives the speaker swap',
    teaches:
      'Azure’s Elsa and Benigno — a female and a male Italian voice — both saying “Ha detto che è la stessa cosa”. Energy distance 0.079, durations within one percent of each other, identical syllable count. He said it’s the same thing, and the metric agrees: the phrase carrier works sentence-long, and it works in Italian.',
  },
  {
    pair_id: 'crossvoice:6f4c2db1:0504a166',
    title: '4 · Mandarin — a tone language doesn’t change the rules',
    teaches:
      'Xiaoxiao and Yunyi, Azure’s two Mandarin voices, saying “没有人在另一头”. Mandarin makes pitch carry word meaning, so you might expect melody to become the phrase — but what survives the voice change is still the energy shape (0.071, close to the re-render floor). What moves is pacing: these two multilingual voices pace Mandarin differently enough to pull the combined score into the borderline band, the same duration fragility the last card in this tour teaches. The pitch track stays display-only even here.',
  },
  {
    pair_id: 'crossvoice:32ee8384:7783cd73',
    title: '5 · Korean — new script, same physics',
    teaches:
      'Azure’s GookMin and YuJin saying “그녀는 더 많이 기억해요” — she remembers more. Energy distance 0.095 and a combined score inside the same-phrase range. Korean’s rhythm and sound system are nothing like the Romance pairs above, and the phrase core still reads straight through a change of speaker.',
  },
  {
    pair_id: 'crossprovider:0cb2e9b9:2bcc4791',
    title: '6 · Different company, same Italian phrase — zero duration gap',
    teaches:
      'Azure’s Benigno against xAI’s ara clone on “può lasciarti tenere qualcosa per un po’” — ten-plus syllables, two entirely different synthesis stacks, and they land the phrase with an identical overall duration and a combined score of 0.28, deep inside same-phrase territory. Cross-provider agreement like this is what lets the audio estate be used as a controlled lab at all.',
  },
  {
    pair_id: 'diffphrase:476f55ba:9606cf67',
    title: '7 · The deceptive pair — the metric hears HOW, not WHAT',
    teaches:
      'Two completely different phrases — “eres joven todavía” and “cambia nuestro cerebro” — with near-identical length and rhythm. Energy distance is a low 0.125 and the combined score sits in the same-phrase range. A contour metric confirms how something was said; it cannot confirm what was said. It must always be paired with a content check, never asked to do word recognition.',
    caution: true,
  },
  {
    pair_id: 'diffphrase:4fbfa1b9:4c22377b',
    title: '8 · Genuinely different phrases — the far anchor',
    teaches:
      'A two-word phrase against a nine-word sentence, same voice. Every dimension is far apart and the combined score is over 6 — this is what “said a different phrase” looks like, and the reference the same-phrase pairs are judged against.',
  },
  {
    pair_id: 'human_tts_cym:89ee6e14:2db912f9',
    title: '9 · Two human Welsh voices, same phrase',
    teaches:
      'Two different human SSi voices recording the same Welsh words — not human vs TTS. Every Welsh clip in the estate is human-recorded (Welsh voice quality is deliberately picky, so there is no Welsh TTS to compare against). The contours land closer than different phrases would — a useful preview of human-to-human distance, which is closer to the eventual learner-vs-model comparison than a human-vs-TTS pair would be.',
    footnote:
      'Honest footnote: in all 12 Welsh pairs one voice is the declarative and the other the question form of the same words, so a real intonation difference rides along with the cross-voice difference. Twelve pairs, confounded — listed as anecdote, load-bearing on nothing.',
  },
  {
    pair_id: 'human_tts_eng:4f4a89a8:5cce06c8',
    title: '10 · Duration is the fragile dimension — why calibration bands are load-bearing',
    teaches:
      'A recording of “I was trying” from the old English course against a TTS render of the same words. Energy shape and syllable count still agree it is the same phrase, but the pacing gap is so large that duration alone scores it as far as a wrong phrase would be. The old recordings pace themselves very differently from modern TTS — a recording-era difference, nothing more. The lesson is about the dimension: read straight, duration punishes any natural pacing difference, which is exactly why the design calibrates variance bands per level before any dimension reaches a learner as a score.',
    caution: true,
  },
]
const tourPairs = computed(() =>
  TOUR.map((t) => ({ ...t, pair: pairById.value.get(t.pair_id) })).filter((t) => t.pair)
)

// ── the lab browser ─────────────────────────────────────────────────────────
const catFilter = ref('all')
const langFilter = ref('all')
const search = ref('')
const selectedPairId = ref('')
const alignedView = ref(true)

const CATEGORY_ORDER = ['crossvoice', 'crossprovider', 'human_tts_eng', 'human_tts_cym', 'rerender', 'diffphrase']
const labLanguages = computed(() => {
  if (!lab.value) return []
  const counts = new Map()
  for (const p of lab.value.pairs) counts.set(p.language, (counts.get(p.language) || 0) + 1)
  return [...counts.entries()].sort((a, b) => b[1] - a[1]).map(([lang, n]) => ({ lang, n }))
})
const filteredPairs = computed(() => {
  if (!lab.value) return []
  const q = search.value.trim().toLowerCase()
  return lab.value.pairs
    .filter((p) => catFilter.value === 'all' || p.category === catFilter.value)
    .filter((p) => langFilter.value === 'all' || p.language === langFilter.value)
    .filter(
      (p) =>
        !q ||
        p.text_a.toLowerCase().includes(q) ||
        (p.text_b || '').toLowerCase().includes(q) ||
        (p.a.voice || '').toLowerCase().includes(q) ||
        (p.b.voice || '').toLowerCase().includes(q) ||
        p.language.toLowerCase().includes(q) ||
        langName(p.language).toLowerCase().includes(q)
    )
    .sort(
      (x, y) =>
        CATEGORY_ORDER.indexOf(x.category) - CATEGORY_ORDER.indexOf(y.category) ||
        (x.combined ?? 99) - (y.combined ?? 99)
    )
})
const selectedPair = computed(() => pairById.value.get(selectedPairId.value) || null)

const aucTable = computed(() => {
  const dd = lab.value?.dimension_discrimination
  if (!dd) return []
  return Object.entries(dd)
    .map(([dim, s]) => ({ dim, ...s }))
    .sort((a, b) => (b.same_vs_diff_auc ?? -1) - (a.same_vs_diff_auc ?? -1))
})

// ── record yourself ─────────────────────────────────────────────────────────
// The founder records graded attempts against model clips (one voice at
// varying self-rated proficiency = controlled calibration corpus). Both sides
// are extracted by vadProsody.js — the SAME extractor, so no python/JS bias.
const recSearch = ref('')
const recModelId = ref('')
// Founder ruling 2026-07-29: the default face of this tab is widely-known
// languages the testing team can actually judge — Spanish, French, Italian,
// Chinese. Everything else (incl. Basque) stays reachable via the pills and
// search; typing a search spans ALL languages, ignoring the pill filter.
const FEATURED_LANGS = ['spa', 'fra', 'ita', 'zho']
const recLangFilter = ref('featured') // 'featured' | 'all' | <lang code>
const recLanguages = computed(() => {
  const counts = new Map()
  for (const c of clipIndex.value) counts.set(c.language, (counts.get(c.language) || 0) + 1)
  return [...counts.entries()].sort((a, b) => b[1] - a[1]).map(([lang]) => lang)
})
const clipIndex = computed(() => {
  const m = new Map()
  if (lab.value)
    for (const p of lab.value.pairs) {
      for (const [side, text] of [
        [p.a, p.text_a],
        [p.b, p.text_b || p.text_a],
      ]) {
        if (!m.has(side.id) && lab.value.contours?.[side.id])
          m.set(side.id, { id: side.id, text, language: p.language, side })
      }
    }
  return [...m.values()]
})
const recClipList = computed(() => {
  const q = recSearch.value.trim().toLowerCase()
  let list = clipIndex.value
  if (q) {
    // search spans every language — it clears the pill filter
    list = list.filter(
      (c) =>
        c.text.toLowerCase().includes(q) ||
        (c.side.voice || '').toLowerCase().includes(q) ||
        c.language.toLowerCase().includes(q) ||
        langName(c.language).toLowerCase().includes(q)
    )
  } else if (recLangFilter.value === 'featured') {
    list = list
      .filter((c) => FEATURED_LANGS.includes(c.language))
      .sort((a, b) => FEATURED_LANGS.indexOf(a.language) - FEATURED_LANGS.indexOf(b.language))
  } else if (recLangFilter.value !== 'all') {
    list = list.filter((c) => c.language === recLangFilter.value)
  }
  return list.slice(0, 60)
})
const recModel = computed(() => clipIndex.value.find((c) => c.id === recModelId.value) || null)

const recState = ref('idle') // idle | recording | processing | done | error
const recError = ref('')
const recBlob = ref(null)
const recUrl = ref('')
const recMime = ref('')
const recFeat = ref(null)
const modelFeat = ref(null)
const modelFeatCache = new Map()
const recScores = ref(null)
const recAligned = ref(true)
const recWarp = ref(null)
const recGain = ref(null) // { requestedDb, appliedDb, limited } — auto loudness match applied to playback
const recElapsed = ref(0)
let mediaRecorder = null
let mediaStream = null
let recTimer = 0

const canRecord = typeof navigator !== 'undefined' && !!navigator.mediaDevices?.getUserMedia

function stopStream() {
  mediaStream?.getTracks().forEach((t) => t.stop())
  mediaStream = null
}

function pickMime() {
  // Safari/iOS records audio/mp4 (AAC); Chrome/Firefox webm/opus
  for (const c of ['audio/mp4', 'audio/webm;codecs=opus', 'audio/webm']) {
    if (window.MediaRecorder?.isTypeSupported?.(c)) return c
  }
  return ''
}

async function startRecording() {
  if (!recModel.value) return
  recError.value = ''
  try {
    // processing off where honoured: AGC/denoise reshape the energy envelope
    mediaStream = await navigator.mediaDevices.getUserMedia({
      audio: { echoCancellation: false, noiseSuppression: false, autoGainControl: false },
    })
  } catch (e) {
    recError.value = `Microphone unavailable: ${e.message}`
    recState.value = 'error'
    return
  }
  const mime = pickMime()
  recMime.value = mime || 'audio/mp4'
  mediaRecorder = mime
    ? new MediaRecorder(mediaStream, { mimeType: mime })
    : new MediaRecorder(mediaStream)
  const chunks = []
  mediaRecorder.addEventListener('dataavailable', (e) => e.data.size && chunks.push(e.data))
  mediaRecorder.addEventListener('stop', () => {
    stopStream()
    clearInterval(recTimer)
    const blob = new Blob(chunks, { type: recMime.value })
    processRecording(blob)
  })
  mediaRecorder.start()
  recState.value = 'recording'
  recElapsed.value = 0
  recTimer = setInterval(() => (recElapsed.value += 0.1), 100)
}

function stopRecording() {
  if (mediaRecorder?.state === 'recording') mediaRecorder.stop()
}

async function ensureModelFeatures(clipId) {
  if (modelFeatCache.has(clipId)) return modelFeatCache.get(clipId)
  const res = await fetch(`${AUDIO_BASE}/${clipId}`)
  if (!res.ok) throw new Error(`model clip HTTP ${res.status}`)
  const mono = await decodeTo16kMono(await res.arrayBuffer())
  const feat = extractFeatures(mono)
  if (!feat) throw new Error('model clip failed feature extraction')
  const entry = { feat, loudnessDb: activeSpeechDb(mono) }
  modelFeatCache.set(clipId, entry)
  return entry
}

async function processRecording(blob) {
  recState.value = 'processing'
  try {
    recBlob.value = blob // raw capture — the calibration corpus saves THIS, never the gained copy
    if (recUrl.value) URL.revokeObjectURL(recUrl.value)
    recUrl.value = URL.createObjectURL(blob)
    recGain.value = null
    const rawBuf = await blob.arrayBuffer()
    const mono = await decodeTo16kMono(rawBuf)
    const mine = extractFeatures(mono)
    if (!mine) throw new Error('recording too short or silent — try again, a little louder')
    const { feat: model, loudnessDb: targetDb } = await ensureModelFeatures(recModel.value.id)
    // Loudness-match the playback copy to the model clip so A/B listening is
    // fair — a raw mic take plays much quieter than a mastered reference.
    // Auto only; a manual trim control is the fallback if the founder's ear
    // says auto isn't enough. Score/contour are level-invariant so only the
    // playback URL changes. On any failure the raw-blob URL above stands.
    const recDb = activeSpeechDb(mono)
    if (targetDb != null && recDb != null) {
      try {
        const norm = await renderLoudnessMatchedWav(rawBuf, targetDb - recDb)
        URL.revokeObjectURL(recUrl.value)
        recUrl.value = URL.createObjectURL(norm.blob)
        recGain.value = {
          requestedDb: targetDb - recDb,
          appliedDb: norm.appliedDb,
          limited: norm.limited,
        }
      } catch {
        /* raw playback fallback stands */
      }
    }
    recFeat.value = mine
    modelFeat.value = model
    recWarp.value = dtwWarp(model.energy_contour_z, mine.energy_contour_z)
    const dims = comparePhraseDims(model, mine)
    const scale = lab.value.combined_score.median_scale
    const parts = PHRASE_DIMS.map((d) => dims[d] / (scale[d] || 1))
    recScores.value = { dims, combined: parts.reduce((a, b) => a + b, 0) / parts.length }
    recState.value = 'done'
    saveState.value = ''
  } catch (e) {
    recError.value = e.message
    recState.value = 'error'
  }
}

function discardRecording() {
  recState.value = 'idle'
  recFeat.value = null
  recScores.value = null
  recWarp.value = null
  recGain.value = null
  recError.value = ''
  saveState.value = ''
}

function pickModel(id) {
  if (recModelId.value !== id) discardRecording()
  recModelId.value = id
}

const recOverlay = computed(() => {
  if (!modelFeat.value || !recFeat.value) return null
  let b = recFeat.value.energy_contour_z
  let bmap = null
  if (recAligned.value && recWarp.value) {
    b = recWarp.value.warped
    bmap = recWarp.value.bmap
  }
  return {
    a: modelFeat.value.energy_contour_z,
    b,
    bmap,
    durA: modelFeat.value.duration_s,
    durB: recFeat.value.duration_s,
    sylTA: modelFeat.value.syllable_peak_t,
    sylTB: recFeat.value.syllable_peak_t,
    f0A: modelFeat.value.f0_contour_st,
    f0B: recFeat.value.f0_contour_st,
  }
})
function recPlaySide() {
  if (playingId.value === recModelId.value) return 'a'
  if (playingId.value === 'self-recording') return 'b'
  return ''
}
const recPseudoPair = computed(() =>
  recScores.value ? { dims: recScores.value.dims, combined: recScores.value.combined } : null
)

// ── saving to the calibration corpus ───────────────────────────────────────
const recProficiency = ref('')
const recNote = ref('')
const saveState = ref('') // '' | saving | saved | error
const saveError = ref('')
const savedList = ref(null)
const PROFICIENCIES = ['native', 'C2', 'C1', 'B2', 'B1', 'A2', 'A1', 'A0/none']

const roundArr = (v, dp) => (v ? v.map((x) => Math.round(x * 10 ** dp) / 10 ** dp) : null)

function compactFeatures(f) {
  return {
    duration_s: Math.round(f.duration_s * 1000) / 1000,
    voiced_frac: Math.round(f.voiced_frac * 1000) / 1000,
    syllable_peaks: f.syllable_peaks,
    syllable_peak_t: roundArr(f.syllable_peak_t, 4),
    energy_contour_z: roundArr(f.energy_contour_z, 2),
    f0_contour_st: roundArr(f.f0_contour_st, 1),
    f0_median_hz: f.f0_median_hz ? Math.round(f.f0_median_hz * 10) / 10 : null,
    f0_range_st: f.f0_range_st ? Math.round(f.f0_range_st * 100) / 100 : null,
  }
}

async function postJson(body) {
  const res = await fetch(REC_API, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  })
  const j = await res.json().catch(() => ({}))
  if (!res.ok) throw new Error(j.error || `HTTP ${res.status}`)
  return j
}

function b64(bytes) {
  let s = ''
  for (let i = 0; i < bytes.length; i += 0x8000)
    s += String.fromCharCode.apply(null, bytes.subarray(i, i + 0x8000))
  return btoa(s)
}

async function saveRecording() {
  if (!recBlob.value || !recProficiency.value) return
  saveState.value = 'saving'
  saveError.value = ''
  try {
    const rand = Array.from(crypto.getRandomValues(new Uint8Array(4)))
      .map((x) => x.toString(16).padStart(2, '0'))
      .join('')
    const id = `r-${Date.now().toString(36)}-${rand}`
    const bytes = new Uint8Array(await recBlob.value.arrayBuffer())
    // ≤24KB raw per chunk → ~32KB base64 POST bodies, under the ~50KB HTTPS
    // upload ceiling documented for the founder's network (build-lab-data.cjs)
    const CHUNK = 24 * 1024
    const nParts = Math.ceil(bytes.length / CHUNK)
    for (let i = 0; i < nParts; i++) {
      const data = b64(bytes.subarray(i * CHUNK, (i + 1) * CHUNK))
      let attempt = 0
      for (;;) {
        try {
          await postJson({ action: 'chunk', id, index: i, data })
          break
        } catch (e) {
          if (++attempt >= 3) throw e
        }
      }
    }
    await postJson({
      action: 'finalize',
      id,
      parts: nParts,
      mime: recMime.value,
      meta: {
        model_clip_id: recModel.value.id,
        model_text: recModel.value.text,
        model_voice: recModel.value.side.voice || null,
        language: recModel.value.language,
        proficiency: recProficiency.value,
        note: recNote.value.trim() || null,
        bytes: bytes.length,
        scores: {
          energy_dtw: Math.round(recScores.value.dims.energy_dtw * 1000) / 1000,
          dur_log_ratio: Math.round(recScores.value.dims.dur_log_ratio * 1000) / 1000,
          syl_count_diff: recScores.value.dims.syl_count_diff,
          combined: Math.round(recScores.value.combined * 1000) / 1000,
        },
        features: compactFeatures(recFeat.value),
        model_features: compactFeatures(modelFeat.value),
      },
    })
    saveState.value = 'saved'
    loadSaved()
  } catch (e) {
    saveError.value = e.message
    saveState.value = 'error'
  }
}

async function deleteSaved(r) {
  if (!window.confirm(`Delete the ${r.language} “${r.model_text}” take (${r.proficiency})? This removes it from the calibration corpus.`)) return
  try {
    await postJson({ action: 'delete', id: r.id })
    savedList.value = savedList.value.filter((x) => x.id !== r.id)
  } catch (e) {
    window.alert(`Delete failed: ${e.message}`)
  }
}

async function loadSaved() {
  try {
    const res = await fetch(`${REC_API}?action=list`)
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    savedList.value = (await res.json()).recordings || []
  } catch {
    savedList.value = null // list quietly unavailable (e.g. local dev without api)
  }
}
function openRecordTab() {
  tab.value = 'record'
  if (savedList.value === null) loadSaved()
}
</script>

<template>
  <div class="vadlab">
    <nav class="admin-crumbs">
      <router-link to="/">Home</router-link><span class="sep">/</span>
      <router-link to="/admin">Admin</router-link><span class="sep">/</span>
      <router-link to="/admin/labs">Labs</router-link><span class="sep">/</span>
      <span class="cur">VAD Lab</span>
    </nav>

    <header class="lab-head">
      <h1>VAD Lab — prosody made audible</h1>
      <p class="sub">
        The invariance study, by ear: over 1,000 clips, 509 pairs across nine languages from the
        live audio estate (the 2026-07-28 study plus the 2026-07-29 language-breadth round). Across
        voices saying the <em>same</em> phrase, energy-contour shape, duration and syllable count
        stay put while melody, register and range move with the speaker — so the first three are
        the measurable core of a phrase, and the rest is the voice, which is never scored.
        Findings: <code>docs/course-optimization/prosody-lab-poc.md</code>.
      </p>
      <div class="tabs">
        <button :class="{ on: tab === 'tour' }" @click="tab = 'tour'">Listening tour</button>
        <button :class="{ on: tab === 'lab' }" @click="tab = 'lab'">Browse the lab</button>
        <button :class="{ on: tab === 'record' }" @click="openRecordTab">Record yourself</button>
        <button :class="{ on: tab === 'proves' }" @click="tab = 'proves'">What this proves</button>
      </div>
    </header>

    <div v-if="loading" class="notice">Loading study data…</div>
    <div v-else-if="loadError" class="notice err">{{ loadError }}</div>

    <!-- ═══════════ LISTENING TOUR ═══════════ -->
    <main v-else-if="tab === 'tour'" class="tour">
      <p class="tour-intro">
        Ten pairs chosen to be heard in order, across seven languages. Each teaches one thing
        the numbers alone can’t.
        Tap a phrase to hear it — the playhead sweeps the chart underneath, which is the
        loudness-shape of each clip: the stress rhythm a learner actually copies. Small ticks on
        the axis are the detected syllable beats.
      </p>

      <section v-for="t in tourPairs" :key="t.pair_id" class="tour-card" :class="{ caution: t.caution }">
        <h2>{{ t.title }}</h2>
        <p class="teaches">{{ t.teaches }}</p>

        <div class="players">
          <button
            class="clip"
            :class="{ playing: playingId === t.pair.a.id }"
            @click="play(t.pair.a.id)"
          >
            <span class="clip-icon">{{ playingId === t.pair.a.id ? '■' : '▶' }}</span>
            <span class="clip-text">“{{ t.pair.text_a }}”</span>
            <span class="clip-voice">{{ voiceLabel(t.pair.a) }}</span>
          </button>
          <button
            class="clip clip-b"
            :class="{ playing: playingId === t.pair.b.id }"
            @click="play(t.pair.b.id)"
          >
            <span class="clip-icon">{{ playingId === t.pair.b.id ? '■' : '▶' }}</span>
            <span class="clip-text">“{{ t.pair.text_b }}”</span>
            <span class="clip-voice">{{ voiceLabel(t.pair.b) }}</span>
          </button>
        </div>

        <div v-if="contourPair(t.pair, true)" class="contour">
          <VadContour
            v-bind="contourPair(t.pair, true)"
            :play-side="playSideFor(t.pair)"
            :play-frac="mappedPlayFrac"
            :show-pitch="showPitch"
          />
          <div class="legend">
            <span><i class="sw sw-a"></i>{{ voiceLabel(t.pair.a) }} · {{ fmt(contourPair(t.pair, true).durA, 2) }}s</span>
            <span><i class="sw sw-b"></i>{{ voiceLabel(t.pair.b) }} · {{ fmt(contourPair(t.pair, true).durB, 2) }}s</span>
            <span class="legend-note">energy shape, time-aligned · ticks = syllable beats</span>
          </div>
        </div>

        <div class="scores">
          <div v-for="dim in PHRASE_DIMS" :key="dim" class="score-row">
            <span class="score-label" :title="DIM_META[dim].hint">{{ DIM_META[dim].label }}</span>
            <span class="score-val">{{ fmt(t.pair.dims[dim]) }}</span>
            <div class="track" v-if="trackPos(dim, t.pair.dims[dim])">
              <div class="tick tick-near" :style="{ left: trackPos(dim, t.pair.dims[dim]).near + '%' }" title="re-render median (noise floor)"></div>
              <div class="tick tick-far" :style="{ left: trackPos(dim, t.pair.dims[dim]).far + '%' }" title="different-phrase median"></div>
              <div class="dot" :style="{ left: trackPos(dim, t.pair.dims[dim]).v + '%' }"></div>
            </div>
          </div>
          <div class="score-row combined-row">
            <span class="score-label">Combined phrase-identity score</span>
            <span class="score-val">{{ fmt(t.pair.combined, 2) }}</span>
            <span class="verdict" :class="combinedVerdict(t.pair).cls">{{ combinedVerdict(t.pair).text }}</span>
          </div>
        </div>

        <p v-if="t.footnote" class="footnote">{{ t.footnote }}</p>
      </section>

      <p class="track-key">
        Score tracks: <i class="tick-demo tick-near"></i> re-render median — the metric’s noise
        floor — and <i class="tick-demo tick-far"></i> different-phrase median — the far anchor.
        A dot near the left tick means “indistinguishable from the same recording”; near the
        right tick, “as far apart as two different phrases”.
      </p>
    </main>

    <!-- ═══════════ THE LAB ═══════════ -->
    <main v-else-if="tab === 'lab'" class="labmain">
      <div class="filters">
        <button :class="{ on: catFilter === 'all' }" @click="catFilter = 'all'">
          All ({{ lab.pairs.length }})
        </button>
        <button
          v-for="c in CATEGORY_ORDER"
          :key="c"
          :class="{ on: catFilter === c }"
          @click="catFilter = c"
        >
          {{ catMeta(c).label }} ({{ lab.pairs.filter((p) => p.category === c).length }})
        </button>
        <input v-model="search" class="search" type="search" placeholder="search text, voice or language…" />
      </div>
      <div class="filters lang-filters">
        <button :class="{ on: langFilter === 'all' }" @click="langFilter = 'all'">All languages</button>
        <button
          v-for="l in labLanguages"
          :key="l.lang"
          :class="{ on: langFilter === l.lang }"
          @click="langFilter = l.lang"
        >
          {{ langName(l.lang) }} ({{ l.n }})
        </button>
      </div>

      <div class="lab-split">
        <div class="pair-list">
          <button
            v-for="p in filteredPairs"
            :key="p.pair_id"
            class="pair-row"
            :class="{ sel: p.pair_id === selectedPairId }"
            @click="selectedPairId = p.pair_id"
          >
            <span class="pr-cat">{{ catMeta(p.category).short }}</span>
            <span class="pr-text bidi-isolate" :dir="dirFor(p.text_a)">
              “{{ p.text_a }}”<template v-if="p.category === 'diffphrase'"> · “{{ p.text_b }}”</template>
            </span>
            <span class="pr-score" :class="combinedVerdict(p).cls">{{ fmt(p.combined, 2) }}</span>
          </button>
          <p v-if="!filteredPairs.length" class="notice">No pairs match.</p>
        </div>

        <div class="pair-detail" v-if="selectedPair">
          <h3>{{ catMeta(selectedPair.category).label }} <span class="lang">· {{ selectedPair.language }}</span></h3>
          <p v-if="selectedPair.same_bytes" class="footnote">
            Flagged <code>same_bytes</code>: the two s3 keys hold byte-identical audio — excluded
            from the study’s noise floor.
          </p>

          <div class="players">
            <button class="clip" :class="{ playing: playingId === selectedPair.a.id }" @click="play(selectedPair.a.id)">
              <span class="clip-icon">{{ playingId === selectedPair.a.id ? '■' : '▶' }}</span>
              <span class="clip-text">“{{ selectedPair.text_a }}”</span>
              <span class="clip-voice">{{ voiceLabel(selectedPair.a) }}</span>
            </button>
            <button class="clip clip-b" :class="{ playing: playingId === selectedPair.b.id }" @click="play(selectedPair.b.id)">
              <span class="clip-icon">{{ playingId === selectedPair.b.id ? '■' : '▶' }}</span>
              <span class="clip-text">“{{ selectedPair.text_b }}”</span>
              <span class="clip-voice">{{ voiceLabel(selectedPair.b) }}</span>
            </button>
          </div>

          <div v-if="cleanFor(selectedPair.a.id) || cleanFor(selectedPair.b.id)" class="clean-ab">
            <h4>Clean master A/B <span class="h4-note">— the hiss fix, by ear</span></h4>
            <div v-for="side in [selectedPair.a, selectedPair.b].filter((s) => cleanFor(s.id))" :key="'clean-' + side.id" class="clean-row">
              <span class="clean-voice">{{ voiceLabel(side) }}</span>
              <button class="align-toggle" @click="play(side.id)">
                {{ playingId === side.id ? '■' : '▶' }} original master
              </button>
              <button class="align-toggle" @click="play('clean:' + side.id, cleanSrc(side.id))">
                {{ playingId === 'clean:' + side.id ? '■' : '▶' }} clean master
                <template v-if="cleanFor(side.id).output_lufs"> · {{ cleanFor(side.id).output_lufs }} LUFS</template>
              </button>
            </div>
            <p class="footnote">
              The clean copy is a fresh xAI render mastered without the compressor stage that
              lifts the clone’s noise floor — a new take of the same phrase by the same voice.
              Listen for the noise floor between words, not the exact delivery: the contour and
              scores above still describe the original master.
            </p>
          </div>

          <div v-if="contourPair(selectedPair, alignedView)" class="contour">
            <VadContour
              v-bind="contourPair(selectedPair, alignedView)"
              :play-side="playSideFor(selectedPair)"
              :play-frac="mappedPlayFrac"
              :show-pitch="showPitch"
            />
            <div class="legend">
              <span><i class="sw sw-a"></i>{{ voiceLabel(selectedPair.a) }} · {{ fmt(contourPair(selectedPair, alignedView).durA, 2) }}s</span>
              <span><i class="sw sw-b"></i>{{ voiceLabel(selectedPair.b) }} · {{ fmt(contourPair(selectedPair, alignedView).durB, 2) }}s</span>
              <button class="align-toggle" @click="showPitch = !showPitch">
                {{ showPitch ? 'hide' : 'show' }} pitch track
              </button>
              <button class="align-toggle" @click="alignedView = !alignedView">
                {{ alignedView ? 'time-aligned (DTW) — show raw' : 'raw shape — show aligned' }}
              </button>
            </div>
          </div>
          <p v-else class="notice">No contour for this pair — one clip failed feature extraction.</p>

          <h4>Phrase-carrying dimensions <span class="h4-note">— what a learner would be measured on</span></h4>
          <div class="scores">
            <div v-for="dim in PHRASE_DIMS" :key="dim" class="score-row">
              <span class="score-label" :title="DIM_META[dim].hint">{{ DIM_META[dim].label }}</span>
              <span class="score-val">{{ fmt(selectedPair.dims[dim]) }}</span>
              <div class="track" v-if="trackPos(dim, selectedPair.dims[dim])">
                <div class="tick tick-near" :style="{ left: trackPos(dim, selectedPair.dims[dim]).near + '%' }"></div>
                <div class="tick tick-far" :style="{ left: trackPos(dim, selectedPair.dims[dim]).far + '%' }"></div>
                <div class="dot" :style="{ left: trackPos(dim, selectedPair.dims[dim]).v + '%' }"></div>
              </div>
            </div>
            <div class="score-row combined-row">
              <span class="score-label">Combined phrase-identity score</span>
              <span class="score-val">{{ fmt(selectedPair.combined, 2) }}</span>
              <span class="verdict" :class="combinedVerdict(selectedPair).cls">{{ combinedVerdict(selectedPair).text }}</span>
            </div>
          </div>

          <h4>Voice-dominated dimensions <span class="h4-note">— shown for honesty, never scored</span></h4>
          <div class="scores muted-scores">
            <div v-for="dim in ['f0_dtw', 'f0_range_diff_st', 'f0_register_gap_st', 'voiced_frac_diff', 'syl_rate_diff']" :key="dim" class="score-row">
              <span class="score-label" :title="DIM_META[dim].hint">{{ DIM_META[dim].label }}</span>
              <span class="score-val">{{ fmt(selectedPair.dims[dim]) }}</span>
              <span class="dim-hint">{{ DIM_META[dim].hint }}</span>
            </div>
          </div>
        </div>
        <div class="pair-detail empty" v-else>
          <p class="notice">Pick a pair on the left — players, contour overlay and every dimension appear here.</p>
        </div>
      </div>

      <section class="auc-section">
        <h3>The dimension table — what survives a change of voice</h3>
        <p class="sub">
          <strong>AUC</strong>: the probability the dimension still recognises “same phrase” through
          a voice change — above 0.5 it tracks the phrase; below 0.5 two voices saying the
          <em>same</em> phrase are further apart than one voice saying two <em>different</em>
          phrases, which is the definition of measuring the speaker.
          <strong>vsens</strong>: how far a voice change moves the dimension, as a fraction of a
          phrase change.
        </p>
        <table class="auc-table">
          <thead>
            <tr><th>Dimension</th><th>near (re-render)</th><th>cross (new voice)</th><th>far (diff phrase)</th><th>vsens</th><th>AUC</th><th></th></tr>
          </thead>
          <tbody>
            <tr v-for="row in aucTable" :key="row.dim" :class="{ carrier: PHRASE_DIMS.includes(row.dim), degenerate: row.dim === 'pause_diff' }">
              <td>{{ DIM_META[row.dim]?.label || row.dim }}</td>
              <td>{{ fmt(row.near_p50) }}</td>
              <td>{{ fmt(row.cross_p50) }}</td>
              <td>{{ fmt(row.far_p50) }}</td>
              <td>{{ fmt(row.voice_sensitivity, 2) }}</td>
              <td>{{ fmt(row.same_vs_diff_auc, 3) }}</td>
              <td class="tag-cell">
                <span v-if="row.dim === 'pause_diff'" class="tag t-na">degenerate at this phrase length</span>
                <span v-else-if="PHRASE_DIMS.includes(row.dim)" class="tag t-carrier">phrase carrier</span>
                <span v-else class="tag t-voice">voice — never scored</span>
              </td>
            </tr>
          </tbody>
        </table>
      </section>
    </main>

    <!-- ═══════════ RECORD YOURSELF ═══════════ -->
    <main v-else-if="tab === 'record'" class="recmain">
      <p class="tour-intro">
        Record an attempt against any model clip. Both sides go through the <em>same</em>
        extractor, in this browser, and you get the overlay plus the three phrase-carrying
        scores immediately. Save recordings with a language + self-rated proficiency tag —
        they become the calibration corpus for the variance-band work. Private admin tool.
      </p>
      <p v-if="!canRecord" class="notice err">
        This browser exposes no microphone API — recording needs HTTPS and mic permission.
      </p>

      <div class="rec-split">
        <div class="rec-pick">
          <div class="filters rec-lang-filters">
            <button :class="{ on: recLangFilter === 'featured' && !recSearch.trim() }" @click="recLangFilter = 'featured'; recSearch = ''">
              Featured
            </button>
            <button
              v-for="l in FEATURED_LANGS.filter((f) => recLanguages.includes(f))"
              :key="l"
              :class="{ on: recLangFilter === l && !recSearch.trim() }"
              @click="recLangFilter = l; recSearch = ''"
            >
              {{ langName(l) }}
            </button>
            <button
              v-for="l in recLanguages.filter((x) => !FEATURED_LANGS.includes(x))"
              :key="l"
              :class="{ on: recLangFilter === l && !recSearch.trim() }"
              @click="recLangFilter = l; recSearch = ''"
            >
              {{ langName(l) }}
            </button>
            <button :class="{ on: recLangFilter === 'all' && !recSearch.trim() }" @click="recLangFilter = 'all'; recSearch = ''">
              All
            </button>
          </div>
          <input
            v-model="recSearch"
            class="search rec-search"
            type="search"
            placeholder="search all model clips — text, voice or language…"
          />
          <div class="pair-list rec-list">
            <button
              v-for="c in recClipList"
              :key="c.id"
              class="pair-row"
              :class="{ sel: c.id === recModelId }"
              @click="pickModel(c.id)"
            >
              <span class="pr-cat">{{ c.language }}</span>
              <span class="pr-text bidi-isolate" :dir="dirFor(c.text)">“{{ c.text }}”</span>
              <span class="pr-score">{{ voiceLabel(c.side) }}</span>
            </button>
            <p v-if="!recClipList.length" class="notice">No clips match.</p>
          </div>
        </div>

        <div class="pair-detail rec-detail">
          <template v-if="recModel">
            <h3><span class="bidi-isolate" :dir="dirFor(recModel.text)">“{{ recModel.text }}”</span> <span class="lang">· {{ recModel.language }} · {{ voiceLabel(recModel.side) }}</span></h3>

            <div class="players">
              <button class="clip" :class="{ playing: playingId === recModel.id }" @click="play(recModel.id)">
                <span class="clip-icon">{{ playingId === recModel.id ? '■' : '▶' }}</span>
                <span class="clip-text">Model clip</span>
                <span class="clip-voice">{{ voiceLabel(recModel.side) }}</span>
              </button>
              <button
                v-if="recUrl && (recState === 'done' || recState === 'processing')"
                class="clip clip-b"
                :class="{ playing: playingId === 'self-recording' }"
                @click="play('self-recording', recUrl)"
              >
                <span class="clip-icon">{{ playingId === 'self-recording' ? '■' : '▶' }}</span>
                <span class="clip-text">Your attempt</span>
                <span class="clip-voice">
                  {{ recFeat ? fmt(recFeat.duration_s, 2) + 's' : '' }}
                  <template v-if="recGain">
                    · level {{ recGain.appliedDb >= 0 ? '+' : '' }}{{ fmt(recGain.appliedDb, 1) }} dB{{
                      recGain.limited ? ' (peak-limited)' : ''
                    }}
                  </template>
                </span>
              </button>
            </div>

            <div class="rec-controls">
              <button
                v-if="recState === 'idle' || recState === 'error' || recState === 'done'"
                class="rec-btn"
                :disabled="!canRecord"
                @click="startRecording"
              >
                ● {{ recState === 'done' ? 'Record again' : 'Record your attempt' }}
              </button>
              <button v-if="recState === 'recording'" class="rec-btn recording" @click="stopRecording">
                ■ Stop ({{ recElapsed.toFixed(1) }}s)
              </button>
              <span v-if="recState === 'processing'" class="notice">Extracting features…</span>
              <span v-if="recState === 'error'" class="notice err">{{ recError }}</span>
            </div>

            <template v-if="recState === 'done' && recOverlay">
              <div class="contour">
                <VadContour
                  v-bind="recOverlay"
                  :play-side="recPlaySide()"
                  :play-frac="mappedPlayFrac"
                  :show-pitch="showPitch"
                />
                <div class="legend">
                  <span><i class="sw sw-a"></i>model · {{ fmt(recOverlay.durA, 2) }}s</span>
                  <span><i class="sw sw-b"></i>you · {{ fmt(recOverlay.durB, 2) }}s</span>
                  <button class="align-toggle" @click="showPitch = !showPitch">
                    {{ showPitch ? 'hide' : 'show' }} pitch track
                  </button>
                  <button class="align-toggle" @click="recAligned = !recAligned">
                    {{ recAligned ? 'time-aligned (DTW) — show raw' : 'raw shape — show aligned' }}
                  </button>
                </div>
              </div>

              <div class="scores">
                <div v-for="dim in PHRASE_DIMS" :key="dim" class="score-row">
                  <span class="score-label" :title="DIM_META[dim].hint">{{ DIM_META[dim].label }}</span>
                  <span class="score-val">{{ fmt(recPseudoPair.dims[dim]) }}</span>
                  <div class="track" v-if="trackPos(dim, recPseudoPair.dims[dim])">
                    <div class="tick tick-near" :style="{ left: trackPos(dim, recPseudoPair.dims[dim]).near + '%' }"></div>
                    <div class="tick tick-far" :style="{ left: trackPos(dim, recPseudoPair.dims[dim]).far + '%' }"></div>
                    <div class="dot" :style="{ left: trackPos(dim, recPseudoPair.dims[dim]).v + '%' }"></div>
                  </div>
                </div>
                <div class="score-row combined-row">
                  <span class="score-label">Combined phrase-identity score</span>
                  <span class="score-val">{{ fmt(recPseudoPair.combined, 2) }}</span>
                  <span class="verdict" :class="combinedVerdict(recPseudoPair).cls">{{ combinedVerdict(recPseudoPair).text }}</span>
                </div>
              </div>
              <p class="rec-band-note">
                Raw distances against uncalibrated anchors — the study says a residual
                not-being-the-model-voice cost is baked in, and duration reads any pacing
                difference as distance. That is what this corpus exists to calibrate out.
              </p>

              <div class="rec-save">
                <label>
                  Self-rated proficiency
                  <select v-model="recProficiency">
                    <option value="" disabled>choose…</option>
                    <option v-for="p in PROFICIENCIES" :key="p" :value="p">{{ p }}</option>
                  </select>
                </label>
                <input v-model="recNote" class="search" type="text" placeholder="note (optional)" />
                <button
                  class="rec-btn save"
                  :disabled="!recProficiency || saveState === 'saving' || saveState === 'saved'"
                  @click="saveRecording"
                >
                  {{ saveState === 'saving' ? 'Saving…' : saveState === 'saved' ? 'Saved ✓' : 'Save to calibration corpus' }}
                </button>
                <button class="align-toggle" @click="discardRecording">discard</button>
              </div>
              <p v-if="saveState === 'error'" class="notice err">Save failed: {{ saveError }} — the recording is still here; try again.</p>
            </template>
          </template>
          <p v-else class="notice">Pick a model clip on the left, listen to it, then record your attempt.</p>
        </div>
      </div>

      <section v-if="savedList && savedList.length" class="rec-saved">
        <h3>Calibration corpus — {{ savedList.length }} recording{{ savedList.length === 1 ? '' : 's' }}</h3>
        <table class="auc-table">
          <thead>
            <tr><th></th><th>When</th><th>Phrase</th><th>Lang</th><th>Proficiency</th><th>energy</th><th>dur</th><th>sylΔ</th><th>combined</th><th>Note</th><th></th></tr>
          </thead>
          <tbody>
            <tr v-for="r in savedList" :key="r.id">
              <td>
                <button class="align-toggle" @click="play('saved:' + r.id, `${REC_API}?action=audio&id=${r.id}`)">
                  {{ playingId === 'saved:' + r.id ? '■' : '▶' }}
                </button>
              </td>
              <td>{{ (r.created || '').slice(0, 16).replace('T', ' ') }}</td>
              <td class="rec-saved-text">“{{ r.model_text }}”</td>
              <td>{{ r.language }}</td>
              <td>{{ r.proficiency }}</td>
              <td>{{ fmt(r.scores?.energy_dtw) }}</td>
              <td>{{ fmt(r.scores?.dur_log_ratio) }}</td>
              <td>{{ fmt(r.scores?.syl_count_diff) }}</td>
              <td>{{ fmt(r.scores?.combined, 2) }}</td>
              <td class="rec-saved-text">{{ r.note || '' }}</td>
              <td><button class="align-toggle" title="delete this take" @click="deleteSaved(r)">✕</button></td>
            </tr>
          </tbody>
        </table>
      </section>
    </main>

    <!-- ═══════════ WHAT THIS PROVES ═══════════ -->
    <main v-else class="proves">
      <section class="prove-card can">
        <h2>What the metric can do</h2>
        <p>
          Recognise that the <em>same phrase</em> was said, through a change of speaker, using no
          timbre information at all. Energy-contour shape alone separates same-phrase-new-voice
          from different-phrase at AUC 0.845; combined with duration and syllable count, 0.813.
          The category ordering largely matches the physical story: same render &lt; new voice
          &lt; new provider &lt; cross-human (Welsh) &lt; different phrase &lt; the old-course
          English recordings vs TTS — that last flip is a pacing artefact of those recordings'
          era, not a fact about humans versus TTS; see the tour and findings doc.
        </p>
      </section>
      <section class="prove-card cannot">
        <h2>What it cannot do</h2>
        <p>
          It cannot recognise <em>words</em> — the deceptive pair in the tour scores two different
          phrases as rhythmically near-identical, so it must always be paired with a content
          check. And it must not score <em>melody</em>: even with the speaker’s register
          normalised out, the residual F0 shape still tracks the voice, not the phrase — AUC
          0.464, chance. On this evidence, scoring a learner’s pitch contour is scoring their
          larynx. Melody is voice; voice is identity; identity is never graded. (The pitch track
          in the contour view is a display-only experiment for exactly this reason.)
        </p>
      </section>
      <section class="prove-card next">
        <h2>What comes next</h2>
        <p>
          A residual voice-sensitivity remains — a learner scored raw would pay a small penalty
          just for not being the model voice — and duration reads <em>any</em> natural pacing
          difference as distance (tour card 6). So the next step is calibration: recordings of
          real speakers at known levels set variance bands per level, so the score reads
          “within the band for your stage”, not “identical to the machine”. The Record-yourself
          tab exists to build exactly that corpus. Calibration is not polish; it is what makes
          the residual honest. The scoring unit is the <em>utterance</em>, never the phoneme —
          understandability needs enough contiguous signal (~10 syllables) for the listener's
          predictive reconstruction (founder ruling, in the findings doc).
        </p>
      </section>
      <section class="prove-card policy">
        <h2>Voice-sourcing policy</h2>
        <p>
          Context for the human/TTS categories above: all future course voices are TTS, except
          where quality demands otherwise — Welsh (deliberately picky about quality, human-voiced),
          Breton (no TTS exists for it), and any language where Azure — the most comprehensive TTS
          provider available; if Azure doesn't have a suitable voice, one likely doesn't exist —
          has no suitable voice. That's why the Welsh category above is cross-human rather than
          human-vs-TTS: it isn't a gap to close, it's the policy working as intended.
        </p>
      </section>
      <p class="prove-src">
        Study: 774 clips, 388 pairs, 2026-07-28; language-breadth extension to 509 pairs /
        1,016 clips across nine languages, 2026-07-29 (anchors unchanged — new pairs score on
        the study’s fixed scale) · methods and full results in
        <code>docs/course-optimization/prosody-lab-poc.md</code> · re-runnable via
        <code>tools/prosody-lab/run-study.sh</code> · theory:
        <code>ssi-learning-app/docs/vad-feedback-design.md</code>.
      </p>
    </main>
  </div>
</template>

<style scoped>
/* The clip text binds `dir`; the row it sits in does not move. */
.pr-text { text-align: left; }

.vadlab {
  max-width: 1180px;
  margin: 0 auto;
  padding: 20px 22px 60px;
  color: var(--color-paper, var(--ink));
}
.admin-crumbs { font-size: 0.8125rem; margin-bottom: 10px; }
.admin-crumbs a { color: var(--accent-2); text-decoration: none; }
.admin-crumbs a:hover { color: #6ee7b7; }
.admin-crumbs .sep { margin: 0 6px; color: var(--surface-3); }
.admin-crumbs .cur { color: var(--muted); }
.lab-head h1 { margin: 0 0 6px; font-size: 1.25rem; letter-spacing: -0.01em; }
.lab-head .sub { margin: 0 0 14px; max-width: 820px; color: var(--muted); font-size: 0.875rem; line-height: 1.5; }
code { background: var(--surface-2); padding: 1px 5px; border-radius: 4px; font-size: 0.9em; font-family: var(--font-mono, ui-monospace, Menlo, monospace); }

.tabs { display: flex; gap: 8px; margin-bottom: 18px; flex-wrap: wrap; }
.tabs button {
  background: var(--surface-2); color: var(--muted); border: 1px solid var(--surface-3);
  border-radius: 8px; padding: 7px 14px; font-size: 0.875rem; cursor: pointer;
}
.tabs button.on { background: rgba(59, 130, 246, 0.15); border-color: #3b82f6; color: var(--color-paper, var(--ink)); }

.notice { color: var(--muted); font-size: 0.875rem; padding: 12px 0; }
.notice.err { color: var(--danger); }

/* ── tour ── */
.tour-intro { max-width: 820px; color: var(--muted); font-size: 0.875rem; line-height: 1.5; margin: 0 0 18px; }
.tour-card {
  background: var(--surface-1, rgba(255, 255, 255, 0.03));
  border: 1px solid var(--surface-3);
  border-radius: 12px; padding: 18px 20px; margin-bottom: 18px;
}
.tour-card.caution { border-color: rgba(251, 146, 60, 0.4); }
.tour-card h2 { margin: 0 0 8px; font-size: 1rem; }
.teaches { margin: 0 0 14px; max-width: 780px; color: var(--muted); font-size: 0.875rem; line-height: 1.55; }
.footnote { margin: 12px 0 0; font-size: 0.8125rem; color: #fbbf24; background: rgba(251, 146, 60, 0.1); border: 1px solid rgba(251, 146, 60, 0.25); border-radius: 8px; padding: 8px 12px; max-width: 780px; line-height: 1.5; }
[data-theme='light'] .footnote { color: #92400e; }

/* players */
.players { display: flex; gap: 10px; flex-wrap: wrap; margin-bottom: 12px; }
.clip {
  flex: 1 1 260px; display: flex; align-items: center; gap: 10px; text-align: left;
  background: var(--surface-2); border: 1px solid var(--surface-3); border-radius: 10px;
  padding: 10px 14px; cursor: pointer; color: inherit; min-height: 52px;
}
.clip:hover { border-color: #3987e5; }
.clip.playing { border-color: #3987e5; background: rgba(57, 135, 229, 0.12); }
.clip-b:hover, .clip-b.playing { border-color: #d95926; background: rgba(217, 89, 38, 0.1); }
.clip-icon { font-size: 0.8rem; width: 1.2em; color: #3987e5; }
.clip-b .clip-icon { color: #d95926; }
.clip-text { font-size: 0.9rem; flex: 1; }
.clip-voice { font-size: 0.75rem; color: var(--muted); white-space: nowrap; }

/* contour chart */
.contour { margin: 4px 0 12px; }
.legend { display: flex; gap: 16px; align-items: center; flex-wrap: wrap; font-size: 0.75rem; color: var(--muted); margin-top: 6px; }
.sw { display: inline-block; width: 14px; height: 3px; border-radius: 2px; margin-right: 5px; vertical-align: middle; }
.sw-a { background: #3987e5; }
.sw-b { background: #d95926; }
.legend-note { margin-left: auto; font-style: italic; }
.align-toggle { background: none; border: 1px solid var(--surface-3); border-radius: 6px; color: var(--muted); font-size: 0.75rem; padding: 3px 8px; cursor: pointer; }
.align-toggle:hover { border-color: #3987e5; color: inherit; }
.legend .align-toggle:first-of-type { margin-left: auto; }

/* score rows */
.scores { display: flex; flex-direction: column; gap: 7px; max-width: 780px; }
.score-row { display: grid; grid-template-columns: 200px 64px 1fr; gap: 12px; align-items: center; font-size: 0.8125rem; }
.score-label { color: var(--muted); }
.score-val { font-family: var(--font-mono, ui-monospace, Menlo, monospace); text-align: right; }
.track { position: relative; height: 8px; background: var(--surface-2); border-radius: 4px; }
.tick { position: absolute; top: -2px; width: 2px; height: 12px; border-radius: 1px; }
.tick-near { background: #6ee7b7; }
.tick-far { background: var(--danger); }
.dot { position: absolute; top: 50%; width: 10px; height: 10px; border-radius: 50%; background: var(--color-paper, #fff); border: 2px solid #3987e5; transform: translate(-50%, -50%); }
.combined-row { border-top: 1px solid var(--surface-3); padding-top: 8px; margin-top: 4px; }
.verdict { font-size: 0.75rem; padding: 2px 8px; border-radius: 999px; justify-self: start; }
.v-same { background: rgba(110, 231, 183, 0.15); color: #6ee7b7; }
.v-mid { background: rgba(251, 191, 36, 0.15); color: #fbbf24; }
.v-diff { background: rgba(248, 113, 113, 0.15); color: var(--danger); }
[data-theme='light'] .v-same { color: #047857; }
[data-theme='light'] .v-mid { color: #92400e; }
[data-theme='light'] .v-diff { color: #b91c1c; }
.track-key { font-size: 0.8125rem; color: var(--muted); max-width: 780px; line-height: 1.6; }
.tick-demo { display: inline-block; width: 2px; height: 11px; border-radius: 1px; vertical-align: middle; margin: 0 3px; }

/* ── lab browser ── */
.filters { display: flex; gap: 8px; flex-wrap: wrap; align-items: center; margin-bottom: 14px; }
.filters button { background: var(--surface-2); color: var(--muted); border: 1px solid var(--surface-3); border-radius: 999px; padding: 5px 12px; font-size: 0.8125rem; cursor: pointer; }
.filters button.on { background: rgba(59, 130, 246, 0.15); border-color: #3b82f6; color: var(--color-paper, var(--ink)); }
.search { background: var(--surface-2); border: 1px solid var(--surface-3); border-radius: 8px; padding: 6px 10px; font-size: 0.8125rem; color: inherit; min-width: 200px; }
.filters .search { margin-left: auto; }
.lab-split { display: grid; grid-template-columns: minmax(280px, 380px) 1fr; gap: 18px; align-items: start; }
@media (max-width: 900px) { .lab-split { grid-template-columns: 1fr; } }
.pair-list { max-height: 640px; overflow-y: auto; border: 1px solid var(--surface-3); border-radius: 10px; }
.pair-row { display: grid; grid-template-columns: 92px 1fr 48px; gap: 8px; align-items: center; width: 100%; text-align: left; background: none; border: none; border-bottom: 1px solid var(--surface-3); padding: 8px 10px; cursor: pointer; color: inherit; font-size: 0.8125rem; }
.pair-row:hover { background: var(--surface-2); }
.pair-row.sel { background: rgba(59, 130, 246, 0.12); }
.pr-cat { font-size: 0.65rem; letter-spacing: 0.04em; color: var(--muted); }
.pr-text { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.pr-score { font-family: var(--font-mono, ui-monospace, Menlo, monospace); font-size: 0.75rem; text-align: right; border-radius: 4px; padding: 1px 4px; }
.pair-detail { background: var(--surface-1, rgba(255, 255, 255, 0.03)); border: 1px solid var(--surface-3); border-radius: 12px; padding: 16px 18px; }
.pair-detail.empty { display: flex; align-items: center; justify-content: center; min-height: 200px; }
.pair-detail h3 { margin: 0 0 10px; font-size: 0.95rem; }
.pair-detail .lang { color: var(--muted); font-weight: normal; font-size: 0.8125rem; }
.pair-detail h4 { margin: 18px 0 8px; font-size: 0.8125rem; letter-spacing: 0.02em; }
.h4-note { color: var(--muted); font-weight: normal; }
.muted-scores .score-row { grid-template-columns: 200px 64px 1fr; opacity: 0.75; }
.dim-hint { font-size: 0.75rem; color: var(--muted); font-style: italic; }

/* clean-master A/B */
.clean-ab { margin: 4px 0 12px; }
.clean-ab h4 { margin: 10px 0 8px; }
.clean-row { display: flex; gap: 10px; align-items: center; margin-bottom: 6px; flex-wrap: wrap; }
.clean-voice { font-size: 0.8125rem; color: var(--muted); min-width: 160px; }

/* ── record yourself ── */
.rec-split { display: grid; grid-template-columns: minmax(260px, 360px) 1fr; gap: 18px; align-items: start; }
.rec-lang-filters { margin-bottom: 8px; }
.lang-filters { margin-top: -6px; }
@media (max-width: 900px) { .rec-split { grid-template-columns: 1fr; } }
.rec-search { width: 100%; margin-bottom: 10px; box-sizing: border-box; }
.rec-list { max-height: 560px; }
.rec-list .pair-row { grid-template-columns: 34px 1fr auto; }
.rec-list .pr-score { font-family: inherit; color: var(--muted); }
.rec-controls { display: flex; gap: 12px; align-items: center; margin: 6px 0 14px; flex-wrap: wrap; }
.rec-btn {
  background: rgba(217, 89, 38, 0.12); color: inherit; border: 1px solid #d95926;
  border-radius: 10px; padding: 10px 18px; font-size: 0.9rem; cursor: pointer; min-height: 48px;
}
.rec-btn:disabled { opacity: 0.5; cursor: default; }
.rec-btn.recording { background: rgba(248, 113, 113, 0.2); border-color: var(--danger); animation: recpulse 1.2s infinite; }
.rec-btn.save { background: rgba(110, 231, 183, 0.12); border-color: #6ee7b7; }
@keyframes recpulse { 50% { opacity: 0.6; } }
.rec-band-note { max-width: 780px; font-size: 0.8125rem; color: var(--muted); font-style: italic; line-height: 1.5; }
.rec-save { display: flex; gap: 12px; align-items: center; flex-wrap: wrap; margin-top: 12px; }
.rec-save label { display: flex; gap: 8px; align-items: center; font-size: 0.8125rem; color: var(--muted); }
.rec-save select { background: var(--surface-2); border: 1px solid var(--surface-3); border-radius: 8px; padding: 6px 10px; color: inherit; font-size: 0.8125rem; }
.rec-saved { margin-top: 26px; }
.rec-saved h3 { font-size: 1rem; margin: 0 0 10px; }
.rec-saved-text { max-width: 220px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }

/* AUC table */
.auc-section { margin-top: 26px; }
.auc-section h3 { font-size: 1rem; margin: 0 0 6px; }
.auc-section .sub { max-width: 820px; color: var(--muted); font-size: 0.8125rem; line-height: 1.55; margin: 0 0 12px; }
.auc-table { border-collapse: collapse; font-size: 0.8125rem; width: 100%; max-width: 900px; }
.auc-table th { text-align: left; color: var(--muted); font-weight: 500; padding: 6px 10px; border-bottom: 1px solid var(--surface-3); }
.auc-table td { padding: 6px 10px; border-bottom: 1px solid var(--surface-2); font-family: var(--font-mono, ui-monospace, Menlo, monospace); }
.auc-table td:first-child { font-family: inherit; }
.auc-table tr.carrier td { color: #6ee7b7; }
[data-theme='light'] .auc-table tr.carrier td { color: #047857; }
.auc-table tr.degenerate td { opacity: 0.5; }
.tag { font-size: 0.6875rem; padding: 2px 8px; border-radius: 999px; font-family: inherit; white-space: nowrap; }
.t-carrier { background: rgba(110, 231, 183, 0.15); color: #6ee7b7; }
.t-voice { background: rgba(148, 163, 184, 0.15); color: var(--muted); }
.t-na { background: rgba(148, 163, 184, 0.1); color: var(--muted); font-style: italic; }
[data-theme='light'] .t-carrier { color: #047857; }

/* ── proves ── */
.proves { display: flex; flex-direction: column; gap: 16px; max-width: 820px; }
.prove-card { border-radius: 12px; padding: 18px 20px; border: 1px solid var(--surface-3); background: var(--surface-1, rgba(255, 255, 255, 0.03)); }
.prove-card h2 { margin: 0 0 8px; font-size: 1rem; }
.prove-card p { margin: 0; font-size: 0.9rem; line-height: 1.6; color: var(--muted); }
.prove-card.can { border-color: rgba(110, 231, 183, 0.35); }
.prove-card.cannot { border-color: rgba(248, 113, 113, 0.35); }
.prove-card.next { border-color: rgba(59, 130, 246, 0.35); }
.prove-src { font-size: 0.8125rem; color: var(--muted); line-height: 1.6; }
</style>
