const fs = require('fs');
const batches = JSON.parse(fs.readFileSync('/tmp/deu_sonnet_batches.json', 'utf8'));

// Generate prompt for each batch
const prompts = batches.map((batch, batchIdx) => {
  // Get unique vocab per seed
  const vocabBySeed = {};
  batch.forEach(l => {
    if (!vocabBySeed[l.seed_number]) vocabBySeed[l.seed_number] = l.vocab;
  });

  let p = `You generate German BUILD and USE phrases for the SSi course deu_for_eng and submit them via API.

## CRITICAL RULE — CONTAINMENT (READ THIS CAREFULLY)
Every BUILD and USE phrase's TARGET text must contain the FULL LEGO target text as an exact substring.

Example for M-LEGO target "ich mache gern":
  VALID:   target = "ich mache gern Deutsch sprechen" (contains "ich mache gern")
  VALID:   target = "ich mache gern etwas mit dir"    (contains "ich mache gern")
  INVALID: target = "ich mache das gern"              (words rearranged — not a substring match)
  INVALID: target = "mache gern lernen"               (missing "ich" — not a substring match)

Example for A-LEGO target "geben":
  VALID:   target = "ich will dir etwas geben"        (contains "geben")
  VALID:   target = "du musst mir das Buch geben"     (contains "geben")

The API will REJECT any phrase where the target doesn't contain the LEGO target as a substring.

## REQUIREMENTS
- BUILD: minimum 3 phrases per LEGO (short sentences)
- USE: minimum 8 phrases per LEGO (longer sentences, 10+ words)
- Aim for 5 BUILD and 12 USE per LEGO
- Every word in the German target MUST exist in the vocab list for that seed
- German grammar must be correct (V2 word order, correct cases, verb endings)
- Do NOT submit component-level phrases (like just the LEGO components) — those are auto-generated by the API

## VOCAB BY SEED (words available for phrases)
`;

  for (const [seed, vocab] of Object.entries(vocabBySeed).sort((a, b) => a[0] - b[0])) {
    p += `Seed ${seed}: ${vocab}\n\n`;
  }

  p += `## YOUR LEGOS (${batch.length} total)\n`;
  batch.forEach((l, i) => {
    const comps = l.components ? l.components.map(c => `${c.known}=${c.target}`).join(', ') : 'none';
    p += `${i + 1}. S${l.seed_number} L${l.lego_index} [${l.type}] "${l.known_text}" = "${l.target_text}" (components: ${comps})\n`;
  });

  p += `
## HOW TO SUBMIT
Submit ALL phrases for all LEGOs in ONE curl request:

curl -s -X POST "http://localhost:3471/api/v2/phrases/deu_for_eng" \\
  -H "Content-Type: application/json" \\
  -d '{"phrases": [
    {
      "seed_number": ${batch[0].seed_number},
      "lego_index": ${batch[0].lego_index},
      "build": [
        {"known": "English sentence using the lego", "target": "German sentence CONTAINING ${batch[0].target_text}"},
        ...more BUILD phrases...
      ],
      "use": [
        {"known": "Longer English sentence", "target": "Longer German sentence CONTAINING ${batch[0].target_text}"},
        ...more USE phrases...
      ]
    },
    ...more LEGOs...
  ]}'

## PROCESS
1. For each LEGO, construct BUILD phrases (short German sentences containing the full LEGO target)
2. For each LEGO, construct USE phrases (longer German sentences containing the full LEGO target)
3. Verify EVERY word in your German targets exists in the vocab for that seed
4. Submit via curl
5. If errors, fix the specific issues and resubmit ONLY the failed LEGOs

Work autonomously. NEVER ask questions. Fix errors and retry.`;

  return { batchIdx, seedRange: `${batch[0].seed_number}-${batch[batch.length - 1].seed_number}`, legoCount: batch.length, prompt: p };
});

fs.writeFileSync('/tmp/deu_sonnet_prompts.json', JSON.stringify(prompts));
console.log(`Generated ${prompts.length} prompts`);
prompts.forEach(p => console.log(`  Batch ${p.batchIdx}: ${p.legoCount} LEGOs (seeds ${p.seedRange}), prompt: ${p.prompt.length} chars`));
