const {createClient}=require('@supabase/supabase-js');
require('dotenv').config();
const s=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_KEY);

const pairs = [
[1,"I want to speak {L} with you now.","Voglio parlare {L} con te adesso."],
[2,"I'm trying to learn.","Sto provando a imparare."],
[3,"how to speak as often as possible.","Come parlare il più spesso possibile."],
[4,"how to say something in {L}","Come dire qualcosa in {L}."],
[5,"I'm going to practise speaking with someone else.","Sto per fare pratica parlando con qualcun altro."],
[6,"I'm trying to remember a word.","Sto provando a ricordare una parola."],
[7,"I want to try as hard as I can today.","Voglio provare il più possibile oggi."],
[8,"I'm going to try to explain what I mean.","Sto per provare a spiegare quello che intendo."],
[9,"I speak a little {L} now.","Parlo un po' di {L} adesso."],
[10,"I'm not sure if I can remember the whole sentence.","Non sono sicuro se posso ricordare tutta la frase."],
[11,"I'd like to be able to speak after you finish.","Mi piacerebbe poter parlare dopo che finisci."],
[12,"I wouldn't like to guess what's going to happen tomorrow.","Non mi piacerebbe indovinare cosa succederà domani."],
[13,"You speak {L} very well.","Parli {L} molto bene."],
[14,"Do you speak {L} all day?","Parli {L} tutto il giorno?"],
[15,"And I want you to speak {L} with me tomorrow.","E voglio che tu parli {L} con me domani."],
[16,"He wants to come back with everyone else later on.","Vuole tornare più tardi con tutti gli altri."],
[17,"She wants to find out what the answer is.","Vuole scoprire qual è la risposta."],
[18,"We want to meet at six o'clock this evening.","Vogliamo incontrarci alle sei questa sera."],
[19,"But I don't want to stop talking.","Ma non voglio smettere di parlare."],
[20,"You want to learn his name quickly.","Vuoi imparare il suo nome velocemente."],
[21,"Why are you learning her name?","Perché stai imparando il suo nome?"],
[22,"Because I want to meet people who speak {L}.","Perché voglio incontrare persone che parlano {L}."],
[23,"I'm going to start talking more soon.","Sto per cominciare a parlare di più presto."],
[24,"I'm not going to be able to remember easily.","Non sarò in grado di ricordare facilmente."],
[25,"Are you going to help me before I have to go?","Mi aiuterai prima che io debba andare?"],
[26,"I like feeling as if I'm nearly ready to go.","Mi piace sentirmi come se fossi quasi pronto ad andare."],
[27,"I don't like taking too much time to answer.","Non mi piace prendere troppo tempo per rispondere."],
[28,"It's useful to start talking as soon as you can.","È utile cominciare a parlare appena puoi."],
[29,"I'm looking forward to speaking better as soon as I can.","Non vedo l'ora di parlare meglio appena posso."],
[30,"I wanted to ask you something yesterday.","Volevo chiederti qualcosa ieri."],
[31,"You wanted to speak with me tonight.","Volevi parlare con me stasera."],
[32,"Did you want to show me something?","Volevi mostrarmi qualcosa?"],
[33,"How long have you been learning {L}?","Da quanto tempo stai imparando l'{L}?"],
[34,"He doesn't want to be quiet when other people are here.","Non vuole stare zitto quando ci sono altre persone."],
[35,"She doesn't want to read anything this afternoon.","Non vuole leggere niente questo pomeriggio."],
[36,"We don't want to interrupt the story.","Non vogliamo interrompere la storia."],
[37,"I started to think about it carefully last month.","Ho cominciato a pensarci attentamente il mese scorso."],
[38,"I've been learning for about a week.","Sto imparando da circa una settimana."],
[39,"But I'm a little tired this morning.","Ma sono un po' stanco stamattina."],
[40,"How do you feel at the moment?","Come ti senti al momento?"],
[41,"I feel okay, but I'm starting to feel tired.","Mi sento bene, ma sto cominciando a sentirmi stanco."],
[42,"I was starting to feel better than last night.","Stavo cominciando a sentirmi meglio di ieri sera."],
[43,"I wasn't thinking about how to answer.","Non stavo pensando a come rispondere."],
[44,"Or if I need to improve.","O se ho bisogno di migliorare."],
[45,"I don't need to know everything.","Non ho bisogno di sapere tutto."],
[46,"But I don't worry about making mistakes.","Ma non mi preoccupo di fare errori."],
[47,"Because I think that it's a good thing to make mistakes.","Perché penso che sia una buona cosa fare errori."],
[48,"I don't care about making mistakes.","Non mi importa di fare errori."],
[49,"It's like this, if you know what I mean.","È così, se capisci cosa intendo."],
[50,"I'm not trying to finish as quickly as possible.","Non sto provando a finire il più velocemente possibile."],
[51,"I enjoy doing interesting things with my friends.","Mi piace fare cose interessanti con i miei amici."],
[52,"He wanted to write a letter to his friend last week.","Voleva scrivere una lettera al suo amico la settimana scorsa."],
[53,"She wanted to put his letter in her bag.","Voleva mettere la sua lettera nella sua borsa."],
[54,"We wanted to give you a little more time.","Volevamo darti un po' più di tempo."],
[55,"I don't enjoy waking up when I didn't sleep very well.","Non mi piace svegliarmi quando non ho dormito molto bene."],
[56,"So I can remember how to say a few words.","Così posso ricordare come dire alcune parole."],
[57,"I can't remember how to say what I wanted to say.","Non riesco a ricordare come dire quello che volevo dire."],
[58,"It's interesting when you understand enough words.","È interessante quando capisci abbastanza parole."],
[59,"I know how to do what I need to do next week.","So come fare quello che devo fare la settimana prossima."],
[60,"I don't know how to say enough different words yet.","Non so ancora come dire abbastanza parole diverse."],
[61,"Could you say that again a little more slowly?","Potresti dirlo di nuovo un po' più lentamente?"],
[62,"I'm not sure if I can help you at the same time.","Non sono sicuro se posso aiutarti allo stesso tempo."],
[63,"Are you sure you don't mind helping me?","Sei sicuro che non ti dispiace aiutarmi?"],
[64,"Learning {L} isn't easy but it is fun.","Imparare l'{L} non è facile, ma è divertente."],
[65,"It's important to take time to test yourself.","È importante prendersi il tempo per mettersi alla prova."],
[66,"It's not difficult to find the answer.","Non è difficile trovare la risposta."],
[67,"Why do you want to stop?","Perché vuoi smettere?"],
[68,"What are you looking for?","Che cosa stai cercando?"],
[69,"He didn't want to look after the young dog all afternoon.","Non voleva badare al cane giovane tutto il pomeriggio."],
[70,"She didn't want to tell me where it was.","Non voleva dirmi dove fosse."],
[71,"We didn't want to let anyone hear the truth.","Non volevamo far sentire la verità a nessuno."],
[72,"I think that you're doing very well.","Penso che tu stia andando molto bene."],
[73,"Thank you very much, but I've got more to learn.","Grazie mille, ma ho ancora di più da imparare."],
[74,"Thank you very much for helping me to understand.","Grazie mille per avermi aiutato a capire."],
[75,"Have you got more to learn?","Hai ancora di più da imparare?"],
[76,"I'm very happy with how much I've learnt already.","Sono molto contento di quanto ho già imparato."],
[77,"I'm surprised at how quickly I'm starting to understand.","Sono sorpreso di quanto velocemente sto cominciando a capire."],
[78,"I don't understand what you said.","Non capisco quello che hai detto."],
[79,"When did you start to learn?","Quando hai cominciato a imparare?"],
[80,"I'm not sure when I'll be ready.","Non sono sicuro di quando sarò pronto."],
[81,"When do you want to start?","Quando vuoi cominciare?"],
[82,"I'm not going to wait for you. Why not?","Non ti aspetto. Perché no?"],
[83,"I agree with what you said about your friend.","Sono d'accordo con quello che hai detto del tuo amico."],
[84,"I don't agree with what he said about my friend.","Non sono d'accordo con quello che ha detto del mio amico."],
[85,"I don't know those people.","Non conosco quelle persone."],
[86,"It wasn't possible, unfortunately.","Non era possibile, purtroppo."],
[87,"They are people I don't know.","Sono persone che non conosco."],
[88,"I'm not ready to talk to people I don't know yet.","Non sono ancora pronto a parlare con persone che non conosco."],
[89,"I think that I've done a lot in a short time.","Penso di aver fatto molto in poco tempo."],
[90,"If you can speak more slowly that would be great.","Se puoi parlare più lentamente, sarebbe fantastico."],
[91,"It's difficult to think quickly enough to answer in time.","È difficile pensare abbastanza velocemente per rispondere in tempo."],
[92,"I'd like to keep on doing this for a while.","Mi piacerebbe continuare a farlo per un po'."],
[93,"It's time to go now.","È ora di andare adesso."],
[94,"This is the only way it will work.","Questo è l'unico modo in cui funzionerà."],
[95,"Are you ready to go home on the next bus?","Sei pronto a tornare a casa con il prossimo autobus?"],
[96,"No I'm not ready yet, I need a little more time.","No, non sono ancora pronto, ho bisogno di un po' più di tempo."],
[97,"Yes I'm ready to go as soon as you want.","Sì, sono pronto ad andare appena vuoi."],
[98,"I should consider playing something else.","Dovrei considerare di suonare qualcos'altro."],
[99,"You should ask yourself why it's not working.","Dovresti chiederti perché non funziona."],
[100,"You shouldn't worry about doing something similar.","Non dovresti preoccuparti di fare qualcosa di simile."],
[101,"I'm enjoying finding out more about this language.","Mi piace scoprire di più su questa lingua."],
[102,"We're trying to say that it's not like that.","Stiamo provando a dire che non è così."],
[103,"We're not trying to hear many more words.","Non stiamo provando a sentire molte più parole."],
[104,"We need to change what we're doing.","Dobbiamo cambiare quello che stiamo facendo."],
[105,"That is why he didn't know the answer.","Ecco perché non conosceva la risposta."],
[106,"We don't need to feel happy, we just need to work hard.","Non dobbiamo sentirci felici, dobbiamo solo lavorare sodo."],
[107,"We hoped to see what you were doing.","Speravamo di vedere che cosa stavi facendo."],
[108,"We didn't hope to wake in the middle of the night.","Non speravamo di svegliarci nel mezzo della notte."],
[109,"We must work hard to learn a lot of new words.","Dobbiamo lavorare sodo per imparare molte parole nuove."],
[110,"We're friends, and after we finish I'd like to relax.","Siamo amici, e dopo che finiamo mi piacerebbe rilassarmi."],
[111,"When we learn something new it changes our brain.","Quando impariamo qualcosa di nuovo, cambia il nostro cervello."],
[112,"That was very interesting, and I wasn't expecting it.","Era molto interessante, e non me lo aspettavo."],
[113,"Why can't I remember what you said?","Perché non riesco a ricordare quello che hai detto?"],
[114,"I feel as if I'm doing worse today than yesterday.","Mi sento come se stessi andando peggio oggi di ieri."],
[115,"I don't feel as if I'm ready to have a conversation.","Non mi sento come se fossi pronto a fare una conversazione."],
[116,"This isn't the best choice I could make.","Questa non è la scelta migliore che potrei fare."],
[117,"I'm definitely doing better than I was last time we talked to each other.","Sto sicuramente andando meglio di quando abbiamo parlato l'ultima volta."],
[118,"I feel better than I felt when we were in the pub.","Mi sento meglio di come mi sentivo quando eravamo al pub."],
[119,"Can I ask you something before you leave?","Posso chiederti qualcosa prima che tu vada via?"],
[120,"It's interesting that you like to go by bus.","È interessante che ti piace andare in autobus."],
[121,"It's unusual that you don't like to use your car.","È insolito che non ti piace usare la tua macchina."],
[122,"It's starting to feel easier and I'm excited about how it's going.","Sta cominciando a sembrare più facile e sono entusiasta di come sta andando."],
[123,"I think that's a good idea.","Penso che sia una buona idea."],
[124,"I thought that was a good idea.","Pensavo che fosse una buona idea."],
[125,"I believe that your idea was very good.","Credo che la tua idea fosse molto buona."],
[126,"This work is changing the shape of my brain.","Questo lavoro sta cambiando la forma del mio cervello."],
[127,"That isn't why I wanted to see you.","Non è per questo che volevo vederti."],
[128,"You're like someone I used to know.","Sei come qualcuno che conoscevo una volta."],
[129,"I'm so happy that you're doing so well.","Sono così felice che tu stia andando così bene."],
[130,"That was a surprise, because he's my friend.","È stata una sorpresa, perché è un mio amico."],
[131,"There are too many ideas going around in my head.","Ci sono troppe idee che mi girano in testa."],
[132,"That's less exciting than what she was saying.","È meno entusiasmante di quello che stava dicendo lei."],
[133,"You get to know someone very well when you work together.","Conosci molto bene qualcuno quando lavorate insieme."],
[134,"It's not a problem when you work at something difficult with them.","Non è un problema quando lavori con loro a qualcosa di difficile."],
[135,"I don't know why you think that it's so good.","Non so perché pensi che sia così bello."],
[136,"Of course you can ask her because she's my friend.","Certo che puoi chiederlo a lei, perché è una mia amica."],
[137,"It's more important to talk often than to be perfect.","È più importante parlare spesso che essere perfetti."],
[138,"This was where my friend wanted to meet us.","Qui è dove il mio amico voleva incontrarci."],
[139,"I'm sorry that I need to leave so early.","Mi dispiace che devo andare via così presto."],
[140,"I'm sorry that I can't see what you're trying to show me.","Mi dispiace che non riesco a vedere quello che stai provando a mostrarmi."],
[141,"No problem. Everything is okay.","Nessun problema. Va tutto bene."],
[142,"That's very kind of you and I'm grateful to you for helping.","È molto gentile da parte tua e ti sono grato per l'aiuto."],
[143,"It's the same thing as we were talking about earlier.","È la stessa cosa di cui parlavamo prima."],
[144,"I woke earlier than I wanted to this morning.","Mi sono svegliato prima di quanto volevo stamattina."],
[145,"Why are you not happy any more?","Perché non sei più felice?"],
[146,"Nothing seems to be working since we tried to fix it.","Niente sembra funzionare da quando abbiamo provato a sistemarlo."],
[147,"She was very kind when she saw me feeling nervous.","Era molto gentile quando mi ha visto sentirmi nervoso."],
[148,"He wasn't very patient when I couldn't answer.","Non era molto paziente quando non riuscivo a rispondere."],
[149,"This isn't very difficult, so I hope you'll finish soon.","Questo non è molto difficile, quindi spero che finirai presto."],
[150,"Can you tell me what your name is?","Puoi dirmi come ti chiami?"],
];

(async()=>{
  const knownLang = 'Italian';
  const targetLang = 'italiano';

  const translations = pairs.map(([n, known, target]) => {
    // Replace placeholders
    let k = known.replace(/\{L\}/g, knownLang);
    let t = target.replace(/l'\{L\}/g, "l'" + targetLang)
                   .replace(/il \{L\}/g, "l'" + targetLang)
                   .replace(/\{L\}/g, targetLang);
    return { seed_number: n, target_text: t };
  });

  // Submit in batches of 50
  for (let i = 0; i < translations.length; i += 50) {
    const batch = translations.slice(i, i + 50);
    const resp = await fetch('http://localhost:3471/api/course/ita_for_eng/translate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ translations: batch })
    });
    const data = await resp.json();
    console.log(`Batch ${Math.floor(i/50)+1}: ${data.updated}/${batch.length} updated`);
  }

  // Verify
  const {count} = await s.from('course_seeds').select('*',{count:'exact',head:true})
    .eq('course_code','ita_for_eng').not('target_text','is',null).neq('target_text','');
  console.log(`\nTotal translated seeds: ${count}/668`);
})();
