#!/usr/bin/env node
/**
 * revoice-clips.cjs — move clips that are stranded on a legacy provider's voice
 * onto the voice the course is actually configured to use, and heal every link.
 *
 * WHY (2026-08-04, deu_for_eng): 338 clips were still speaking in Azure voices
 * (de-DE-Conrad/Katja, en-GB-Sonia/Libby/Hollie/Ryan) inside a course whose
 * voice_config has said known=eve / target1=ara / target2=leo (all xAI) since
 * 2026-01. A learner hit a different speaker mid-course. Re-rendering them on
 * their EXISTING voice — which is all repair-silent-clips.cjs can do, because it
 * derives the provider from the row it is repairing — would have faithfully
 * reproduced the wrong voice. This tool takes the target voice from the COURSE,
 * not from the row.
 *
 *   node tools/revoice-clips.cjs deu_for_eng --dry
 *   node tools/revoice-clips.cjs deu_for_eng --limit 6
 *   node tools/revoice-clips.cjs deu_for_eng --concurrency 3
 *
 * TTS costs money. Run only under an approved plan (deu_for_eng re-voice is
 * approved: Kai 2026-08-04). Idempotent: re-running skips ids that are already
 * on the configured voice, so an interrupted run resumes safely.
 *
 * ── Why this is NOT repair-silent-clips.cjs with a flag ─────────────────────
 * The two differ in the one place that matters, the ORDER OF MUTATION.
 *
 * repair-silent-clips re-renders the SAME text at the SAME voice, so the new row
 * collides with the old one on the unique key
 * (course_code, text_normalized, language, role, voice_id) and the old row must
 * be DELETED FIRST. That delete is what makes role='presentation' unsafe there:
 * lego_introductions.presentation_audio_id is ON DELETE CASCADE, so the delete
 * takes the authored introduction row with it. Hence its blanket refusal.
 *
 * A re-voice CHANGES voice_id, which is a column of that unique key. So the new
 * row does not collide, and it can be INSERTED FIRST — links re-pointed while
 * both rows exist — and the old row deleted LAST, once nothing references it.
 * By then the CASCADE has nothing to cascade to. That inversion is what makes
 * presentation clips safe to move here and unsafe to repair there; it is a
 * property of the operation, not a policy difference, which is why it lives in
 * a separate tool rather than behind a flag on that one.
 *
 * ── The links, including the ones the repair tool misses ────────────────────
 * Measured against the live FK catalogue, 2026-08-04:
 *
 *   SET NULL  course_legos / course_practice_phrases / course_seeds
 *             .{known,target1,target2}_audio_id
 *   SET NULL  listening_pod_sentences.{known,target,explainer,note}_audio_id
 *   CASCADE   lego_introductions.presentation_audio_id
 *   CASCADE   course_audio_envelope.audio_id
 *
 * listening_pod_sentences is NOT in repair-silent-clips.cjs's LINK_TABLES, and
 * it holds 72 of deu_for_eng's 73 azure `known` links — repairing one of those
 * rows there would silently null the pod's link. It is covered here.
 *
 * listening_pod_sentences also has ARRAY audio columns (sentence_audio_ids,
 * sentence_known_audio_ids, takeg_audio_ids) which carry NO foreign key at all,
 * so a delete leaves dangling uuids in them with no error. They are captured
 * before anything is deleted and swapped POSITIONALLY (never appended, never
 * deduped — they are ordered segment indexes), under a drift assertion. This
 * used to be a blanket refusal; on fra_for_eng that refused 65 of 140 clips,
 * every one an English pod line stuck in the French male voice.
 *
 * course_audio_envelope rows are dropped by the cascade and regenerated by the
 * envelope backfill — a no-op, and the same trade repair-silent-clips.cjs makes.
 *
 * ── Denormalised durations ──────────────────────────────────────────────────
 * target1_duration_ms / target2_duration_ms on course_legos and
 * course_practice_phrases size the pause between cycles. A new voice means a new
 * duration, so leaving them stale would fix the voice and leave a wrong pause.
 * They are rewritten as the links are re-pointed.
 *
 * ── Unrendered stubs are left alone ─────────────────────────────────────────
 * A row with s3_key LIKE 'pending/%' or a NULL duration_ms was never rendered —
 * there is no audio to re-voice, only a placeholder. Rendering it would mint a
 * duplicate of a clip that already exists on the configured voice. Skipped and
 * reported, never deleted.
 */
require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') })
process.env.PHASE8_NO_LISTEN = process.env.PHASE8_NO_LISTEN || '1'  // never squat :3465

const fs = require('fs')
const os = require('os')
const path = require('path')
const { execFile } = require('child_process')
const { v4: uuidv4 } = require('uuid')
const { PutObjectCommand } = require('@aws-sdk/client-s3')
const { AUDIO_CACHE_CONTROL } = require('../services/shared/audio-cache-control.cjs')
const { canonicalVoiceId } = require('../services/shared/clip-identity.cjs')
const { createClient } = require('@supabase/supabase-js')
const ttsService = require('../services/tts-service.cjs')
const p8 = require('../services/phases/phase8-audio-v13.cjs')
const { toBcp47 } = require('../services/voice-discovery-service.cjs')
const { bumpCourseVersion, bumpCourseRevalidation } = require('../services/shared/course-version.cjs')
const { isHumanVoiceCourse } = require('../services/shared/human-voice-courses.cjs')

const argv = process.argv.slice(2)
const arg = (f, d = null) => { const i = argv.indexOf(f); return i !== -1 && argv[i + 1] ? argv[i + 1] : d }
const COURSE = argv[0] && !argv[0].startsWith('--') ? argv[0] : null
const LIMIT = Number(arg('--limit', 0)) || 0
const DRY = argv.includes('--dry')
const ATTEMPTS = Number(arg('--attempts', 3))
const ROLES = (arg('--roles', '') || '').split(',').filter(Boolean)
/** Deliberately low: sustained xAI load is the root cause of the whole incident. */
const CONCURRENCY = Number(arg('--concurrency', 3))
/**
 * ACCEPTED but no longer consulted. It used to choose the spelling a re-voiced
 * row was STORED under ('bare' eve/ara/leo vs 'prefixed' xai_eve), i.e. it let a
 * course's local habit mint a second identity for one voice. Storage is now
 * always canonical (storedVoiceId) and matching accepts every spelling
 * (voiceSpellings), so the flag only survives so existing invocations and
 * runbooks keep working. Delete it once those are updated.
 */
const SPELLING = arg('--spelling', 'bare')
/**
 * --ids <path>: an explicit JSON array of course_audio ids to re-voice, INSTEAD
 * of the isLegacyVoice() scan.
 *
 * WHY (2026-08-05, fra_for_eng). isLegacyVoice() only recognises a legacy
 * PROVIDER — azure_/elevenlabs_/…Neural. It is blind to the defect Kai actually
 * heard in deu_for_eng: an English `known` clip narrated by one of the course's
 * own xAI TARGET voices, because the pod builder inherited the known-side voice
 * from the target line's character voice instead of from voice_config
 * (docs/audio-repair-2026-08-04/deu_for_eng-revoice-complete.md). fra_for_eng
 * still carries 138 of those. A blanket "voice_id != configured voice" selector
 * would be wrong here — pod TARGET voices are deliberate multi-speaker casting
 * and must not be collapsed — so the policy stays in the caller's query and this
 * flag just carries the resulting list. Everything downstream (stub/human
 * refusal, twin merge, array-slot relinking, truncation gate) is unchanged.
 */
const IDS_FILE = arg('--ids', null)

if (!COURSE) {
  console.error('usage: revoice-clips.cjs <course> [--ids path.json] [--roles a,b] [--limit N] [--concurrency N] [--spelling bare|prefixed] [--attempts N] [--dry]')
  process.exit(1)
}
if (isHumanVoiceCourse(COURSE)) {
  console.log(`${COURSE} is human-voiced only — no TTS ever (Tom 2026-07-25). Nothing to do.`)
  process.exit(0)
}

const supabase = createClient(
  (process.env.SUPABASE_URL || '').trim(),
  (process.env.SUPABASE_SERVICE_KEY || '').trim(),
  { auth: { persistSession: false, autoRefreshToken: false } },
)

const FFMPEG = process.env.FFMPEG || 'ffmpeg'
const FLOOR_MS = 400
const SILENCE_MEAN_DB = -60
/**
 * Truncation is measured against what the TARGET voice does, never against the
 * duration the old voice produced. Measured on deu_for_eng, 2026-08-04, Azure
 * runs 1.4x-1.8x longer than xAI for identical text (target2 96.6 vs 53.6
 * ms/char over 173 and 10,934 clips). Judging an xAI render against its Azure
 * predecessor therefore condemns perfectly good audio: the first pilot rejected
 * "er will Deutsch sprechen" at 1272 ms as a 0.46x shrink when the course's own
 * leo clips predict 1233 ms for that text. The baseline is calibrated at runtime
 * from the course's existing clips on the target voice (p05 of ms-per-char is
 * ~41 against a median of ~54, so 0.6x of median sits below the real floor).
 */
const TRUNCATION_RATIO = 0.6
/** Fallback ms-per-char if a course has no existing clips on the target voice. */
const DEFAULT_MS_PER_CHAR = 55

/** Scalar columns that point at a course_audio id. */
const LINK_TABLES = [
  { table: 'course_legos', cols: ['known_audio_id', 'target1_audio_id', 'target2_audio_id'], durations: true },
  { table: 'course_practice_phrases', cols: ['known_audio_id', 'target1_audio_id', 'target2_audio_id'], durations: true },
  { table: 'course_seeds', cols: ['known_audio_id', 'target1_audio_id', 'target2_audio_id'], durations: false },
  { table: 'listening_pod_sentences', cols: ['known_audio_id', 'target_audio_id', 'explainer_audio_id', 'note_audio_id'], durations: false },
  { table: 'lego_introductions', cols: ['presentation_audio_id'], durations: false },
]
/** No FK, so a delete silently strands the uuid inside the array. Refuse instead. */
const ARRAY_LINK_COLS = [
  { table: 'listening_pod_sentences', col: 'sentence_audio_ids' },
  { table: 'listening_pod_sentences', col: 'sentence_known_audio_ids' },
  { table: 'listening_pod_sentences', col: 'takeg_audio_ids' },
]

/** A voice_id that is not one of ours: prefixed azure/elevenlabs, or a bare
 *  Azure voice NAME ('en-GB-SoniaNeural') — the prefix was applied unevenly. */
function isLegacyVoice(voiceId) {
  const v = String(voiceId || '')
  return /^(azure|elevenlabs)_/.test(v) || /Neural$/.test(v)
}

/** Peak/mean level of a file via ffmpeg volumedetect. null = unmeasurable. */
function measureLevel(file) {
  return new Promise(resolve => {
    execFile(FFMPEG, ['-hide_banner', '-nostats', '-i', file, '-af', 'volumedetect', '-f', 'null', '-'],
      { encoding: 'utf8', maxBuffer: 1 << 22 }, (_e, _o, stderr) => {
        const mean = /mean_volume:\s*(-?[\d.]+) dB/.exec(stderr || '')
        const peak = /max_volume:\s*(-?[\d.]+) dB/.exec(stderr || '')
        resolve(mean && peak ? { meanDb: parseFloat(mean[1]), peakDb: parseFloat(peak[1]) } : null)
      })
  })
}

/**
 * Which voice_config slot a role speaks in. known/target1/target2/presentation
 * are named in voice_config directly; the bookend narration is the known-language
 * narrator, so it follows `known`.
 */
const ROLE_SLOT = {
  known: 'known',
  target1: 'target1',
  target2: 'target2',
  presentation: 'presentation',
  bookend_listen_intro: 'known',
  bookend_listen_outro: 'known',
}

/**
 * The spelling a re-voiced row is STORED under: always canonical
 * (services/shared/clip-identity.cjs), never the course's local habit.
 *
 * This used to follow `--spelling`, storing the bare id when that was what the
 * course predominantly used — which is how a course's habit became a second
 * identity for the same voice. The flag now only affects which EXISTING
 * spellings are recognised (see voiceSpellings), not what gets written.
 */
function storedVoiceId(target) {
  const bare = typeof target === 'string' ? target : target.voiceId
  const provider = typeof target === 'string' ? undefined : target.provider
  return canonicalVoiceId(bare, provider ? { provider } : undefined)
}

/** Every spelling an existing row may carry for this voice — for matching only. */
function voiceSpellings(target) {
  const bare = typeof target === 'string' ? target : target.voiceId
  const set = new Set([bare, `xai_${bare}`, storedVoiceId(target)])
  return [...set]
}

/**
 * What the target voice takes, per character, for this role in this course.
 * Keyed `role|voiceId`; populated once at startup from clips already on the
 * configured voice, which is the only baseline that can judge truncation.
 */
const msPerChar = new Map()

async function calibrate(allClips) {
  for (const [key, rows] of allClips) {
    const rates = rows.map(r => r.duration_ms / String(r.text || '').length)
      .filter(x => Number.isFinite(x) && x > 0).sort((a, b) => a - b)
    if (rates.length >= 20) {
      msPerChar.set(key, rates[Math.floor(rates.length * 0.5)])
    }
  }
}

async function renderVerified(text, voice, language, tmpDir, tag, rateKey) {
  const rate = msPerChar.get(rateKey) || DEFAULT_MS_PER_CHAR
  const expectedMs = Math.round(rate * String(text || '').length)
  let last = null, lastErr = null
  for (let attempt = 1; attempt <= ATTEMPTS; attempt++) {
    try {
      const { audioBuffer } = await ttsService.generateWithRetry(text, voice.provider, {
        apiKey: process.env.XAI_API_KEY,
        voiceId: voice.voiceId,
        language: toBcp47(language),
      })
      // masterAudio can REFUSE a render outright (its tail-defect guard throws
      // "refusing to ship" when a click survives its repair passes). That is a
      // property of the individual render, not of the clip, so it re-rolls here
      // instead of killing the job — 2 of the first 6 pilot clips died that way.
      const { buffer, durationMs } = await p8.masterAudio(audioBuffer, text)

      const probe = path.join(tmpDir, `verify-${tag}-${attempt}.mp3`)
      fs.writeFileSync(probe, buffer)
      const level = await measureLevel(probe)
      try { fs.unlinkSync(probe) } catch {}

      const silent = level && level.meanDb < SILENCE_MEAN_DB
      const short = durationMs < FLOOR_MS
      const truncated = durationMs < TRUNCATION_RATIO * expectedMs
      last = { buffer, durationMs, level, expectedMs }
      if (!silent && !short && !truncated) return last
      console.log(`      attempt ${attempt}: ${silent ? 'SILENT' : short ? `${durationMs}ms < floor` : `${durationMs}ms vs expected ${expectedMs}ms`} — re-roll`)
    } catch (e) {
      lastErr = e
      console.log(`      attempt ${attempt}: render/master threw — ${e.message.slice(0, 90)} — re-roll`)
    }
  }
  if (last) throw new Error(`no attempt produced speech (last ${last.durationMs}ms vs expected ${last.expectedMs}ms, mean ${last.level ? last.level.meanDb : '?'}dB)`)
  throw new Error(`every attempt threw (last: ${lastErr && lastErr.message.slice(0, 110)})`)
}

/** Every scalar link to `audioId`. */
async function captureLinks(audioId) {
  const links = []
  for (const { table, cols } of LINK_TABLES) {
    for (const col of cols) {
      const { data, error } = await supabase.from(table).select('id').eq(col, audioId)
      if (error) throw new Error(`capture ${table}.${col}: ${error.message}`)
      for (const r of data || []) links.push({ table, col, rowId: r.id })
    }
  }
  return links
}

/**
 * Every unconstrained-array reference to a clip, with the exact slots it sits in.
 *
 * These columns carry NO foreign key, so a delete strands the uuid silently and
 * the pod plays a 404 where a sentence should be. The tool used to REFUSE such a
 * clip outright, which on fra_for_eng meant refusing 65 of 140 — every one of
 * them an English pod line stuck in the French male voice, i.e. exactly the
 * defect the run existed to fix. deu_for_eng hit the same wall on 2026-08-04 and
 * the ruling there was that these needed re-linking, not refusal.
 *
 * Positional, never by value: the arrays are ORDERED segment indexes, so the
 * same id may legitimately appear twice and must be swapped in place — never
 * appended, never deduped, never reordered.
 */
async function arrayReferences(audioId) {
  const refs = []
  for (const { table, col } of ARRAY_LINK_COLS) {
    const { data, error } = await supabase.from(table).select(`id, ${col}`).contains(col, [audioId])
    if (error) continue          // column absent on this deployment — nothing to strand
    for (const r of data || []) {
      const arr = r[col] || []
      const indexes = arr.map((v, i) => (v === audioId ? i : -1)).filter(i => i !== -1)
      if (indexes.length) refs.push({ table, col, rowId: r.id, indexes })
    }
  }
  return refs
}

/**
 * Swap `oldId` for `newId` at the captured slots. Serialised through one promise
 * chain: several clips can share a pod row, and two concurrent read-modify-write
 * updates of the same array would silently drop one of the swaps.
 */
let arrayWriteChain = Promise.resolve()
function relinkArrays(refs, oldId, newId) {
  const work = async () => {
    for (const ref of refs) {
      const { data, error: readErr } = await supabase
        .from(ref.table).select(ref.col).eq('id', ref.rowId).single()
      if (readErr) throw new Error(`array read ${ref.table}.${ref.col}#${ref.rowId}: ${readErr.message}`)
      const arr = [...(data[ref.col] || [])]
      for (const i of ref.indexes) {
        if (arr[i] !== oldId) throw new Error(`array drift ${ref.table}.${ref.col}#${ref.rowId}[${i}]: expected ${oldId}, found ${arr[i]}`)
        arr[i] = newId
      }
      const { error: wErr } = await supabase.from(ref.table).update({ [ref.col]: arr }).eq('id', ref.rowId)
      if (wErr) throw new Error(`array write ${ref.table}.${ref.col}#${ref.rowId}: ${wErr.message}`)
    }
  }
  arrayWriteChain = arrayWriteChain.then(work, work)
  return arrayWriteChain
}

/** Point captured links at `newId`, refreshing the denormalised duration. */
async function relink(links, newId, durationMs) {
  for (const l of links) {
    const patch = { [l.col]: newId }
    const spec = LINK_TABLES.find(t => t.table === l.table)
    const m = /^(target[12])_audio_id$/.exec(l.col)
    if (spec.durations && m) patch[`${m[1]}_duration_ms`] = durationMs
    const { error } = await supabase.from(l.table).update(patch).eq('id', l.rowId)
    if (error) throw new Error(`relink ${l.table}.${l.col}#${l.rowId}: ${error.message}`)
  }
}

;(async () => {
  const { data: course, error: cErr } = await supabase
    .from('courses').select('course_code, voice_config').eq('course_code', COURSE).single()
  if (cErr || !course) { console.error(`cannot read course ${COURSE}: ${cErr && cErr.message}`); process.exit(1) }
  const voices = (course.voice_config || {}).voices || {}
  if (!Object.keys(voices).length) { console.error(`${COURSE} has no voice_config.voices — nothing to target`); process.exit(1) }

  console.log(`\nrevoice-clips — ${COURSE}`)
  console.log(`configured voices: ${Object.entries(voices).map(([k, v]) => `${k}=${v.voiceId}/${v.provider}`).join(', ')}`)
  console.log(`storing voice_id in its canonical form (e.g. ${storedVoiceId('eve')}); --spelling ${SPELLING} is accepted and ignored\n`)

  // Every clip in the course, paged; then the ones on a legacy voice.
  let all = [], from = 0
  for (;;) {
    const { data, error } = await supabase.from('course_audio')
      .select('id,role,voice_id,language,text,text_normalized,duration_ms,s3_key,origin')
      .eq('course_code', COURSE).range(from, from + 999)
    if (error) { console.error('read course_audio:', error.message); process.exit(1) }
    all = all.concat(data)
    if (data.length < 1000) break
    from += 1000
  }
  let jobs
  if (IDS_FILE) {
    const wanted = JSON.parse(fs.readFileSync(IDS_FILE, 'utf8'))
    if (!Array.isArray(wanted) || !wanted.length) { console.error(`--ids ${IDS_FILE}: expected a non-empty JSON array of course_audio ids`); process.exit(1) }
    const byId = new Map(all.map(r => [r.id, r]))
    const missing = wanted.filter(id => !byId.has(id))
    jobs = wanted.map(id => byId.get(id)).filter(Boolean)
    console.log(`--ids ${IDS_FILE}: ${wanted.length} requested, ${jobs.length} found in ${COURSE}${missing.length ? `, ${missing.length} not in this course (skipped)` : ''}`)
    const already = jobs.filter(r => ROLE_SLOT[r.role] && voices[ROLE_SLOT[r.role]] && voiceSpellings(voices[ROLE_SLOT[r.role]]).includes(r.voice_id))
    if (already.length) { console.log(`SKIPPING ${already.length} clip(s) already on the configured voice — re-run safe.`); jobs = jobs.filter(r => !already.includes(r)) }
  } else {
    jobs = all.filter(r => isLegacyVoice(r.voice_id))
  }
  if (ROLES.length) jobs = jobs.filter(r => ROLES.includes(r.role))

  // Human-recorded audio is never re-synthesised.
  const human = jobs.filter(r => r.origin === 'human')
  if (human.length) { console.log(`REFUSING ${human.length} origin=human clip(s).`); jobs = jobs.filter(r => r.origin !== 'human') }

  // Never rendered: a placeholder, not a clip. Nothing to re-voice.
  const stubs = jobs.filter(r => /^pending\//.test(r.s3_key || '') || r.duration_ms == null)
  if (stubs.length) {
    const byRole = stubs.reduce((a, r) => ((a[r.role] = (a[r.role] || 0) + 1), a), {})
    console.log(`SKIPPING ${stubs.length} unrendered stub(s) (s3_key pending/ or NULL duration): ${JSON.stringify(byRole)}`)
    console.log(`   these were never rendered — there is no audio to re-voice, and they are left in place, not deleted.`)
    jobs = jobs.filter(r => !(/^pending\//.test(r.s3_key || '') || r.duration_ms == null))
  }

  const unmapped = jobs.filter(r => !ROLE_SLOT[r.role] || !voices[ROLE_SLOT[r.role]])
  if (unmapped.length) {
    console.log(`SKIPPING ${unmapped.length} clip(s) whose role has no voice_config slot: ${[...new Set(unmapped.map(r => r.role))].join(', ')}`)
    jobs = jobs.filter(r => ROLE_SLOT[r.role] && voices[ROLE_SLOT[r.role]])
  }
  if (LIMIT) jobs = jobs.slice(0, LIMIT)

  // A clip whose text already exists on the configured voice cannot be re-rendered
  // there — it would violate the unique key. Its links move to the existing row.
  const byRole = {}
  for (const r of jobs) {
    const slot = ROLE_SLOT[r.role]
    r._target = voices[slot]
    r._targetVoiceId = storedVoiceId(r._target)
    const twin = all.find(x => x.id !== r.id && x.role === r.role && x.language === r.language &&
      x.text_normalized === r.text_normalized &&
      voiceSpellings(r._target).includes(x.voice_id))
    r._merge = twin || null
    const k = `${r.role} ${r.voice_id} -> ${r._targetVoiceId}${twin ? ' (merge)' : ''}`
    byRole[k] = (byRole[k] || 0) + 1
  }

  // Calibrate the truncation baseline off clips ALREADY on the configured voice.
  const buckets = new Map()
  for (const r of all) {
    if (!r.duration_ms || r.duration_ms <= FLOOR_MS || !r.text) continue
    const slot = ROLE_SLOT[r.role]
    if (!slot || !voices[slot]) continue
    if (!voiceSpellings(voices[slot]).includes(r.voice_id)) continue
    const key = `${r.role}|${bare}`
    if (!buckets.has(key)) buckets.set(key, [])
    buckets.get(key).push(r)
  }
  await calibrate(buckets)
  console.log(`calibrated ms-per-char from existing clips: ${[...msPerChar.entries()].map(([k, v]) => `${k}=${v.toFixed(1)}`).join(', ') || '(none — using default)'}\n`)

  const merges = jobs.filter(r => r._merge)
  console.log(`${jobs.length} clip(s) to re-voice — ${jobs.length - merges.length} render, ${merges.length} merge into an existing clip (no TTS)\n`)
  Object.entries(byRole).sort((a, b) => b[1] - a[1]).forEach(([k, v]) => console.log(`   ${String(v).padStart(4)}  ${k}`))
  const ttsChars = jobs.filter(r => !r._merge).reduce((a, r) => a + String(r.text || '').length, 0)
  console.log(`\n   ~${ttsChars.toLocaleString()} characters of TTS\n`)

  if (DRY) {
    for (const j of jobs.slice(0, 25)) {
      console.log(`  [DRY] ${j._merge ? 'MERGE ' : 'RENDER'} ${j.role.padEnd(13)} ${String(j.duration_ms).padStart(6)}ms  ${j.voice_id} -> ${j._targetVoiceId}  ${JSON.stringify(j.text).slice(0, 46)}`)
    }
    if (jobs.length > 25) console.log(`  ... and ${jobs.length - 25} more`)
    console.log(`\nDry run — nothing rendered, nothing written.\n`)
    process.exit(0)
  }

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'revoice-'))
  let revoiced = 0, merged = 0, failed = 0, chars = 0
  const log = []

  const doOne = async (job, i) => {
    const prefix = `[${i + 1}/${jobs.length}] ${job.role} ${JSON.stringify(job.text).slice(0, 38)}`
    try {
      const { data: row, error: readErr } = await supabase
        .from('course_audio').select('*').eq('id', job.id).single()
      if (readErr || !row) { console.log(`${prefix}: gone — skip`); return }
      // The re-read guard against a concurrent run. It asks the same question the
      // selection asked: with --ids that is "is it already on the configured
      // voice?", because an --ids job is by definition NOT a legacy-provider job.
      const done = IDS_FILE ? row.voice_id === job._targetVoiceId : !isLegacyVoice(row.voice_id)
      if (done) { console.log(`${prefix}: already on ${row.voice_id} — skip`); return }

      const arrayRefs = await arrayReferences(row.id)
      const links = await captureLinks(row.id)

      // ── Merge: the configured-voice clip already exists. Move links, drop dup.
      if (job._merge) {
        await relink(links, job._merge.id, job._merge.duration_ms)
        if (arrayRefs.length) await relinkArrays(arrayRefs, row.id, job._merge.id)
        const { error: delErr } = await supabase.from('course_audio').delete().eq('id', row.id)
        if (delErr) throw new Error(`delete after merge: ${delErr.message}`)
        merged++
        console.log(`${prefix}: merged into existing ${job._merge.voice_id} clip ${job._merge.id}, ${links.length} link(s) moved`)
        log.push({ id: row.id, action: 'merged', into: job._merge.id, links: links.length })
        return
      }

      // ── Re-voice: render first, mutate second. A failed render costs nothing.
      const rendered = await renderVerified(row.text, job._target, row.language, tmpDir, row.id,
        `${row.role}|${job._target.voiceId}`)
      chars += String(row.text || '').length

      const newId = uuidv4().toUpperCase()
      const s3Key = `mastered/${newId}.mp3`
      await p8.s3.send(new PutObjectCommand({
        Bucket: p8.S3_BUCKET, Key: s3Key, Body: rendered.buffer, ContentType: 'audio/mpeg', CacheControl: AUDIO_CACHE_CONTROL,
      }))

      // INSERT BEFORE DELETE. voice_id is part of the unique key and it is
      // changing, so both rows coexist — which means the links are never nulled
      // and the presentation CASCADE has nothing to take with it.
      const fresh = { ...row, id: newId, s3_key: s3Key, voice_id: job._targetVoiceId,
        duration_ms: rendered.durationMs, origin: 'tts', file_size_bytes: rendered.buffer.length }
      delete fresh.text_stripped     // GENERATED ALWAYS
      delete fresh.created_at
      delete fresh.updated_at
      delete fresh.word_boundaries   // belonged to the old voice's timing
      const { error: insErr } = await supabase.from('course_audio').insert(fresh)
      if (insErr) throw new Error(`insert: ${insErr.message}`)

      try {
        await relink(links, newId, rendered.durationMs)
        if (arrayRefs.length) await relinkArrays(arrayRefs, row.id, newId)
      } catch (e) {
        await supabase.from('course_audio').delete().eq('id', newId)   // roll back
        throw e
      }

      const { error: delErr } = await supabase.from('course_audio').delete().eq('id', row.id)
      if (delErr) {
        console.log(`${prefix}: re-voiced to ${newId} but old row ${row.id} could not be deleted (${delErr.message}) — links already moved, safe to sweep later`)
      }

      revoiced++
      console.log(`${prefix}: ${row.voice_id} ${row.duration_ms}ms -> ${job._targetVoiceId} ${rendered.durationMs}ms (${rendered.level.meanDb}dB), ${links.length} link(s)${arrayRefs.length ? ` + ${arrayRefs.reduce((n, r) => n + r.indexes.length, 0)} array slot(s)` : ''} -> ${newId}`)
      log.push({ id: row.id, newId, action: 'revoiced', from: row.voice_id, to: job._targetVoiceId,
        wasMs: row.duration_ms, nowMs: rendered.durationMs, meanDb: rendered.level.meanDb,
        links: links.length, arraySlots: arrayRefs.map(r => `${r.table}.${r.col}#${r.rowId}[${r.indexes.join(',')}]`) })
    } catch (e) {
      failed++
      console.log(`${prefix}: FAILED — ${e.message.slice(0, 140)}`)
      log.push({ id: job.id, action: 'failed', error: e.message })
    }
  }

  let cursor = 0
  await Promise.all(Array.from({ length: Math.min(CONCURRENCY, jobs.length) }, async () => {
    for (;;) {
      const i = cursor++
      if (i >= jobs.length) return
      await doOne(jobs[i], i)
    }
  }))
  try { fs.rmSync(tmpDir, { recursive: true, force: true }) } catch {}

  // New ids mean cached client scripts point at rows that no longer exist, which
  // would turn a wrong voice into a 404. Bump so clients refetch metadata.
  if (revoiced + merged > 0) {
    await bumpCourseVersion(supabase, COURSE, 'patch')
    await bumpCourseRevalidation(supabase, COURSE)
    console.log(`\ncourse version + revalidation key bumped — clients will refetch the new audio ids.`)
  }

  const logPath = `/tmp/revoice-${COURSE}-${jobs.length}.json`
  fs.writeFileSync(logPath, JSON.stringify(log, null, 2))
  console.log(`\n${revoiced} re-voiced, ${merged} merged, ${failed} failed, of ${jobs.length}.`)
  console.log(`${chars.toLocaleString()} characters of TTS.`)
  const health = ttsService.getXaiHealth()
  console.log(`xAI health this run: ${health.requests} responses, ${health.stubs} empty (${(health.stubRate * 100).toFixed(2)}%), ${health.cooldowns} cooldown(s).`)
  console.log(`log -> ${logPath}\n`)
  process.exit(failed ? 2 : 0)
})().catch((e) => { console.error('ERR:', e.message); process.exit(1) })
